src/terms.tsx

* Update terms.tsx
Fixed some typos
* Update src/terms.tsx
Co-authored-by: Dev Ojha <ValarDragon@users.noreply.github.com>
Co-authored-by: Seunghoon Ko <55690750+sko-kr@users.noreply.github.com>
Co-authored-by: Dev Ojha <ValarDragon@users.noreply.github.com>

Update terms.tsx (#3)

---

src/components/common/DisplayLeftTime.tsx
src/pages/pools/components/LabsOverview/RewardPayoutCountdown.tsx

I'm a fan of this change, I think it simplifies the interface.
Fixes #74

Issue #74: Remove 0D from time until epoch rewards

---

src/config.ts

`Likecoin` should be `LikeCoin`

Fix LikeCoin name

---

src/config.ts

Regen's IBC has been re-enabled with their latest upgrade!

Re-Enable IBC on Regen

---

src/provider/ibc-history-notifier.tsx

Spelling fixes at lines 111 and 112. Grammar fix at line 111.

Spelling and grammar fixes

---

src/hooks/account/context.tsx

Minor grammar fix at line 66. Spelling fixes at lines 67, 69, and 70.

Minor grammar and spelling fixes

---

src/stores/root.ts

This simple PR adds a new entry to the gamm swap manager.

Added Lum Network on trade toolbox

---

src/dialogs/create-new-pool/index.tsx

Fixed typo in pool creation error message

---

src/stores/root.ts

Transferred from #201, so cloudflare will build

Add missing OSMO pools (Regen, Iov, Ngm) to Trade page.

---

src/config.ts

* modifying explorer link to mintscan

modify konstellation explorer to mintscan

---

src/config.ts

-Add gauge id: 2109 for external incentives to pool 612 (XPRT/UST)
-Makes pool 612 Lockup abled

Add external to 612

---

src/config.ts

Fix Decentr Explorer URL (remove '$' that was before {txHash})

Fix Decentr Explorer URL

---

src/config.ts

update testnet chain-id to osmo-test-4

---

src/config.ts

Provided externals: UMEE (ibc/67795E528DF67C5606FC20F824EA39A6EF55BA133F4DC79C90A8C47A0901E17C)
Liquidity pool: 641 - UMEE/OSMO
30 epoch
24h/7d/14d gauges

Add UMEE External Incentives

---

src/config.ts

https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2252
https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2253
https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2254
https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2255
https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2256
https://lcd-osmosis.imperator.co/osmosis/incentives/v1beta1/gauge_by_id/2257

Add external incentives LIKE for pools 553 555

---

src/config.ts

Adds external incentives for pools 637/638.

Add External Incentives.

---

src/config.ts

Update gauges associated with CHEQ pools (602 and 617)

Update CHEQ gauges

---

src/config.ts

update xprt chain features after chain upgrade to comsos-sdk 44.6 and ibc-go to v2.0.2

---

src/config.ts

Fixed all merge conflicts in #205 to aid it being merged in

Fixed merge conflicts in PR #205

---

src/config.ts

Please HOLD this PR, till i get confirmation from the team.

enable pstake deposits and withdrawals.

---

src/config.ts

Provided externals: UMEE (ibc/67795E528DF67C5606FC20F824EA39A6EF55BA133F4DC79C90A8C47A0901E17C)
Liquidity pool: 642 - UMEE/UST
- 24h  30 epochs & 116,668 UMEE https://www.mintscan.io/osmosis/txs/96160436FC3A8D91CF3F0BCDCE137D14B52336498966DA045B566EB54A42D983
- 7d   30 epochs & 300,002 UMEE https://www.mintscan.io/osmosis/txs/E23DA8D824B06EB678956AFBF751FA83DED6321A376A8D7350F514CD17831654
- 14d  30 epochs & 416,670 UMEE https://www.mintscan.io/osmosis/txs/567557501629CEF2E5DC926BFE4B2A6702D03E2449015A969647B35F372BD6F8
Liquidity pool: 643 - UMEE/ATOM
- 24h  30 epochs & 116,668 UMEE https://www.mintscan.io/osmosis/txs/A5A9B8AC893DC2FBF2B8E70735A51CE6F89DEA060C3532CE0B1817102B00D516
- 7d   30 epochs & 300,002 UMEE https://www.mintscan.io/osmosis/txs/A4B812EBA3850FDF55E38C34124A9FE1376CED966 …

Add UMEE External Incentives to UMEE/UST and UMEE/ATOM

---

src/config.ts

https://www.mintscan.io/osmosis/txs/775F3B2C7CC955CCBB40A71899307480C78C07F9B9B75F7C1316D47750826C9A

enable pstake external incentivisation.

---

src/config.ts

Updated Cerberus CoinGeckoID to coinGeckoId: 'cerberus'

Updated Cerberus CoinGeckoID

---

src/config.ts

Add AKT External to Pool3
gauge 2578 (30 days)

Add AKT External to Pool3

---

src/stores/root.ts

Add Pool 662 CRBRUS/OSMO 0.1% sf

Add Pool 662 CRBRUS/OSMO

---

src/stores/root.ts

Add Pool 638 to Trade router

---

src/config.ts
src/stores/root.ts

Merge fixes to change the BTSG price reference for Osmosis, from pool 574 (ATOM/BTSG) to pool 573 (BTSG/OSMO).

Merge fix change BTSG price reference

---

packages/web/stores/root.ts

We can't access `window` on nodejs environment because there is no `window` global object on nodejs.
It makes "window is not defined" error on execution.
To avoid this problem, we should avoid the access to `window` by checking the typeof `window`.
Ex)
```typescript
if (typeof window === "undefined") {
// In server-side (nodejs), use memory kv store (volatile kv store).
return new MemoryKVStore(prefix);
}
return new LocalKVStore(prefix);
```
After keplr-wallet@v0.9.18, `getKeplrFromWindow()` function checks the window object before access like above way, and it returns `undefined` if `typeof window === "undefined"`
On osmosis frontend, we should avoid the more usage of `window` access, and the main points are usages of kv stores. `IndexedDBKVStore` and `LocalKVStore` requires the browser …

Use `MemoryKVStore` on nodejs environment (on build)

---

src/config.ts
src/stores/root.ts

Remove Unincentivized tokens
KRT, TICK, CTK, CERBERUS, and HOPE (asset infos, chain suggest, trade router)
fixes #337

Remove Unincentivized tokens

---

src/config.ts

Reverts osmosis-labs/osmosis-frontend#360
now that ibc transfers work again--was able to test on frontier
nvm, I could withdraw but not deposit (error 501)

Revert "undo reactivate juno"

---

src/config.ts

Provided externals: $RAC (ibc/6BDB4C8CCD45033F9604E4B93ED395008A753E01EECD6992E7D1EA23D9D3B788)
Liquidity pool: 669 - OSMO/RAC
24h - 90 epochs & 7,500 $RAC https://www.mintscan.io/osmosis/txs/692A91423A83C648C6D99D903F160C1976E57D8F79ADED230A737A2411AB977E
7d - 90 epochs & 12,500 $RAC
https://www.mintscan.io/osmosis/txs/55F52CE3D5072E6C235ADD8D473016B0AC8F348E80341C4C1C0DCB2319E5AAFF
14d - 90 epochs & 30,000 $RAC
https://www.mintscan.io/osmosis/txs/7B922DF5A8CC9F1EEE4BEC26405F915861796D5E23746A23242950587E7F41A3

Add Pool 669 $RAC External Incentives (OSMOS/RAC)

---

.github/workflows/add-to-project.yml

Simple git action to automatically add issues to our project.

New git action to add issues to project

---

src/config.ts

Added coingeckoID 'pool:rac' to display $RAC price

Added coingeckoID 'pool:rac' to display $RAC price

---

src/config.ts

Provided externals: HOPE(ibc/C2A2E9CA95DDD4828B75124B5E27B8401C7D8493BC48353D418CBFC04565899B)
Liquidity pools: 653 - HOPE/OSMO
180 epochs
14d gauges

Frontier - HOPE Incentives (653)

---

src/config.ts

Use `axl` prefix to match naming on Axelar network
Also ran `prettify` on `config.ts`

fix: change prefix for Axelar tokens

---

src/config.ts

Akash v0.16.0

---

src/config.ts

Update GAMM 3 External incentives gauge ID to 3178

Update GAMM 3 External incentives

---

src/config.ts

This pool's last guage has expired and two new gauges have been created

Update pool 625 guages

---

src/config.ts

https://github.com/osmosis-labs/osmosis-frontend/pull/445 but targeting frontier

(frontier) Update LIKE config with new prefix and no-legacy-stdTx

---

src/config.ts
src/stores/root.ts

Re-add tokens (TICK, KRT, CTK), alternativeCoinIds, and pools to trade router

Add 653 to router

---

src/config.ts
src/stores/root.ts

Add fet to main and 681 to router and make 681 bondable

Main - Add FET to main

---

src/config.ts

New gauge:
https://www.mintscan.io/osmosis/txs/397D38EEC8005D94CDB7283CE0B5D0FE565D793333540E198DA9B9245C576239
https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json#L140

Frontier: update old gauge with new one.

---

src/stores/root.ts

-Add RAW price via altCoinId (pool 700 RAW/OSMO)
-Add RAW to Trade router (700 RAW/OSMO, 699 RAW/axlDAI)

Frontier - Add RAW to Trade page

---

src/config.ts

New gauge:
https://www.mintscan.io/osmosis/txs/397D38EEC8005D94CDB7283CE0B5D0FE565D793333540E198DA9B9245C576239
https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json#L140
cherry-pick of #642 into master

Main: update old gauge with new one.

---

README.md

Closes https://github.com/osmosis-labs/docs/issues/36

Small edit on readme to link guides

---

src/stores/root.ts

Add 674 OSMO:DAI to Trade Router

Add 674 OSMO:DAI to Trade Router

---

src/config.ts

Update Terra suggest chain's gas price steps with the latest gas price info [here](https://fcd.terra.dev/v1/txs/gas_prices)

update Terra suggest chain gas price steps

---

src/config.ts

Fix UST price. Was pool:uluna, now pool:uusd

Main - Fix UST price

---

src/stores/root.ts

Add OSMO/WBTC 712 to Trade router

Add OSMO/WBTC 712 to Trade

---

src/stores/root.ts

Add MEME to Trade 701 and MEME price (umeme)

Add MEME to Trade 701

---

packages/web/config/price.ts

Add altCoinIds for:
tick, hope, rac, block, hash, glx, dhk, raw, asvt

Refactor - Add altCoinIds bulk

---

packages/web/config/feature-flag.ts

-Add XPRT/USDC 14-day gauge 3528
-add gauges for pools: 3, 625, 633
-update gauges for pools: 573, 574, 592, 600, 601, 602, 604, 611, 613, 617, 641, 643, 648
Edit: and 2 gauges for 716

Main - Add missing gauges

---

packages/web/components/control/token-select.tsx
packages/web/components/trade-clipboard/index.tsx
packages/web/config/ibc-assets.ts
packages/web/hooks/window/use-token-swap-query-params.ts
packages/web/modals/ibc-transfer.tsx
packages/web/pages/assets/index.tsx
packages/web/stores/assets/index.ts

Two main improvements:
* Fix PSTAKE (multihop IBC assets)
* Show balances in assets page
* Show balance available to deposit
* Use IBC hash's for to/from trade query params

Fix PSTAKE (multihop IBC) & ibc hash query denoms

---

packages/web/config/price.ts

Main - Add Joe price data

---

packages/web/config/ibc-assets.ts

-update axelar satellite URLs to use asset_denom param. e.g., '&asset_denom=uusdc'
-params now accept minimalDenom instead of symbol

Main - Update Axelar Satellite URL params

---

packages/web/config/ibc-assets.ts

Disable all IBC transfers in the frontend to prevent IBC txs being sent from the frontend.

disable all IBC deposit/withdrawal

---

packages/stores/src/account/index.ts
packages/stores/src/account/msg/proto/generated/codecimpl.d.ts
packages/stores/src/account/msg/proto/generated/codecimpl.js

For osmosis v9, there aren’t many major changes to the front-end.
Without this PR, the create pool will not work in osmosis v9.
However, all other functions are expected to work.
Merge this PR when osmosis v9 goes up.

Support osmosis v9

---

packages/web/config/feature-flag.ts

https://www.mintscan.io/osmosis/txs/194A0451CF5660C26524FA4BDC552AF3C86B02A7CFA08B3D2BAF6E941922830B
https://www.mintscan.io/osmosis/txs/3AF6EC3E02FB13E3968F88A574F7CD8E01B6A869EDEF09FDA1FA60547ACEFC94

Update gauge for pool 553 and 555

---

packages/web/components/complex/sidebar-bottom.tsx

Requested by the support team.

Updating the support link text

---

packages/web/config/ibc-assets.ts

https://github.com/osmosis-labs/assetlists/pull/196

Move ustc and lunc to frontier only

---

packages/web/config/ibc-assets.ts

INJ becomes verified (main site, no longer just Frontier), moved up in order

INJ becomes verified, moved up in Assets list

---

packages/web/package.json
packages/web/stores/root.ts

We will support suggest chain experimentally in keplr mobile.
This PR is currently pre-made for seeing preview.
Don't merge before it's ready.

Enable the suggest chain for mobile web experimentally

---

packages/web/components/pixels/pallete.tsx
packages/web/pages/_app.tsx

Replace old Kepler link with new one
`https://wallet.keplr.app/#/osmosis/stake` => [https://wallet.keplr.app/chains/osmosis](https://wallet.keplr.app/chains/osmosis)
`https://wallet.keplr.app/#/osmosis/governance` => [https://wallet.keplr.app/chains/osmosis?tab=governance](https://wallet.keplr.app/chains/osmosis?tab=governance)

Replace old Kepler link with new one

---

packages/web/config/feature-flag.ts

Adds new pool 748 incentive gauge-id of 21736

Add ECH/USDC Pool 748 Incentive

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

Add GLTO price

---

packages/web/config/ibc-assets.ts

via isUnstable = true
chain halted https://explorer.microtick.zone/proposals/20

disable Tick deposit/withdraw

---

packages/web/config/ibc-assets.ts

temporary disablement for security reasons:
https://twitter.com/Axl_Satellite/status/1554259002531500032

disable DOT and WGLMR

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

This contains a commit running `yarn lint:fix` in order to make the pre-xommit hooks pass.

Add Tgrade (TGD) price

---

packages/web/components/trade-clipboard/index.tsx

* Fix estimates content clip in WebKit browsers
* Speed up animations

Trade UX tweaks

---

packages/web/config/chain-infos.ts

https://www.coingecko.com/en/coins/agoric

Add BLD CoingeckoID

---

packages/web/pages/disclaimer/index.tsx

Add rektdrop disclaimer

---

packages/web/components/complex/pool/create/step1-set-ratios.tsx
packages/web/components/input/input-box.tsx
packages/web/pages/pool/[id].tsx

Fixes the following
* #764 
* #732

Bug fixes 2

---

packages/web/config/chain-infos.ts
packages/web/config/feature-flag.ts
packages/web/config/price.ts

Please include the incentives for O9W. Many thanks.

O9W incentives

---

packages/web/config/ibc-assets.ts

revert evmos withdrawal change

---

packages/web/config/ibc-assets.ts

https://wallet.keplr.app/chains/osmosis/proposals/332

Verify stATOM

---

packages/web/components/input/input-box.tsx
packages/web/components/trade-clipboard/index.tsx
packages/web/config/user-analytics-v2.ts

- Close #814 
- Add `Swap: Input box clicked` event
- Add missing event properties

Fix Amplitude event name typo & Add an event to track

---

packages/web/modals/index.tsx
packages/web/modals/pre-transfer.tsx
packages/web/pages/assets/index.tsx

https://t.me/c/1430596792/14261

Mobile: add pre transfer modal

---

packages/web/config/ibc-assets.ts

was disabled due to chain halt. Chain has since resumed

Re-enable ROWAN

---

packages/web/config/feature-flag.ts
packages/web/config/user-analytics-v2.ts
packages/web/pages/assets/index.tsx

On Amplitude, property value should be a number for aggregation.

Change some properties' type from string to number

---

packages/web/config/ibc-assets.ts

Verified in https://www.mintscan.io/osmosis/proposals/333

Add Axelar

---

packages/web/config/feature-flag.ts

Modeled after [this](https://github.com/osmosis-labs/osmosis-frontend/pull/776) example

Add ext osmo gauge to pool 806

---

packages/web/components/alert/temp-banner.tsx
packages/web/components/alert/tx-event-toast.ts
packages/web/config/feature-flag.ts
packages/web/pages/_app.tsx

Going forward, we can toggle a flag that will show UI that the chain is halted.
Decided to not modify tx sending logic.

Add halt UI

---

packages/web/config/feature-flag.ts

- This changes the IS_HALTED to false.

Turn off halted network banner

---

packages/web/config/ibc-assets.ts

Reverts osmosis-labs/osmosis-frontend#874

Revert "Disable EVMOS temporarily"

---

packages/web/config/chain-infos.ts
packages/web/config/feature-flag.ts
packages/web/config/ibc-assets.ts
packages/web/config/price.ts

- show stJUNO on the asset pane
- show the stJUNO price on pool 817
- add gauge to pool 817

Fix stJUNO

---

packages/web/config/feature-flag.ts

Updates external incentives for STARS pools for the following 62 epochs
Ref: https://www.mintscan.io/osmosis/txs/9E7618EE2873D88009614F3EB178F4C58F8FA3983C9F05D96A98284451EFEA9D

update external incentives gauges for Stargaze

---

packages/web/config/chain-infos.ts

SVG token picture does not show well.
change to use the png one

Update tori picture

---

packages/web/config/feature-flag.ts

Updated external incentives for OSMO:CHEQ Pool #602 and ATOM:CHEQ Pool #617

chore: Add updated CHEQ gauges

---

packages/stores/src/bridge-history/index.ts
packages/stores/types/bridge-history/index.d.ts
packages/web/config/ibc-assets.ts
packages/web/integrations/axelar/index.ts
packages/web/integrations/axelar/source-chain-config.ts
packages/web/integrations/axelar/transfer.tsx
packages/web/integrations/axelar/types.ts
packages/web/stores/root.ts

Adds WETH Integrated Axelar Transfer
Works in local testing

Add WETH Integrated Axelar Transfer

---

packages/web/config/feature-flag.ts

Rebus LBP no longer active on this pool.
Leaving commented out for ease of formatting any future LBPs

Remove Rebus LBP promotion

---

packages/web/config/ibc-assets.ts

STRD/OSMO now incentivised in: https://www.mintscan.io/osmosis/proposals/345

Add Stride to main site

---

packages/web/config/ibc-assets.ts
packages/web/config/price.ts

1. Update lambda price pool id from `823` LAMB/ATOM to `826` LAMB/OSMO
2. Fix wrong ibc channel

Update lambda price pool id

---

packages/web/config/feature-flag.ts

old gauge expired, new gauge added

add new 810 gauge

---

packages/web/config/feature-flag.ts
packages/web/config/price.ts

Added the wrong pool by mistake

fix price pool

---

packages/web/config/chain-infos.ts
packages/web/config/feature-flag.ts
packages/web/config/ibc-assets.ts
packages/web/config/price.ts

- add stOSMO ibc asset
- add stOSMO price on pool
- add pool 833 gauge

add stOSMO (ibc asset, pool price and gauge)

---

packages/web/localizations/dayjs-locale-ko.js
packages/web/localizations/en.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/stores/user-settings/language.tsx

#919
I added a Korean translation, but it needs to be reviewed. Also, some translations need to be discussed. Can I discuss it with  @dogemos ?
for better review please check the link below
https://www.diffchecker.com/RuOJhW6f

add Korean

---

packages/web/localizations/dayjs-locale-es.js
packages/web/localizations/es.json
packages/web/stores/user-settings/language.tsx

This is the first version of the Spanish language for Osmosis
- @jonator How is the dayjs-locale generated?

Español esta aqui amigos

---

packages/web/config/feature-flag.ts

Adding gauges for Rebus pool 813

add gauge for Rebus pool 813

---

packages/web/config/chain-infos.ts
packages/web/config/feature-flag.ts

price by pool 837 OSMO/IST.
gaugeId 29948 on pool 837

Add IST price and Gauges

---

packages/web/config/feature-flag.ts

- update pool 817 juno/stjuno external rewards gauge ID

update pool 817 gauge id

---

packages/web/config/price.ts

Add IST price

---

packages/web/localizations/fr.json

Correct some word in French language

Correct some word in French language

---

packages/stores/src/account/msg/proto/generated/codecimpl.d.ts
packages/stores/src/account/msg/proto/generated/codecimpl.js

[osmosis-temp.zip](https://github.com/osmosis-labs/osmosis-frontend/files/10004202/osmosis-temp.zip)
There is a problem because the compile method of protobuf that we are currently using is outdated.
For now, use the above method.
Use
```
yarn install
sh ./scripts/predefine-proto.sh
sh ./scripts/define-proto.sh
```
The output is created in the ./output directory.
In predefine-proto.sh, you can select files to compile.

Update protobuf for v13

---

packages/web/localizations/dayjs-locale-zh-tw.js
packages/web/localizations/zh-tw.json
packages/web/stores/user-settings/language.tsx

Tested on https://osmosis-frontend-web-three.vercel.app
Feedbacks gathered from a Traditional Chinese crypto community for ~1 week

Add Traditional Chinese translation

---

packages/web/config/feature-flag.ts

update pool 803 atom/statom external rewards gauge ID

add new_gauge_803_30074

---

packages/web/localizations/zh-tw.json

Left = Fixed preview / Right = Current
APY text before fix
APY text after fix

Urgent fix for zh-tw

---

packages/web/localizations/zh-tw.json

Fix content overflow on zh-tw

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

-correct stargaze cgid
-uncomment prices.ts file
Does not add load time

Minor Prices Fixes

---

packages/web/config/chain-infos.ts

Update Chihuahua Chain Suggest Fees as per Chain Registry (same as https://chihuahua.omniflix.co/ 's suggested chain config)

Update Chihuahua Chain Suggest Fees

---

packages/web/config/ibc-assets.ts

Unverified because Marble no longer receives incentives.

Changed Marble to unverified

---

packages/web/localizations/dayjs-locale-zh-tw.js

Copy & paste and forgot to update mistakes...

Fix zh-tw format

---

packages/web/styles/globals.css

Feat Scrollbars on windows

---

packages/web/config/feature-flag.ts

Replace expired gauge ids with new ones

Update Osmo/Lamb pool gauge id

---

packages/web/config/feature-flag.ts

adds a gauge id for STRD incentives on the stSTARS / STARS pool (810)
transaction: https://www.mintscan.io/osmosis/txs/740E019C39F750F923DA664EBFCBD4DE23093BAE4BEED5786B2FB2CECAC0FE4F

add stSTARS / STARS gauge

---

packages/web/config/ibc-assets.ts

Since IBC transfer issue was fixed

Re-enable bJuno

---

packages/web/config/feature-flag.ts

adds a new stOSMO / OSMO gauge of 300k STRD for 30 days

add new stOSMO / OSMO gauge

---

packages/web/config/ibc-assets.ts

DARC now unstable

---

packages/web/config/ibc-assets.ts

make unstable since channel is down

Disable DIG

---

packages/web/config/feature-flag.ts

adds gauge 30144 (500 STRD / day for 30 days) to pool 817 (stJUNO / JUNO)

add gauge 30144

---

packages/web/localizations/es.json

I had to check where this text was being shown to make this edit.

Redundancy on Spanish Translation. Minor correction

---

packages/web/config/ibc-assets.ts

Proposal 369 https://www.mintscan.io/osmosis/proposals/369

Add stOSMO to main

---

packages/web/config/feature-flag.ts

reference: 
https://www.mintscan.io/osmosis/txs/5E2BA2AE3EB9454994B00635FD7ABF1F3D254B695EC43A732E45BAD8FE8EBB52

update STARS external incentives

---

packages/web/config/price.ts

Was using old ECH pool 747. Switched to 848 ECH/OSMO

Fix ECH price

---

packages/web/config/chain-infos.ts

Remove foo from defaul coin asset

Remove Foo

---

packages/web/config/ibc-assets.ts

IST token now isVerified
Osmosis Governace trusts the token: https://www.mintscan.io/osmosis/proposals/365

IST to Main

---

packages/web/config/ibc-assets.ts

Ixo changed its chain id from impacthub-3 to ixo-4

Unstable Ixo

---

packages/web/config/price.ts

based on seeing this: https://github.com/osmosis-labs/assetlists/pull/300
and that fact the swap fee is closer to the standard

Update IMV price from 864 spot to 866 spot

---

packages/web/config/chain-infos.ts

Correcting Medasdigital chain name to match pretty name on chain reg

Correcting Medasdigital chain Name

---

packages/web/config/ibc-assets.ts

Governance removed incentives from DSM pool.

Unverified DSM

---

packages/web/config/ibc-assets.ts

Governance removed incentives from Darc pool.

Unverified DARC

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts

Validated transfers of LUNC and USTC both directions.
Both chains governance approved:
https://www.mintscan.io/osmosis/proposals/374
https://ping.pub/terra-luna/gov/11018

Re-enable Terra Classic tokens LUNA, USTC

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts

Change : to / for USK denom to resolve chain suggest issue
Resolves https://github.com/osmosis-labs/osmosis-frontend/issues/1132

Fix Kujira Suggest Chain

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts

Update IXO chain id to ixo-4
Resolves https://github.com/osmosis-labs/osmosis-frontend/issues/1116

Fix IXO Chain ID

---

packages/web/config/ibc-assets.ts

Reverts osmosis-labs/osmosis-frontend#1127
Incentives haven't been removed yet

Revert "Unverified DSM"

---

.github/workflows/push-docker-images.yaml

This PR adds a tag to the docker images pushed to our registry.

[docker] Add additional tag to Docker Image

---

packages/web/config/chain-infos.ts

Keplr's Secret Network endpoint works, Scrt's doensn't

SCRT endpoint from SCRT Network to Keplr

---

packages/web/config/ibc-assets.ts

Re-enable IOV

---

packages/web/config/ibc-assets.ts

https://www.mintscan.io/osmosis/proposals/384

Add WMATIC to main

---

packages/web/config/feature-flag.ts

add updated 7 and 14 days gauges

add updated REBUS gauges

---

packages/web/components/navbar-osmo-price.tsx
packages/web/pages/assets/index.tsx
packages/web/pages/index.tsx
packages/web/pages/pool/[id].tsx

Some Amplitude events did not match the expected type from the dashboard. Perhaps, a good idea would be to use the amplitude CLI to generate these types.

improvement: Correct Types for Amplitude Events

---

packages/web/config/ibc-assets.ts

Sifchain unstable (halted)

---

packages/web/config/feature-flag.ts

replace old stOSMO / OSMO gauge id with new STRD gauge id

add STRD gauge to stOSMO / OSMO pool

---

packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

Translation values are mainly broken by https://github.com/osmosis-labs/osmosis-frontend/commit/6c343b5d298433d0c0771d58383bb7b1cdf77569
Some are additional fixes

Fix zh-tw zh-hk translations

---

packages/stores/src/queries-external/filtered-pools/filtered-pools.ts

Updates data more often (not every 2 mins)
Requested by @IbrarMakaveli

Update pools endpoint

---

packages/web/config/chain-infos.ts

According to changes in chain-registry we want to update rpc & api endpoints
Reference pull request in chain-registry: https://github.com/cosmos/chain-registry/pull/1202

Update to rpc and api endpoints for LumenX

---

packages/stores/src/queries/incentives/gauge-by-id.ts

Handle empty distributed coins

---

packages/web/components/alert/toast.tsx
packages/web/components/trade-clipboard/index.tsx

https://user-images.githubusercontent.com/74899114/212817429-5b6cea74-4ca3-4629-92f4-6c7c7d856598.mov

Fix `Application error: a client-side exception` through change the input handler condition in `<TradeClipboard />`

---

packages/web/config/chain-infos.ts

Estimated Fee based on what I see in a Metamask tx from Canto.io

Update Canto fee

---

packages/web/components/assets/pool-assets-icon.tsx

With addition of stableswap, 3 pools will be more important. Let's show all 3 token icons instead of 1 icon and "+ 2". After 3 tokens, we show "+x".

Show 3 token icons

---

packages/pools/src/errors.ts
packages/stores/src/ui-config/errors.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/components/localization/translate-error.ts
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

fix: Show Not Enough Pool Liquidity on Huge Swaps

---

packages/web/pages/api/active-gauges.ts

-and change duration_1_week to duration_upcoming_soon in case we wanted to deviate from 7 days.

Filter completed gauges

---

packages/web/config/price.ts

This updates the DYS/OSMO to the new pool "905"

update DYS OSMO pool

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

Add HOPERS price

---

packages/web/config/chain-infos.ts

Update Canto chain-info

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

Add Mars price

---

packages/web/config/ibc-assets.ts

Add WYND to Main

---

packages/web/config/chain-infos.ts

**What is the purpose of the change**
- Update gas step price
**Brief Changelog**
- Update gasPriceStep parameter
**Documentation and Release Note**
- Does this pull request introduces a new feature or user-facing behaviour changes? yes
- How is the feature or change documented? yes

feat!: update gas step price

---

packages/web/config/ibc-assets.ts

via isVerified: true
matched incentives program authorised by governance: https://www.mintscan.io/osmosis/proposals/424

sktATOM to MAIN

---

packages/web/localizations/dayjs-locale-pt-br.js
packages/web/localizations/pt-br.json
packages/web/stores/user-settings/language.tsx

I'm native brazilian portuguese speaker. I tried adapt the translation to something that can be approximately understandable. I think is good atm.

add Brazilian Portuguese translation

---

packages/web/config/chain-infos.ts

Verifiable via Chain Registry: https://github.com/cosmos/chain-registry/blob/master/planq/assetlist.json

Fix Planq symbol: PLANQ -> PLQ

---

packages/web/config/ibc-assets.ts

update evmos ibc transfer external url

---

packages/web/components/trade-clipboard/index.tsx
packages/web/pages/index.tsx
packages/web/pages/pools/index.tsx

* Add stEVMOS to swap router (frontier) #1353 
* Fix overflow issue with rate field

Hotfix: stEVMOS routing, rate overflow

---

packages/stores/src/queries/lockup/account-locked.ts
packages/web/pages/pool/[id].tsx

Hotfix: show multiple locks in pool details page

---

packages/web/config/ibc-assets.ts

https://www.mintscan.io/osmosis/proposals/457

Move CMST to Main

---

packages/web/components/complex/all-pools-table.tsx
packages/web/components/input/search-box.tsx
packages/web/utils/formatter.ts

* Add new pools table amplitude events

Hotfixes & Amplitude events

---

packages/web/config/ibc-assets.ts

Restore Bostrom BOOT IBC Transfer

---

packages/web/localizations/fa.json

better translate.

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts

Update IXO Chain Id

---

packages/web/components/assets/icon.tsx
packages/web/components/complex/all-pools-table.tsx
packages/web/components/complex/pool/create/step3-confirm.tsx
packages/web/components/complex/transfer.tsx
packages/web/components/control/checkbox.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/modals/lock-tokens.tsx
packages/web/public/icons/sprite.svg

Improve the sorting and filtering experience of the pools page by adding a checkbox dropdown to select the relevant content to display.

feat: Improve Sorting and Filtering Experience

---

packages/stores/src/ui-config/trade-token-in-config.ts

* Prevent quoting errors from crashing frontend, display routing error instead.

fix: capture errors

---

packages/web/integrations/ethereum/metamask.ts

* minor fix: handling rejected sends- cleanup
For native EVM token deposits, match other types of transfers (ERC20, IBC) behavior by also closing the transfer modal when the transfer is rejected.

Hotfix: rejecting native deposit send tx (metamask)

---

packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

Fix incorrect entries for zh-tw & zh-hk

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts

Add JUNOX (Juno Testnet)

---

packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

```
PASS  localizations/__tests__/localizations.test.ts (16.09 s)
Localization JSON files
✓ should have the same keys (5 ms)
✓ should have all keys be found somewhere in tsx source files (2373 ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
```

Remove Unused Localization Keys

---

packages/pools/src/__tests__/routes.spec.ts
packages/pools/src/routes.ts
packages/stores/src/ui-config/trade-token-in-config.ts

* Fix bug with base case of adding first pool to route
* Improve router by swapping in and out tokens to look for better routes there, then inverting those (since our pool route finder is greedy by TVL)
* Lower max pools from 5 to 4

Router improvements

---

inlang.config.js

- add standard lint rules (https://github.com/inlang/standard-lint-rules)
- use `getLanguages` function and thereby clean up the config

chore: update inlang config

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

Add FLIX price

---

packages/web/config/ibc-assets.ts

stOSMO, stLUNA, stJUNO, stSTARS

Stride LSDs to Main

---

packages/web/config/chain-infos.ts

as per https://github.com/osmosis-labs/assetlists/pull/507

Correct LIGHT exponent from 6 to 9

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

from CoinGeckoID to Pool 1018 spot price

Update PEPE Price

---

packages/web/components/trade-clipboard/index.tsx

I used the amount and spot price to calculate slippage (as was used in the keplr message in the past).
But this was yielding weird results.
Now I just calculate simply from the percentage.

Hotfix: fix slippage calc

---

packages/web/config/generate-wallet-registry.ts
packages/web/integrations/keplr-walletconnect/chain-wallet.ts
packages/web/integrations/keplr-walletconnect/client.ts
packages/web/integrations/keplr-walletconnect/index.ts
packages/web/integrations/keplr-walletconnect/main-wallet.ts
packages/web/integrations/keplr-walletconnect/registry.ts
packages/web/integrations/keplr-walletconnect/utils.ts
packages/web/modals/wallet-select.tsx

While Keplr is working on their Walletconnect V2 fixes, It's a good idea to use V1 in the meantime. This PR adds a Cosmoskit 
Wallet for WalletConnect v1.

feat: Create Keplr Walletconnect V1 Cosmoskit Wallet

---

packages/web/config/ibc-assets.ts

Lambda Unstable (expired IBC client)

---

packages/web/config/feature-flag.ts
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

Pending additional review.
Exact publish time TBD

Add Autonomy Banner

---

packages/web/config/chain-infos.ts
packages/web/config/price.ts

related with https://github.com/osmosis-labs/osmosis-frontend/pull/1162

Update chain-infos.ts to add IBCX

---

packages/web/config/chain-infos.ts
packages/web/package.json
packages/web/pages/_app.tsx
yarn.lock

This is just the scaffold for using launch darkly.
https://app.clickup.com/t/8677h2rqm

setup launch darkly

---

packages/web/config/ibc-assets.ts

Hi LAMB has replaced its inactive ibc client to active client, please help to reactive it in Osmosis Frontier.
Here is passed [proposal](https://www.mintscan.io/osmosis/proposals/511)

Update LAMB status

---

packages/web/pages/index.tsx
packages/web/pages/pool/[id].tsx

* Filter CL pools from router
* Redirect pool detail page to `pools/` if CL pool (same behavior if pool is not found)
We'll be ready to use the useFlags hook for the other CL items as they are added.

(CL) Concentrated liquidity feature flags

---

packages/web/components/cards/app-display-card.tsx
packages/web/components/cards/hero-card.tsx
packages/web/components/cards/icon-link.tsx
packages/web/pages/apps/index.tsx

Fix link bug.
Small styling changes

Final app store fixes

---

packages/web/config/ibc-assets.ts

Move qAssets to main after https://www.mintscan.io/osmosis/proposals/517
Added verification flag for each qasset
Did not test - flag change

qAssets to Main

---

packages/web/config/chain-infos.ts

update kujira rpc and lcd. current ones are doing a http redir to cosmos.directory.
n/a
rpc/ld updated
withdraw to kujira
(tested locally)
- Does this pull request introduce a new feature or user-facing behavior changes? (no)
- How is the feature or change documented? (not applicable)

update kujira rpc/lcd

---

packages/stores/src/ui-config/manage-liquidity/index.ts
packages/stores/src/ui-config/manage-liquidity/remove-concentrated-liquidity.ts
packages/web/components/control/slider.tsx
packages/web/components/my-position-card/expanded.tsx
packages/web/hooks/ui-config/use-remove-concentrated-liquidity-config.ts
packages/web/localizations/en.json
packages/web/modals/remove-concentrated-liquidity.tsx
packages/web/pages/pool/concentrated-liquidity-pool.tsx

Closes: #XXX
> Add a description of the overall background and high level changes that this PR introduces
_(E.g.: This pull request improves area A by adding ...._
Please provide a link to the ClickUp task for this pull request:
_(for example:)_
- _This adds frontend_asset_name to page_name_
- _Adds a new button for ..._
- _Removes the ..._
\*(Enter here)
_(Please pick either of the following options)_
_(or)_
This change has not been tested locally, because (to-be-explained-why...)
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
- How is the feature or change documented? (not applicable / …

(CL) Remove liquidity modal

---

packages/web/pages/api/broadcast-transaction.ts

Fix endpoint validation in `broadcast-transaction`

fix: Endpoint Validation

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/web/components/chart/concentrated-liquidity-depth.tsx
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts

- Uses current price in pool, instead of last price in chart data to place the current price bar (avoids issue if API is out of date or inaccurate)
- Tweak some logic for how price range is stored
- Code cleanup

(CL) Add liq: fix sliders, code cleanup

---

packages/math/src/pool/concentrated/math.ts
packages/stores/src/account/__tests_e2e__/positions.spec.ts
packages/stores/src/account/index.ts
packages/stores/src/account/msg-opts.ts
packages/stores/src/ui-config/manage-liquidity/remove-concentrated-liquidity.ts
packages/web/components/cards/my-position/expanded.tsx
packages/web/components/cards/my-position/index.tsx
packages/web/hooks/ui-config/use-remove-concentrated-liquidity-config.ts
packages/web/modals/increase-concentrated-liquidity.tsx
packages/web/modals/remove-concentrated-liquidity.tsx

[ClickUp Task URL](https://app.clickup.com/t/863gxjgq9)
- Add remove liquidity message
- Some cleanup of UI config and views
- Fix: displaying full range prices in my position card header
- Remove all liquidity (position is deleted) or remove some liquidity, should work

(CL) Add remove liquidity message

---

packages/web/config/chain-infos.ts
packages/web/config/ibc-assets.ts
packages/web/config/price.ts

This PR aims to add Nolus mainnet configurations. 
All IBC channels are tested and work as expected
Pool: 1041 is created usdc/unls

Add Nolus mainnet

---

.vscode/extensions.json
inlang.config.js
package.json
packages/web/package.json
yarn.lock

Updated inlang to include the ide extension.

use inlang ide extension

---

packages/web/config/ibc-assets.ts

NLS asset upgrade to Main site
Adds isVerifdied true to NLS in ibc-assets.ts

NLS to main

---

packages/web/pages/index.tsx

- revert / combine changes to made modal + ad banner justified right

trade clipboard styles update

---

packages/web/components/ad-banner/ad-banner-cms.json

Fix autonomy link in ad banner

---

packages/stores/src/account/base.ts
packages/web/components/ad-banner/ad-banner-cms.json
packages/web/components/table/assets-table.tsx
packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/ibc-assets.ts

Stage -> Master

---

packages/web/config/generate-chain-infos/utils.ts
packages/web/config/generate-wallet-assets/__tests__/utils.spec.ts
packages/web/config/generate-wallet-assets/utils.ts
packages/web/package.json
yarn.lock

Use our Chain Info as a primary source of truth to generate our wallet assets. That way, new assets that have not been added to the Comsos-Kit registry will be available on our end.  
- Simplify https://github.com/osmosis-labs/osmosis-frontend/blob/c03045ec05bbb11ead4e7f94c6d07c93fc73970f/packages/web/config/generate-wallet-assets/utils.ts `getAssetLists` function. 
- Do not show console warns on wallet assets tests.

improvement: Wallet Assets Generation

---

packages/web/config/generate-chain-infos/utils.ts
packages/web/config/generate-wallet-assets/__tests__/utils.spec.ts
packages/web/config/generate-wallet-assets/utils.ts
packages/web/package.json
yarn.lock

- Improve wallet assets generation

Publish Stage

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

To restore connection with LumenX infra--deposit was not possible.
- _This adds new nodes for lumenx in source-chain-config.ts
- _Updates price for ROAR_

Update LumenX Nodes

---

packages/stores/src/account/README.md

Provide a README Document for Guidance on Message Creation and Addition

improvement: Add Account Store Message README

---

packages/stores/src/queries-external/filtered-pools/types.ts
packages/stores/src/queries-external/filtered-pools/utils.ts

Adds CL pool from imperator optimized/filtered/sorted pools query.
[ClickUp Task URL](https://app.clickup.com/t/861mwk0t6)
- Adds CL pool parsing for response from imperator filtered pools query

(CL) Add stream pool

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

To add QSR pricing to 1059 spot
define pool:uqsr in price.ts, and add coingecko_Id for qsr in source-chain-config.ts
This change has not been tested locally, because the change to so small.

Add QSR Price

---

packages/web/components/ad-banner/ad-banner-cms.json

Update limit orders ad banner to go to TFM instead of Autonomy

---

packages/web/config/price.ts

To update the pricing pool of QSR from 1059 to 1060.
Change pool id for qsr in price.ts
This change has not been tested locally, because it;s such a small change

Update QSR Price

---

packages/math/src/pool/concentrated/const.ts

I updated the min tick, but I forgot to also update the min spot price, causing the tick calculations to be incorrect

(CL) Fix: min spot price

---

packages/stores/src/account/osmosis/types.ts

(CL) Swap fixes

---

packages/web/components/ad-banner/ad-banner-cms.json

update calc fi url in banner

---

packages/proto-codecs/scripts/get-proto.sh
packages/proto-codecs/src/codegen/osmosis/concentrated-liquidity/tx.amino.ts
packages/proto-codecs/src/codegen/osmosis/concentrated-liquidity/tx.ts
packages/proto-codecs/src/codegen/osmosis/lockup/tx.amino.ts
packages/proto-codecs/src/codegen/osmosis/lockup/tx.ts
packages/proto-codecs/src/codegen/osmosis/poolmanager/v1beta1/tx.amino.ts
packages/proto-codecs/src/codegen/osmosis/poolmanager/v1beta1/tx.ts
packages/proto-codecs/src/codegen/osmosis/superfluid/tx.amino.ts
packages/proto-codecs/src/codegen/osmosis/superfluid/tx.ts
packages/stores/src/account/amino-converters.ts
packages/stores/src/account/base.ts
packages/web/components/swap-tool/index.tsx
packages/web/components/swap-tool/promo-drawer.tsx

- Update proto codecs to include new amino names
- Fix promo banner height

fix: Display Promo and Update Codecs With New Amino Names

---

packages/web/components/funnels/concentrated-liquidity/intro.tsx
packages/web/components/navbar/index.tsx
packages/web/components/stepper/index.tsx
packages/web/tailwind.config.js

- Match learn more button with Figma
- Match CTA height profile btn height
- Match stepper pills with Figma

More fixes

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/ibc-assets.ts
packages/web/config/price.ts
packages/web/public/tokens/mpwr.svg

To add MPWR token and EmpowerChain
-add EmpowerChain to source-chain-infos.ts
-add MPWR to ibc-assets.ts
-add MPWR logo
-add price for umpwr to pool 1064

Add MPWR and EmpowerChain

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/web/components/cl-deposit-input-group/index.tsx
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/modals/increase-concentrated-liquidity.tsx

Before, we'd set to max irrespective of the user's balance of both assets. Now, it will set the max value without exceeding the balance of the counterparty assets since we calculate the counterparty balance based on the price range and current price. For increase liquidity, it should work the same.
The way this works, is when an asset is set to max, it simply checks if the counterparty balance is calculated to be higher than the user's actual balance, and will set the counterparty balance as max instead. If not, it will set the counterparty balance as usual.
Add liquidity: ensure the highest amounts are set without exceeding either balance. Single side liquidity should simply set it to the max value since only one amount is being …

Set max to valid value

---

packages/web/pages/pool/[id].tsx

fix: redirect pool detail of CL FF is off

---

packages/stores/src/account/osmosis/index.ts

fix: serialize duration

---

packages/stores/src/account/osmosis/types.ts

Adjust gas

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts

Due to a chain issue, we can only let users enter prices +/- 50x current price. Should be fixed in v17.

+/- 50x price range input limit

---

packages/web/components/cards/my-position/expanded.tsx

fix: allow increase liq on SF staked pos

---

packages/web/components/cards/my-position/expanded.tsx

Due to a bug on chain side, staking existing full range positions won't be available until v17.

fix: disable stake position

---

packages/stores/src/account/osmosis/types.ts

fix: increase gas per tick

---

packages/web/components/layouts/main.tsx
packages/web/localizations/en.json

https://app.clickup.com/t/8678bz5f5
Updates the Call To Action button to go the supercharged pool, rather than the classic one

fix CTA pool id

---

packages/web/localizations/en.json

"your pools" instead of "my pools"

---

packages/stores/src/queries-external/token-pair-historical-chart/index.ts

try to hack chart

---

packages/web/modals/remove-concentrated-liquidity.tsx

fix: current price remove liq

---

packages/web/components/pool-detail/concentrated.tsx

fix price at top

---

packages/stores/src/account/osmosis/types.ts

https://sharing.clickup.com/37420681/t/h/862k4k0km/XIA5Z4WVI1RCY2Z

increase gas for superfluid migration

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts

fix: use market value for asset %s

---

packages/web/components/complex/add-conc-liquidity.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts

set final price in graphs to live spot price

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/modals/increase-concentrated-liquidity.tsx
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts

initial price before hover

---

packages/stores/src/currency-registrar/index.ts
packages/web/components/cards/my-position/status.tsx

fix near bounds calculation

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/web/components/complex/add-conc-liquidity.tsx

[ClickUp Task URL](https://app.clickup.com/t/861n2gd1x)

(CL) Improve Add Liquidity Modal Experience for Custom and Passive Strategies

---

packages/web/components/cards/my-position/status.tsx

fixed near bounds calculation

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/components/pool-detail/concentrated.tsx

start price on hover

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/localizations/en.json
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts

Also update copy in learn more instagram flow

fix: init hover price to current pool price

---

packages/web/components/navbar/index.tsx

Remove banner on mobile

---

packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/pages/index.tsx

fix: include CL pool in router

---

packages/web/components/complex/all-pools-table.tsx
packages/web/components/table/cells/pool-composition.tsx
packages/web/localizations/en.json

add supercharged icon to pool table

---

packages/web/components/swap-tool/split-route.tsx

Displays the pool type in the route vis

Display pool type in route vis

---

packages/web/config/ibc-assets.ts

To Upgrade LORE to Main, as per https://www.mintscan.io/osmosis/proposals/561
-adds isVerified: true to LORE
This change has been tested with the Vercel deployment because it's a confident one-line change.

LORE to Main

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/utils/formatter.ts

Positions: display 2 decimals, but if the amount is lesser show at least 2 decimals of the sig fig:

show at least 2 decimals, check back copy

---

packages/proto-codecs/tsconfig.json
packages/web/tsconfig.json
tsconfig.json

Update to commonjs

---

packages/web/config/generate-chain-infos/source-chain-infos.ts

Update Whale rpc/api

---

packages/web/config/generate-chain-infos/source-chain-infos.ts

Deposits and Withdrawals to/fro Migaloo weren't working because the node provider changed the name of their node--which this PR corrects
-source-chain-config
This change has been tested in the buid

Fix WHALE rpc/rest

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts

When creating a position with OSMO and clicking max, subtract amount of OSMO needed to pay max gas.

Subtract gas in add conc liq

---

packages/web/modals/validator-squad.tsx
packages/web/pages/stake/index.tsx

Just fixing two small bugs I missed in the last PR

fix two small bugs

---

packages/web/pages/stake/index.tsx

This seems to have a race condition bug. Removing until I figure out what's wrong

remove redirect until I figure out race condition

---

packages/stores/src/queries/superfluid-pools/osmo-equivalent.ts

Fix SF APR for stableswap pool (wasn't being calculated before). See pool 833.
[ClickUp Task URL](https://app.clickup.com/t/862k56e2j)

fix: SF APR for stable pools

---

packages/web/config/ibc-assets.ts

bump some assets

---

packages/web/components/cards/my-position/index.tsx

Animate bg color when hovering over position header position

fix: animated hover my position

---

packages/web/localizations/en.json

Spell check 

---

packages/web/config/price.ts

Update the pricing of the BLUE token to use pool 1073
Update the pricing of the BLUE token to use pool 1073 against LUNA in prices.ts

Update BLUE Pricing

---

packages/pools/src/concentrated/fetch-pool-amount-provider.ts
packages/pools/src/concentrated/fetch-tick-data-provider.ts
packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/components/swap-tool/index.tsx
packages/web/components/swap-tool/split-route.tsx
packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts
packages/web/hooks/ui-config/use-historical-and-depth-data.ts
packages/web/hooks/ui-config/use-trade-token-in-config.ts
packages/web/pages/pool/[id].tsx
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts
packages/web/utils/background-routes/index.ts
packages/web/utils/background-routes/worker.ts

On stage, the swap tool seemed to work fine for the most part. But I noticed an issue with the swap tool on the CL pool detail page, as well as excessive requests for balances and ticks (8+ for one quote for balances).
* Fix memory leak issue in `BackgroundRoutes`
* Key breakthrough: for existing requests, instead of returning 0s or empty lists for ticks, I maintain a map of promises for in flight requests and await on those. This prevented all sorts of annoying race conditions in the UI, and is a more reliable solution to async UI. Now, even without debounce in our trade UI config, we know (at least with this BG router), that the server will not get spammed unnecessarily.
* Dispose all UI config's reactions
Now, as user input and pools data is updated in the background, the BG router …

Fixes to swap router

---

packages/stores/src/__tests_e2e__/test-env.ts
packages/stores/src/account/__tests_e2e__/collect-rewards.spec.ts
packages/stores/src/account/__tests_e2e__/swap-exact-in-positions.spec.ts
packages/stores/src/account/__tests_e2e__/swap-exact-in.spec.ts
packages/stores/src/account/__tests_e2e__/swap-exact-out.spec.ts
packages/stores/src/account/base.ts
packages/stores/src/account/cosmos/index.ts
packages/stores/src/account/cosmwasm/index.ts
packages/stores/src/account/osmosis/index.ts
packages/stores/src/account/osmosis/types.ts
packages/stores/src/account/utils.ts
packages/stores/src/tx/ibc/ibc-transfer.ts
packages/stores/src/ui-config/fake-fee-config.ts
packages/web/hooks/ui-config/use-trade-token-in-config.ts
packages/web/pages/api/simulate-transaction.ts

[ClickUp Task URL](https://app.clickup.com/t/864dw75ug)

feat: Simulate Transaction to Estimate Gas Fee

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

Adds a price for KYVE
-adds price:ukyve to chain config
-adds pool 1075 as KYVE spot price

Update KYVE Price

---

packages/web/components/swap-tool/index.tsx

limit spot price decimals

---

packages/stores/src/queries/store.ts
packages/stores/src/queries/superfluid-pools/osmo-equivalent.ts

Assume even weight for stable pools.

Fix sf apr for stable pools

---

packages/stores/src/queries/store.ts
packages/stores/src/queries/superfluid-pools/osmo-equivalent.ts
packages/web/components/swap-tool/index.tsx
packages/web/config/ads-banner.json
packages/web/pages/500.tsx
packages/web/pages/index.tsx
packages/web/pages/stake/index.tsx

Deploy to production

---

packages/web/config/ibc-assets.ts

To address PLQ Deposit failing on the frontend
See issue https://github.com/osmosis-labs/osmosis-frontend/issues/1707
Adds a Deposit URL to TFM for PLQ to Osmosis

Update PLQ Deposit URL

---

.github/workflows/lint-and-check-format.yml
package.json
packages/math/index.ts
packages/math/src/pool/index.ts
packages/pools/index.ts
packages/proto-codecs/index.ts
packages/stores/index.ts
packages/stores/src/account/__tests_e2e__/collect-rewards.spec.ts
packages/stores/src/account/__tests_e2e__/positions.spec.ts
packages/stores/src/account/__tests_e2e__/swap-exact-out.spec.ts
packages/stores/src/account/osmosis/index.ts
packages/stores/src/derived-data/pool/bonding.ts
packages/stores/src/queries-external/filtered-pools/filtered-pools.ts
packages/stores/src/queries/pools/pool.ts
packages/stores/src/tx/ibc/types.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/stores/tsconfig.json
packages/web/config/ads-banner.json
packages/web/next.config.js
packages/web/package.json
packages/web/pages/api/active-gauges.ts
packages/web/pages/index.tsx
packages/web/tsconfig.json
turbo.json
yarn.lock

Transpile local Osmosis modules using the Next.js configuration. Makes it easy to have local libraries and keep a slick, manageable dev experience. This will solve the issue with build collisions that required devs to clear the build folder on occasion. 
This PR also adds a Lint action that will improve the repo consistency, especially while merging asset PRs. 
[Add Lint CI Action](https://app.clickup.com/t/866arqaqq)
[Transpile Next.js local Osmosis modules](https://app.clickup.com/t/866arqat3)

feat: Transpile Modules in Next Dev Server and Add Lint to CI

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/ibc-assets.ts

To add XPRT to Testnet page
-adds xprt to ibc-assets
-adds persistence to source-chain-config
-prices and logo were already there

Token Listing: Testnet XPRT

---

packages/stores/src/queries/pools/pool.ts
packages/stores/src/queries/pools/pools.ts

If we encounter an unexpected pool type, like CW pools, we simply exclude it from our query pools list.

(unblock v17) fix: ignore unsupported pool types

---

packages/web/config/ibc-assets.ts

Replacing https://github.com/osmosis-labs/osmosis-frontend/pull/2007 to set DARC, NTRN, and HASH to Verified
- set DARC, NTRN, and HASH to isVerified: true in ibc-assets.ts

Asset Integrations: Verify HASH, DARC, NTRN

---

packages/web/config/ibc-assets.ts

Enable Chihuahua deposit/withdraw

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

Updates SEI Price to use pool 1086 spot balance instead of coingecko call.
-defines pool:usei in price.ts
-replaces coingeckoid for sei to pool:usei in source-chain-config

Asset Integrations: Update SEI Price

---

packages/web/components/control/switch.tsx
packages/web/components/navbar/index.tsx
packages/web/config/user-analytics-v2.ts
packages/web/hooks/use-amplitude-analytics.ts
packages/web/hooks/use-feature-flags.ts
packages/web/integrations/notifi/notifi-popover.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/alert-setting-list.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/alert-setting-row.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/edit-view.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/signup-view.tsx
packages/web/integrations/notifi/notifi-subscription-card/notifi-subscription-card.tsx

Adds amplitude events and feature flag for notifi notifications dropdown.
Also adds some minor cleanup
[ClickUp Task URL](https://app.clickup.com/t/8678kt78j)
* Amplitude vents for the panel, from this [list](https://app.clickup.com/37420681/v/li/900100353450)
* Added "Notifications" feature flag in LD
For testing, I recommend toggling the "DEBUG" flag in use-amplitude-analytics and watching the console to ensure the events log as expected.

Notifi Amplitude events & feature flag

---

packages/web/components/navbar/index.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/signup-view.tsx
packages/web/integrations/notifi/notifi-subscription-card/notifi-subscription-card.tsx
packages/web/package.json
packages/web/pages/_app.tsx
yarn.lock

Fix infinite loop SSR build bug

---

packages/stores/src/queries-external/token-pair-historical-chart/index.ts
packages/web/components/navbar/index.tsx
packages/web/hooks/use-feature-flags.ts
packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts

v17 Hotfixes

---

packages/stores/src/queries-external/filtered-pools/filtered-pools.ts
packages/stores/src/queries/pools/pool.ts
packages/stores/src/queries/pools/pools.ts
packages/stores/src/queries/store.ts
packages/stores/src/ui-config/user-upgrades.ts
packages/web/config/feature-flag.ts
packages/web/stores/root.ts

Hotfix: hide pools in blacklist

---

packages/web/pages/index.tsx

hotfix: only allow 1066 pool

---

packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx

The assets received notification links to cosmos mintscan instead of osmosis

[Notifi] fix: notification links to cosmos mintscan instead of osmosis

---

packages/web/config/ibc-assets.ts

To make KYVE a verified asset
(see that there's no need to activate to select KYVE)
kyve isVerified: true in ibc-assets.ts

Asset Integrations: KYVE Verified

---

packages/stores/src/account/osmosis/index.ts
packages/stores/src/ui-config/user-upgrades.ts
packages/web/components/cards/my-position/expanded.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/components/pool-detail/share.tsx
packages/web/modals/user-upgrades.tsx
packages/web/pages/pools/index.tsx
packages/web/stores/root.ts

* Includes unlocking locks in migration transaction
* Closes upgrades modal on mobile (button not visible on nav bar on mobile intentionally)
* Hides superfluid funnel CTAs where the upgrades modal can be triggered if FF is off
* To prevent chain error, filters upgrades worth < 10 ¢
* CL Remove liquidity: accurately show pending rewards instead of CL position assets
Closes upgrades modal on mobile, as it should only be accessible on desktop. The upgrades button on nav bar is only available on desktop.

Close upgrades modal on shrink to mobile & fixes

---

packages/web/components/cards/app-card.tsx
packages/web/components/cards/hero-card.tsx

fix: Mobile App Layout

---

.vscode/osmosis-frontend.code-workspace
packages/stores/src/derived-data/pool/bonding.ts
packages/stores/src/derived-data/pool/share-pool-details.ts
packages/web/components/cards/app-card.tsx
packages/web/components/cards/hero-card.tsx
packages/web/components/pool-detail/share.tsx
packages/web/stores/user-settings/language.tsx

- Mobile App Layout Fix (#2092)

Stage --> Master

---

packages/stores/src/price/pool.ts
packages/stores/src/queries-external/position-performance/index.ts
packages/web/components/cards/my-position/expanded.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/pages/assets/index.tsx
packages/web/pages/pools/index.tsx
packages/web/stores/assets/index.ts

* Handle GAMM shares natively within the store, leveraging the existing poolGetter dependency
* Add helper function for reducing the price of a list of coins to the sum
* Refactor any inlined use of reduce to sum coins
* Fix position performance price bug, by preferring our own price store over given price values

Improve price store

---

packages/web/config/ibc-assets.ts

-To correct the ATOM testnet ibc channels to the current registered channels
- update ATOM (testnet) ibc channels in ibc-assets as per chain registry
Pool 151 shows ATOM properly under the new channel set

Asset Integrations: Fix ATOM testnet

---

packages/web/config/ibc-assets.ts

To make CTK a verified asset
- add isVerified: true under ctk in ibc-assets.ts
Validation

Asset Integrations: CTK verified

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

Add PASG Pricing via pool 1137 (paired with USDC)
- Add PASG Pricing via pool 1137 (paired with USDC) to price.ts and update source-chain-config to look at the price definiion

Asset Integrations: Add PASG Price

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/ibc-assets.ts
packages/web/config/price.ts

To fix USK asset and pricing
What was this before:
turned into this:
[ClickUp Task URL](https://app.clickup.com/t/86a0qe3qy)
- add ibc transfer path property to usk in ibc-assets.ts and used the colon version in price.ts
Validation sucessful

Asset Integrations: fix USK asset and pricing

---

packages/stores/src/ui-config/user-upgrades.ts

don't suggest upgrades for broken superfluid pools

---

packages/web/modals/user-upgrades.tsx

fix the thang

---

packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/hooks/window/use-token-swap-query-params.ts

[ClickUp Task URL](https://app.clickup.com/t/86a0rkhne)
- Remove unnecessary pool fetch on `use-token-swap-query-params.ts`

fix: Swap Memory Leak

---

packages/web/config/feature-flag.ts

To updated the swap assets:
from:
to:
OSMO, ATOM, USDC, USDT, WBTC, ETH
(I can't explain the ordering here)
- Change assets (by symbol) in feature flag

Asset Integrations: Update Recommended Swap Assets

---

packages/web/config/ibc-assets.ts

Making many assets verified as there have been changes.
Updated Listing requirements: https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md
Proposal for a batch of CL pools: https://www.mintscan.io/osmosis/proposals/614
- add isVerified: true to many assets in ibc-assets.ts
- BOOT, GLTO, GKEY, FRAX, polygon.USDC, avalance.USDC, BLZ, CUDOS, DOT.comp, WETH.grv, USDC.grv, USDT.grv, USTC, FRNZ, NETA, CANTO, USK, MNTA, SILK, SHD
Validation

Asset Integrations: Update Verified Assets (batch)

---

project.inlang.json

Fixes # (issue)
Currently, inlang does not work for Cal.com. This PR fixes this problem, and the VS extension and editor will again work as expected.
Test yourself on: https://inlang.com/editor/github.com/jannesblobel/osmosis-frontend

fix: update  inlang settings

---

packages/pools/src/concentrated/pool.ts
packages/pools/src/cosmwasm/transmuter.ts
packages/pools/src/interface.ts
packages/pools/src/router/__tests__/pool.ts
packages/pools/src/router/routes.ts
packages/pools/src/router/types.ts
packages/pools/src/stable.ts
packages/pools/src/weighted.ts
packages/stores/src/queries-external/pools/pools.ts
packages/stores/src/queries/pools/cfmm-cl-link.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/components/pool-detail/base-pool.tsx
packages/web/components/pool-detail/index.ts
packages/web/components/swap-tool/index.tsx
packages/web/config/feature-flag.ts
packages/web/hooks/data/use-routable-pools.ts
packages/web/pages/pool/[id].tsx
packages/web/queries/complex/pools.ts

Make sure transmuter pool is included as a routable pool.

Add transmuter pool to router

---

packages/stores/src/price/pool.ts

Fix prices on stake page

---

packages/web/pages/api/pool/[id].ts
packages/web/pages/api/pools.ts
packages/web/queries/complex/pools.ts
packages/web/queries/cosmos/bank/balances.ts
packages/web/queries/osmosis/poolmanager/num-pools.ts
packages/web/queries/osmosis/poolmanager/pools.ts

- Removes cold start by using edge functions
- Reduces computation time from ~11s to ~300ms  (189.38% improvement)
- When moving to the edge do not use absolute imports as they include the whole web package bundle

Improvement: Transmuter Performance 

---

.vscode/osmosis-frontend.code-workspace

Add new packages to VSCode workspace

---

.vscode/osmosis-frontend.code-workspace
packages/stores/src/account/base.ts
packages/stores/src/account/osmosis/index.ts
packages/stores/src/price/pool.ts
packages/web/components/cards/rewards-card.tsx
packages/web/components/cards/stake-dashboard.tsx
packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/localizations/en.json

merge stage to master

---

.vscode/osmosis-frontend.code-workspace
packages/stores/src/account/base.ts
packages/stores/src/account/osmosis/index.ts
packages/stores/src/price/pool.ts
packages/web/components/cards/rewards-card.tsx
packages/web/components/cards/stake-dashboard.tsx
packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/localizations/en.json

stage to master

---

packages/stores/src/ui-config/trade-token-in-config.ts

bump cl preferred to 100k

---

packages/stores/src/queries-external/pools/pools.ts
packages/web/pages/pool/[id].tsx

This PR fixes the infinite loop when opening trade pair in the individual pools page

fix: Trade Pair Pools Page

---

packages/stores/src/account/osmosis/index.ts
packages/web/components/cards/stake-dashboard.tsx
packages/web/components/cards/validator-squad-card.tsx
packages/web/localizations/en.json
packages/web/modals/validator-next-step.tsx
packages/web/modals/validator-squad.tsx
packages/web/pages/stake/index.tsx

- refactor to use usersValidatorSetPreference for Dashboard display
- add button disabled states to validator squad modal
- add default checkboxes to validator squad modal
- add routing for stake, stake and edit squad, edit squad
[ClickUp Task URL](https://app.clickup.com/t/86a0td4kf)
[ClickUp Task URL](https://app.clickup.com/t/86a0vbjh5)
[ClickUp Task URL](https://app.clickup.com/t/86a0vbdw1)
add routing for
- new user modal
- existing user modal
- click stake button without new / existing user modal
- edit / view all
add disabled button state for validator squad table
- if user has not selected any validators
- add default checkboxes and map table ids that match a user's valsetpref
https://github.com/osmosis-labs/osmosis-frontend/assets/30577966/b6c44ced-0496-49d3-90b1-602ae9c2c412

Mattupham/validator squad disabled states + default checkboxes for valsetpref modal + dashboard updates + routing

---

packages/web/hooks/data/use-routable-pools.ts

This function takes 200ms on main app load.
This PR introduces a trivial, tiny speedup. Unbenchmarked for impact though.
Eliminating the root cause of this computation time will come in follow-ups.

Constant fold constants for one dec conversion

---

packages/web/components/cards/main-stake-card.tsx
packages/web/components/cards/stake-info-card.tsx
packages/web/components/spinner.tsx
packages/web/pages/stake/index.tsx

Remove the feature flag check on the index of staking
Removes the useFlags hook on the staking index page 

remove LD feature flag check

---

packages/web/components/cards/stake-dashboard.tsx
packages/web/components/cards/stake-tool.tsx
packages/web/components/stake/unbonding-in-progress.tsx
packages/web/pages/stake/index.tsx
packages/web/public/icons/sprite.svg

* Fix info icon
* Text color
* Catch message events, preventing request rejected from bubbling to app

Minor: match staking to figma

---

packages/stores/src/queries-external/concentrated-liquidity/range-aprs.ts

If the APR query fails, it may return an unexpected response. I wrapped the entire APR reference in a try catch to handle all unexpected responses.

Add try catch to response

---

packages/web/components/complex/add-conc-liquidity.tsx

Only display APR if available

---

packages/web/pages/index.tsx

Removes supercharged wos BG and restores it back to normal BG. Requested by @syed8rahman 

Change BG back to wos

---

packages/stores/src/ui-config/price.ts
packages/web/components/cards/my-position/index.tsx

It was not possible to input decimals with many trailing 0s.

Fix CL price range input of decimals

---

packages/pools/src/cosmwasm/transmuter.ts
packages/web/hooks/data/use-routable-pools.ts

The transmuter implementation now properly handles logic around swap limits.

Fix transmuter limit

---

packages/web/components/complex/add-conc-liquidity.tsx

When dragging the slider, it may cause the user to highlight the APR. This adds select none to prevent that.

Add Conc Liq: select none

---

packages/web/components/navbar-osmo-price.tsx
packages/web/hooks/use-feature-flags.ts

[ClickUp Task URL](https://app.clickup.com/t/86a12t3a4)
- Hide OSMO price and change behind feature flag

feat: Place Sidebar OSMO Chart and Change Behind FF

---

packages/web/components/cards/my-position/status.tsx

Address low impact and rare div 0 error.
https://osmosis-wu.sentry.io/issues/4527286068/?alert_rule_id=14454698&alert_type=issue&notification_uuid=954fc4f4-ceee-48c0-950b-b9d705aa5235&project=4505285757698048&referrer=slack

avoid div 0

---

packages/stores/src/account/osmosis/index.ts

In rare scenarios, the user's selected value for upper or lower tick can be 0. This causes the member to be omitted by our serialization code from telescope. For pool 1220, the current tick happens to be ~900, and users wanting to select a super tight range (for stablecoin prices) may have a tick get rounded to 0. If this happens, we set the tick to the pool's - tick spacing for min tick and + tick spacing for max tick. The range isn't _exactly_ what the user selected but it's tight enough.
[ClickUp Task URL](https://app.clickup.com/t/86a0q1w8n)

CL add liq: handle 0 tick in

---

packages/pools/src/router/routes.ts

fix: proper fix for no routes for this trade bug (#2246)

---

packages/pools/src/concentrated/fetch-tick-data-provider.ts

ramp to max tick not min tick

---

packages/pools/src/concentrated/fetch-tick-data-provider.ts

ramp to max tick not min tick (#2248)

---

packages/pools/src/__tests__/concentrated.spec.ts
packages/pools/src/concentrated/fetch-tick-data-provider.ts
packages/pools/src/concentrated/pool.ts
packages/stores/src/queries/concentrated-liquidity/liquidity-net-in-direction.ts
packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
packages/stores/src/queries/concentrated-liquidity/types.ts

Router fix: Add current sqrt price from tick data provider

---

packages/pools/src/concentrated/pool.ts
packages/pools/src/cosmwasm/transmuter.ts
packages/pools/src/cosmwasm/types.ts
packages/pools/src/stable.ts
packages/pools/src/types.ts
packages/pools/src/weighted.ts
packages/web/queries/complex/pools.ts
packages/web/queries/osmosis/poolmanager/index.ts
packages/web/queries/osmosis/poolmanager/params.ts

Adds the taker fee to each pool implementation model. It is then used to subtract a % of the token in before simulating quotes. Notice difference in output (some may be attributed to price differences, but it's still noticable).

Add taker fee to quote logic

---

packages/web/config/feature-flag.ts
packages/web/localizations/en.json

Remove celestia banner

---

packages/stores/src/derived-data/pool/bonding.ts
packages/stores/src/derived-data/pool/concentrated.ts
packages/stores/src/derived-data/store.ts
packages/stores/src/queries-external/concentrated-liquidity/index.ts
packages/stores/src/queries-external/concentrated-liquidity/pool-avg-apr.ts
packages/stores/src/queries-external/store.ts
packages/web/stores/derived-data/pools/metrics.ts
packages/web/stores/derived-data/store.ts

Uses new data service to display average APR for all positions in pools table, instead of the full range APR. This should accurately reflect the higher returns possible in that pool.
https://api-osmosis-chain.imperator.co/cl/v1/apr/avg/1108
[ClickUp Task URL](https://app.clickup.com/t/86a14xc7m)

CL Pools table: add avg CL pool APR to pools table

---

packages/web/config/ibc-assets.ts

verify FIS and rATOM

---

packages/web/integrations/ethereum/queries/erc20.ts
packages/web/pages/api/bridge-transfer/quotes/index.ts
packages/web/stores/queries-external/bridge-transfer/bridge-quotes.ts
packages/web/utils/__tests__/async.ts
packages/web/utils/async.ts

Fixes:
- Withdraw quotes
- Weird ERC20 symbols

[Bridge Provider] Fix Remove Special Symbols from ERC20  

---

packages/web/hooks/data/use-routable-pools.ts

Fix pools loading on testnet

---

packages/pools/src/cosmwasm/transmuter.ts

Don't subtract taker fee in transmuter

---

packages/pools/src/router/__tests__/routes.spec.ts
packages/pools/src/router/routes.ts
packages/web/hooks/ui-config/use-trade-token-in-config.ts

Removes the disposer function so the spot quote and user input will continue to request quotes. However, since the disposer is not being used it may cause a memory leak if the app is used for a very long time.

Fix swap tool init & router pool filter

---

packages/web/config/generate-chain-infos/utils.ts

Add some documentation / move logic for the `getChainInfos` logic. Happy to not merge this, just did this as a driveby as I was understanding this code. This provides no functionality change.

Add some comments for generate-chain-infos code conversion

---

packages/web/config/ibc-assets.ts

- as per LISTING requirements, STRDST, having been launched via StreamSwap, qualifies for Verified status
- 
[Assetlists PR](https://github.com/osmosis-labs/assetlists/pull/727/)
- add isVerified true to STRDST in ibc-assets.ts
Validation

Asset Integrations: Make $STRDST Verified

---

packages/web/config/ibc-assets.ts
packages/web/integrations/nomic/transfer.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/package.json
yarn.lock

This pull request fixes minor issues in the initial integration of the Nomic Bitcoin Bridge.
- Fix a display issue with miner fees
- Update the relayer endpoint
- Display minimum deposits
These changes have been locally tested 
N/A

Nomic integration tweaks

---

packages/web/components/complex/transfer.tsx
packages/web/integrations/bridge-info.ts
packages/web/integrations/bridges/axelar/axelar-bridge-provider.ts
packages/web/integrations/bridges/types.ts
packages/web/modals/bridge-transfer-v2.tsx

[Multi Bridge] Calculate Gas Fees for Axelar Transactions

---

packages/web/components/complex/transfer.tsx
packages/web/integrations/bridge-info.ts
packages/web/integrations/bridges/axelar/axelar-bridge-provider.ts
packages/web/integrations/bridges/types.ts
packages/web/modals/bridge-transfer-v2.tsx
packages/web/pages/assets/index.tsx

Open the deposit or withdraw modal on the assets page by using specific query parameters in the URL. To do this, add `transaction_type=deposit|withdraw` and `denom` to the URL. For example: `/assets?transaction_type=deposit&denom=ETH`.
[ClickUp Task URL](https://app.clickup.com/t/86a18njbn)

feat: Open Deposit/Withdraw Modal from Query Params

---

packages/web/hooks/data/use-routable-pools.ts

10k for all pools

---

packages/stores/src/queries-external/store.ts
packages/stores/src/queries-external/token-data/index.ts
packages/web/components/chart/sparkline.tsx
packages/web/components/navbar-osmo-price.tsx
packages/web/components/table/assets-table-v2.tsx
packages/web/components/table/cells/change-cell.tsx
packages/web/components/table/cells/index.ts
packages/web/components/table/cells/market-cap-cell.tsx
packages/web/components/table/cells/price-cell.tsx
packages/web/components/table/cells/types.ts
packages/web/utils/chart.ts

Add the Price And Change column to the new assets table. 
[Add price column](https://app.clickup.com/t/86a0vf3j5)
[Add change column](https://app.clickup.com/t/86a0vf3jx)

feat: add price and chart initial column

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/ibc-assets.ts

This PR populates config information for Nomic stakenet
- Populate Nomic ibc info
- Populate Nomic rpc and rest URLs

Update Nomic mainnet config

---

packages/web/integrations/nomic/transfer.tsx

This PR adds relayer path for Nomic integration

Add mainnet relayer path

---

packages/web/config/generate-chain-infos/source-chain-infos.ts
packages/web/config/price.ts

To correct the pricing for TIA (had wrong destination coin id)
- Correct coin id to usd-coin

fix: $TIA pricing

---

packages/web/pages/pool/[id].tsx

CL: show default pool page for CL on mobile

---

packages/stores/src/account/osmosis/index.ts

CL create position: increase slippage to 10%

---

packages/stores/src/account/osmosis/index.ts

* increase
* 10
* 15% for 1247 pool ID
* 15% increase liq

CL create position: increase slippage to 10% (#2344)

---

packages/stores/src/account/osmosis/index.ts

Modifies maxSlippage to 15 for osmo<>tia CL pool

fix: osmo<>tia slippage to 15%

---

packages/stores/src/account/osmosis/index.ts

Cherry-picks https://github.com/osmosis-labs/osmosis-frontend/pull/2349 from `stage`

fix: osmo<>tia slippage to 15% (#2349)

---

packages/web/components/complex/add-conc-liquidity.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/components/pool-detail/share.tsx

flip volume and liquidity display in pool details pages

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/components/pool-detail/share.tsx
packages/web/hooks/use-feature-flags.ts
packages/web/pages/pools/index.tsx

support CL on mobile

---

packages/web/pages/_app.tsx

Change Levana URL to add utm tags

Change levana URL to add UTM tags

---

packages/web/components/navbar-osmo-price.tsx

use gray over red for number go down

---

packages/web/components/cards/my-position/expanded.tsx
packages/web/components/pool-detail/base-pool.tsx

CL mobile fixes

---

packages/web/config/feature-flag.ts

persist TIA banner state

---

packages/web/components/main-menu.tsx
packages/web/components/navbar/index.tsx

Something must have gone wrong in the merge that messed with the pro-trading button? SHould be fixed now

DRAFT: Sidebar fixes

---

packages/web/hooks/data/use-routable-pools.ts
packages/web/hooks/use-feature-flags.ts
packages/web/pages/_app.tsx

we want to gracefully fail if LD client id isn't present
[ClickUp Task URL](https://app.clickup.com/t/86a1ab86r)
- Do not fail if LD client id not present

Ld graceful fail

---

packages/web/hooks/data/use-routable-pools.ts

Lower routable pools 1k

---

packages/web/pages/_app.tsx

updating the link for feature request

update feature requests link

---

packages/web/components/main-menu.tsx

small style adjustments

---

packages/web/config/ibc-assets.ts

To make $COREUM verified status
[Assetlists PR](https://github.com/osmosis-labs/assetlists/pull/755)
- add isVerified: true to coreum in ibc-assets.ts

Asset Integrations: $COREUM to Verified status

---

packages/web/config/generate-chain-infos/source-chain-infos.ts

To add an explorer URL for NOMIC chain
- add an explorer URL for NOMIC chain in source-chain-config
Not validated

fix: Nomic Explorer URL

---

packages/web/config/generate-chain-infos/source-chain-infos.ts

To update SGE chain's RPC and REST nodes, as per
this [Assetlists PR](https://github.com/osmosis-labs/assetlists/pull/754)
-Update rpc and rest nodes under SGE in source-chain-infos.ts

Asset Integrations: Update SGE's RPC and REST

---

packages/pools/src/router/__tests__/pool.ts
packages/pools/src/router/__tests__/routes.spec.ts
packages/pools/src/router/routes.ts
packages/stores/src/account/__tests_e2e__/swap-exact-in.spec.ts
packages/stores/src/ui-config/trade-token-in-config.ts
packages/web/hooks/ui-config/use-trade-token-in-config.ts
packages/web/pages/api/router/token-out-given-in.ts
packages/web/utils/background-routes/coding/params.ts

@p0mvn requests we add our router to an edge function so that he can compare our routes against his during automated testing.
Example route:
`/api/router/token-out-given-in?tokenInDenom=uion&tokenInAmount=100&tokenOutDenom=uosmo`
IBC denoms will need to be URL encoded

Edge function router

---

packages/web/config/price.ts

To update the pricing for SUI and BONK to look at larger pools
- Update price.ts for SUI from 1127 to 1128
-and bonk from 1129 to 1130

Asset Integrations: Update SUI and BONK Price

---

packages/web/integrations/notifi/hooks/use-history-detail-contents.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/alert-setting-row.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-detail-view.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-view.tsx
packages/web/integrations/notifi/notifi-subscription-card/fetched-card/signup-view.tsx
packages/web/package.json
yarn.lock

Add hyperlink support for broadcast message in `history-rows` and `history-detail` view.
checkout the demo video herewith
https://github.com/osmosis-labs/osmosis-frontend/assets/127958634/96667d4d-f242-48c9-965b-345b0720f2a3
Overriding the style is possible by modifying the `markdownHtmlAttrs` in `overrideMarkdownHtmlStyle` helper function ( `use-history-detail-contents.tsx`)

[Notifi V5] Support hyperlink in history view/ refactor history view

---

packages/stores/src/account/osmosis/index.ts

Increase slippage

---

packages/web/config/generate-chain-infos/source-chain-infos.ts

Update name of Crypto.org chain to Cronos POS Chain

---

packages/web/components/navbar/index.tsx

move pro trade button

---

packages/web/config/price.ts

Changing to USDC pairing: https://app.osmosis.zone/pool/1262
From abandoned OSMO Pool: https://app.osmosis.zone/pool/1216
N/A
Changed Pool reference and denom spot
This change has not been tested locally, minor change to config
No

Change USDC.wh Price reference pool

---

.github/mergify.yml

chore: mergify stage as base

---

packages/web/server/queries/osmosis/poolmanager/num-pools.ts
packages/web/server/queries/osmosis/poolmanager/pools.ts

Fix URL for query pools and num pools.

fix: URL for Query Pools and Num Pools

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts

Default the Add CL position to be moderate instead of custom

---

packages/web/server/queries/complex/pools.ts

I broke the pools query when trying to fix it earlier

Fix pools query

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/web/server/queries/complex/pools.ts
packages/web/server/queries/osmosis/poolmanager/num-pools.ts
packages/web/server/queries/osmosis/poolmanager/pools.ts

Publish Stage (small fixes)

---

packages/web/components/cards/bond-card.tsx
packages/web/components/complex/all-pools-table.tsx

increase amount needed for high apr warning

---

packages/web/components/table/cells/transfer-button.tsx
packages/web/components/table/index.tsx

fix: Deposit and Withdraw Url Anchor

---

packages/web/config/price.ts

Asset Integrations: Add QWOYN pricing

---

packages/web/config/asset-list/__tests__/asset-lists.ts
packages/web/config/asset-list/mock-asset-lists.ts
packages/web/config/ibc-overrides.ts

Asset list changed Filecoin's symbol. This broke our build because it failed to pass the verification for IBC overrides available assets.

fix: Stage Build

---

packages/web/package.json
packages/web/pages/_app.tsx
yarn.lock

Adds superflow QA tool.  Should only impact stage.osmosis.zone
Just followed instructions here

add superflow

---

packages/web/components/swap-tool/split-route.tsx

Fix inequality overflowing route vis

---

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
packages/stores/src/ui-config/price.ts
packages/web/components/complex/add-conc-liquidity.tsx
packages/web/stores/derived-data/pools/metrics.ts

Fix exclusion of token decimals when calculating APRs and strategies

---

packages/web/config/price.ts

- To add pricing for $BRNCH from Stargaze
[Assetlist Task URL](https://github.com/osmosis-labs/assetlists/pull/722)
- adds price definition for $BRNCH in price.ts using pool 1288
- 

Asset Integrations: Add BRNCH pricing

---

packages/web/components/table/assets-table-v1.tsx
packages/web/components/table/assets-table-v2.tsx
packages/web/components/table/cells/asset-name.tsx
packages/web/components/table/cells/types.ts

Changed chain name with asset name inside assets table.
Resolve issue #2429 

feat: :sparkles: change chain name with asset name

---

package.json
packages/web/package.json
yarn.lock

Upgrade sentry & turbo

---

package.json
packages/web/package.json
yarn.lock

* upgrade sentry
* update turbo

Upgrade sentry & turbo (#2467)

---

packages/web/config/feature-flag.ts

Show chain halted

---

packages/web/config/feature-flag.ts

This reverts commit 54f89a6aa518db57432c0f16b98487f7e3ba7dbb.

Revert "show chain halted"

---

packages/web/components/drawers/token-select-drawer.tsx
packages/web/components/input/search-box.tsx
packages/web/components/swap-tool/index.tsx
packages/web/hooks/input/use-amount-input.ts
packages/web/hooks/use-swap.ts
packages/web/server/api/edge-routers/swap-router.ts
packages/web/server/queries/complex/assets/__tests__/assets.spec.ts
packages/web/server/queries/complex/assets/index.ts
packages/web/utils/routing/best-route-router.ts

* Loading animation for from/to assets
* Fix inputting 0 into swap tool token in amount

Polish swap tool UI

---

packages/proto-codecs/package.json
packages/proto-codecs/tsconfig.json
packages/web/components/complex/all-pools-table.tsx
packages/web/package.json
packages/web/tsconfig.json
yarn.lock

Use [tsx](https://github.com/privatenumber/tsx) as a replacement for ts-node, which is incompatible with newer versions of Node.js. Tsx is a modern alternative developed using esbuild, offering performance comparable to the Rust compiler. Additionally, tsx eliminates the need for creating any configuration files.

feat: Run Scripts With tsx

---

packages/web/components/navbar/index.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/modals/external-links-modal.tsx
packages/web/pages/_app.tsx

add checkbox that allows users to opt out of seeing the external links modal. Also update some styles
[ClickUp Task URL](https://app.clickup.com/t/86a1n7utw)
add checkbox that allows users to opt out of seeing the external links modal

Update external Links Modal

---

packages/pools/src/cosmwasm/astroport-pcl.ts
packages/pools/src/cosmwasm/index.ts
packages/pools/src/types.ts
packages/pools/src/utils.ts
packages/web/config/feature-flag.ts
packages/web/server/queries/complex/route-token-out-given-in.ts

Add Astroport PCL pool interface and quote logic so those can be considered on the router

feat: astroport pcl

---

packages/web/integrations/sidecar/router.ts

* Include swap fee amount in sidecar and swap tool
[ClickUp Task URL](https://app.clickup.com/t/86a1ng2hr)
* Includes calculation of in amount used for swap fees for sidecar quotes
* Should see swap fee % and USD value in swap tool

[SQS] Include swap fee amount in sidecar

---

packages/web/components/your-balance/your-balance.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/pages/assets/[denom].tsx
packages/web/server/queries/external/github.ts

feat: CMS Staking URL

---

packages/web/integrations/sidecar/router.ts
packages/web/integrations/sidecar/types.ts

Adds price impact to SQS.
To be merged after this PR is complete SQS side: https://github.com/osmosis-labs/osmosis/pull/7107

feat: add price impact to sqs

---

packages/web/components/layouts/main.tsx
packages/web/components/main-menu.tsx
packages/web/utils/function.ts

Before
After
[ClickUp Task URL](https://app.clickup.com/t/86a1mpbq9)

fix: Side Nav Overflow

---

packages/web/components/earn/table/columns.tsx

Improve involved tokens image positioning on the table column

feat(web): add margin to table cell based on value length

---

packages/web/components/complex/all-pools-table.tsx
packages/web/components/table/cells/cl-apr-breakdown.tsx
packages/web/hooks/use-feature-flags.ts
packages/web/stores/derived-data/pools/metrics.ts

https://app.launchdarkly.com/default/development/features/apr-breakdown/targeting

Move APR breakdown behind FF

---

packages/web/components/ad-banner/ad-banner.tsx
packages/web/config/ads-banner.json

-- add Levana and milkTIA ad banners
[ClickUp Task URL](https://app.clickup.com/t/86a1q1ykt)
[ClickUp Task URL](https://app.clickup.com/t/86a1q1yp1)
- add images to FE content repo
- update links to pools
- add references to images
- remove randomness and show levana first
test on preview deploy

Add levana and milkTIA ad banners

---

packages/stores/src/account/__tests__/account-base.spec.ts
packages/stores/src/account/base.ts

improvement: Update Gas Multiplier to 3

---

packages/stores/src/account/__tests__/account-base.spec.ts
packages/stores/src/account/base.ts

gas mult > 3.5

---

packages/web/config/ads-banner.json

remove levana

---

packages/web/config/ads-banner.json

remove levana (#2589)

---

packages/web/config/feature-flag.ts
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

To remove the announcement (yellow) banner. Currently about LVN and milkTIA.
- Removes toggle from feature-flag.ts
- Removes text from all 12 localization files.

Remove Announcement Banner

---

packages/web/config/feature-flag.ts
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

yarn fixes (#2591)

---

packages/web/integrations/tfm/router.ts
packages/web/server/api/edge-routers/swap-router.ts

Include decimals in price impact calculation.

Include decimals in price impact

---

packages/web/modals/settings.tsx

Fix a warning relative to key prop error on settings.tsx
- This adds a key prop to a Fragment that wraps each setting
This is not a change that introduces a new feature, but solves a React warning relative to a bad practice

fix(settings): fix key prop error

---

packages/web/components/token-details/token-details.tsx

fix: remove log

---

packages/web/modals/wallet-select.tsx

improvement: Connect Wallet Layout Responsiveness

---

packages/web/components/complex/all-pools-table.tsx
packages/web/components/earn/table/columns.tsx
packages/web/hooks/use-strategy-table-config.ts
packages/web/modals/validator-squad-modal.tsx

Typescript definition from tanstack tables seems a bit tricky when you wanna handle global filters definition from the table declaration , there is a [PR](https://github.com/TanStack/table/pull/5215) that I open for that, meanwhile I moved the definitions to the columns to avoid having problems on all tanstack tables and being forced to define filters every time.

Fix: tanstack table types

---

packages/web/components/complex/bridge-from-to-network.tsx
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/modals/bridge-transfer-v2.tsx
packages/web/modals/pre-transfer.tsx
packages/web/modals/wallet-select.tsx

fix: Mobile Transfer Responsive Layout

---

packages/web/components/complex/pool/create/step1-set-ratios.tsx
packages/web/components/complex/pool/create/step3-confirm.tsx

move swap fee to first page of create pool modal

---

packages/pools/src/router/routes.ts
packages/pools/src/weighted.ts
packages/web/components/swap-tool/index.tsx
packages/web/hooks/use-swap.ts
packages/web/pages/pool/[id].tsx
packages/web/server/queries/complex/pools/index.ts
packages/web/server/queries/complex/route-token-out-given-in.ts

* Set min liq of direct pool to 0 for legacy router
* Change legacy router error for not enough in
Refactor
* Move pools query to /pools/index.ts

Improve direct swap

---

packages/stores/src/account/base.ts
packages/stores/src/account/types.ts
packages/web/components/navbar/index.tsx
packages/web/config/ibc-overrides.ts
packages/web/hooks/input/use-amount-input.ts
packages/web/hooks/queries/cosmos/use-balances.ts
packages/web/hooks/queries/osmosis/use-icns-name.ts
packages/web/hooks/use-swap.ts
packages/web/modals/profile.tsx
packages/web/server/queries/osmosis/icns/index.ts
packages/web/server/queries/osmosis/icns/query-icns-name.ts
packages/web/server/queries/osmosis/index.ts
packages/web/stores/index.tsx
packages/web/stores/nav-bar.ts
packages/web/stores/root.ts

[ClickUp Task URL](https://app.clickup.com/t/86a1uagwj)

feat: Refactor Profile to TRPC

---

packages/types/src/asset-types.ts
packages/web/config/ibc-overrides.ts

Fix build to be compatible with current asset list.

Fix build with new asset list

---

packages/pools/src/router/routes.ts
packages/web/integrations/sidecar/router.ts

Since BOOT is very cheap compared to OSMO, swapping anything below 10**3 will not produce non-zero result.
Out current error message is misleading where it says "No Route For This Trade". This PR fixes it by making sure that the proper error message is displayed.
Before:
After:
After with 10**3 BOOT in:
For the issue to be properly fixed, this PR in SQS needs to be deployed first:
https://github.com/osmosis-labs/sqs/pull/12
However, it does not block the merge of this PR.

fix: not enough quoted error instead of "No Routes"

---

packages/pools/src/router/route.ts
packages/pools/src/router/routes.ts
packages/pools/src/router/types.ts
packages/web/components/swap-tool/split-route.tsx
packages/web/integrations/sidecar/router.ts
packages/web/server/api/edge-routers/swap-router.ts

fix: spread factor for individual pools in routes

---

packages/web/stores/derived-data/pools/metrics.ts

Hotfix: fix apr sorting

---

packages/web/pages/stake.tsx

height fix for vertical centering

---

packages/web/integrations/sidecar/router.ts

Changing the endpoint to:
GET `/router/custom-direct-quote?tokenIn=<tokenIn>&tokenOutDenom=<tokenOutDenom>&poolID=<num>`
Description: returns the quote over route with the given poolIDs. If such route does not exist, returns error.
This endpoint does not use the router route search. As a result, it is not affected by the minimum liquidity parameter. As long as the pool exists on-chain, it will return a quote.
Parameters:
tokenIn the string representation of the sdk.Coin for the token in
tokenOutDenom the string representing the denom of the token out
poolID comma-separated list of pool IDs
SQS PR is merged: https://github.com/osmosis-labs/sqs/pull/37
Already deployed in stage
```
curl "https://sqs.stage.osmosis.zone/router/custom-direct-quote?tokenIn=1000000uosmo&tokenOutDenom=uion&poolID= …
```

refactor(SQS): switch /custom-quote to /custom-direct-quote

---

packages/web/components/navbar/index.tsx
packages/web/hooks/use-feature-flags.ts

feat: Hide TFM Trading Button Behind Feature Flag

---

packages/web/components/your-balance/your-balance.tsx

Currently on this page we use old API to calculate APR, the goal of PR is to migrate to numia API and align with the staking page

Feat: add new APR api

---

packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/pages/assets/[denom].tsx

This pull request adds a responsive navigation button into the asset page named `[denom].tsx`

Add responsive back button into asset page

---

packages/stores/src/account/base.ts
packages/web/stores/root.ts

Chain Suggestions compiled by our frontend are faulty and not showing balances within the wallet. (For example Passage config is broken on production, balance doesn't load inside Keplr).
This PR fixes the list of assets we pass to the `WalletManager` class to make sure we provide it with the native data of the chain it belongs to and not the IBC data.
[ClickUp Task URL](https://app.clickup.com/t/86a1xqh15)

Fix: chain suggestions

---

packages/web/.env
packages/web/components/cards/apr-breakdown.tsx
packages/web/components/complex/all-pools-table-v1.tsx
packages/web/components/complex/all-pools-table-v2.tsx
packages/web/components/control/checkbox-select.tsx
packages/web/components/control/index.ts
packages/web/components/pool-detail/concentrated.tsx
packages/web/components/table/asset-info.tsx
packages/web/components/table/cells/apr-breakdown.tsx
packages/web/components/table/headers/sort.tsx
packages/web/hooks/window/__tests__/use-query-param-state.spec.ts
packages/web/hooks/window/use-query-param-state.ts
packages/web/pages/pools.tsx
packages/web/server/api/edge-routers/edge-router.ts
packages/web/server/api/edge-routers/pools-router.ts
packages/web/server/queries/complex/pools/env.ts
packages/web/server/queries/complex/pools/incentives.ts
packages/web/server/queries/complex/pools/index.ts
packages/web/server/queries/complex/pools/market.ts
packages/web/server/queries/complex/pools/providers/__tests__/sidecar.spec.ts
packages/web/server/queries/complex/pools/providers/sidecar.ts
packages/web/server/queries/imperator/index.ts
packages/web/server/queries/imperator/pools-fees.ts
packages/web/server/queries/sidecar/pools.ts
packages/web/utils/__tests__/sort.spec.ts
packages/web/utils/search.ts
packages/web/utils/sort.ts

NOTE: [feature flag](https://app.launchdarkly.com/default/test/features/new-pools-table/targeting) for pools table will need to be on in stage env for it to be visible.
New pools table driven with tRPC. 
* Pools >= $1k TVL are shown
* Only pools with assets in asset list are shown
* Pool TVL is now calculated from SQS TVL value (vs imperator)
* Volume and fees come from imperator
* APRs come from numia
* APR filters now operate on numia's breakdown values
[ClickUp Task URL](https://app.clickup.com/t/86a1uagzk)
* Adds market & incentive pool tRPC procedure for use with useInfiniteQuery
* Pool functions as old table does

New pools table UI

---

packages/web/pages/pool/[id].tsx

This pull request fixes the issue #2661
- This makes the computation of the `poolId` parameter server-side in order to match the SEO timing which shows the page title in the browser

Fix issue with pool page title

---

packages/web/pages/pool/[id].tsx

Fix out of memory error related to static generation

Fix: disable pool page static generation

---

packages/web/config/ibc-overrides.ts

To add Deposit/Withdraw URL overrides for NINJA token in ibc-overrides.ts
- add Deposit/Withdraw URL overrides for NINJA token in ibc-overrides.ts

Add NINJA Deposit Url Overrides

---

packages/web/server/queries/complex/pools/providers/sidecar.ts

Prevent TVL calculation from crashing table

---

packages/pools/src/types.ts
packages/web/.env
packages/web/server/queries/complex/pools/incentives.ts
packages/web/server/queries/complex/pools/index.ts
packages/web/server/queries/complex/pools/providers/__tests__/imperator.spec.ts
packages/web/server/queries/complex/pools/providers/imperator.ts

* We had an SQS pools provider, but I implemented the pools provider interface for imperator sourced pools as both a backup and a temporary performance improvement.
* Set imperator as default provider
[ClickUp Task URL](https://app.clickup.com/t/86a1uagzk)
* Implement pools provider for imperator
* New pools table (enabled in previews) should work on pools page, and ideally should have improved performance.

Implement imperator pools provider

---

packages/stores/src/ui-config/slippage-config.ts

set default slippage to 0.5%

---

packages/web/pages/pool/[id].tsx

This makes the computation of the `poolId` parameter present in the `[id].tsx` page server side in order to fix the issue of the id not displaying correctly in link previews

Use SSR computation for poolId parameter

---

packages/web/server/api/edge-routers/pools-router.ts
packages/web/server/queries/complex/pools/incentives.ts
packages/web/server/queries/complex/pools/index.ts
packages/web/server/queries/complex/pools/market.ts

See if sidecar can return pools missing from imperator pools query

Use sidecar pool provider

---

packages/web/config/ibc-overrides.ts

Add DYM Deposit Override to TFM
Add DYM Deposit Override to TFM in ibc-overrides.ts

Add DYM Deposit Override

---

packages/web/pages/assets/[denom].tsx

This pull request addresses a problem where injecting an unrecognized value into the token info page would cause visual issues.

Redirect to assets page for unknown denom injection

---

packages/web/config/ibc-overrides.ts

- Update ibc-overrides.ts to add Withdraw and Deposit URLs to TFM
- Update ibc-overrides.ts to add Withdraw and Deposit URLs to TFM
This change has been tested locally by rebuilding the website and verified content and links are expected.
injective.GLTO transfers correctly link out to TFM with correct preselected values.

Add $injective.GLTO Deposit/Withdraw URL Overrides

---

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts

Reverts osmosis-labs/osmosis-frontend#2790

Revert "Fix: pool ratio percentage calc"

---

packages/web/localizations/hi.json
packages/web/localizations/pt-br.json

Few important terms like APR, TVL, Max are correctly translated.

Hindi, Portuguese Translation corrections

---

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts

This PR is a continuation of PR #2790 

Fix: pool ratio percentage calc

---

packages/web/pages/index.tsx

feat: Filter Based on Start and End Date for Swap Ads

---

packages/web/config/ibc-overrides.ts

Update ibc-overrides.ts for solana.USDC.wh to go to portal bridge
Update ibc-overrides.ts for solana.USDC.wh to go to portal bridge

Update solana.USDC.wh ibc-overrides

---

packages/web/server/queries/complex/pools/index.ts
packages/web/server/queries/complex/pools/providers/sidecar.ts

Fixes pools on testnet by removing broken filtering.

fix: pools on testnet

---

packages/web/config/ibc-overrides.ts

Replaces Deposit and Withdraw URLs in ibc-overrides.ts
Goes to pro.osmosis.zone which is TFM, but not geoblocking the US.
Replaces Deposit and Withdraw urls to ibc-overrides.ts
injective.GLTO
NINJA
DYM
ASTRO
MPWR
BLUE
CUB
ROAR
SEI
PLQ
Validated with help of QA

Replace TFM Deposit/Withdraw ibc-overrides

---

packages/web/components/navbar-osmo-price.tsx
packages/web/components/overview/pools.tsx

* Don't trim 0's after decimal price
* Add skeleton loading to pools header price

Fix OSMO price

---

packages/web/pages/_app.tsx

Just adding the 'new' flag for the earn page

add 'new' flag for earn

---

packages/web/components/cards/my-position/index.tsx
packages/web/hooks/use-feature-flags.ts

* Add Feature Flag ([Link](https://app.launchdarkly.com/default/production/features/position-roi/targeting)) to control visibility of user position's ROI

Add ROI feature flag

---

packages/web/config/user-analytics-v2.ts
packages/web/utils/trpc.ts

* Logs query error events to amplitude
* Sets retries to 3

Log failed queries to amplitude, set retry attempts

---

packages/web/hooks/queries/osmosis/use-icns-name.ts
packages/web/server/queries/osmosis/icns/query-icns-name.ts

Fix ICNS query response

---

packages/web/server/queries/complex/concentrated-liquidity/index.ts

Fixes case of missing SF APR data.

Fix missing superfluid APR

---

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts

Check for null, since 0 values would also return false.

Fix initialization of CL add liq strategy

---

packages/web/server/queries/complex/concentrated-liquidity/index.ts

Handle assets not in asset list to be in position rewards

Allow assets not in asset list in perf rewards

---

packages/web/server/queries/complex/assets/price.ts

If an asset is not in the asset list and doesn't have pool price ID or CoinGecko ID info, let's return an error instead of spamming CoinGecko to search for the CoinGecko ID. Searching CoinGecko through prices.osmosis.zone was causing excessive traffic.
This also slightly simplifies the logic and improves naming of the `getAssetPrice` function.

Remove CoinGecko search from getAssetPrice

---

packages/web/server/queries/complex/assets/price.ts

I was informed the search is critical for bridge providers, and calculating and displaying quotes when depositing and withdrawing. This adds it back, but with a greatly increased cache time since we're only using it to get the API identifier.

Add back coingecko search

---

packages/web/package.json
packages/web/pages/_app.tsx
yarn.lock

Removes superflow. Can easily add it back later.

Remove superflow

---

packages/web/server/api/edge-routers/pools-router.ts
packages/web/server/queries/osmosis/lockup/account-unlocking-coins.ts
packages/web/server/queries/osmosis/lockup/index.ts

Include account unlocking GAMM shares in getUserPools query.

Include unlocking coins in getUserPools

---

packages/stores/src/queries/concentrated-liquidity/position-by-id.ts

"Collect rewards" action does not currently work on mobile and on desktop if you do it from the pools page, PR solves this problem
[ClickUp Task URL](https://app.clickup.com/t/86a2ehtc0)

Fix: Collect Rewards

---

packages/web/config/ibc-overrides.ts

Add ibc Override for $BERLIN because it's an EVMOS asset.
Add ibc Override for $BERLIN
Deposit redirects to Evmos IBC transfer interface

Add ibc Override for $BERLIN

---

packages/web/localizations/de.json
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/gu.json
packages/web/localizations/hi.json
packages/web/localizations/ja.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/ru.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json

Accidentally removed a translation when removing old pools table.

Fix missing translation

---

packages/web/config/ibc-overrides.ts

To add transfer overrides for BMOS token, using Osmosis Pro
- add transfer overrides for BMOS token, using Osmosis Pro. to ibc-overrides.ts
Finally it works

Add BMOS IBC transfer overrides

---

packages/web/components/pool-detail/base-pool.tsx

Hotfix pool weight

---

packages/web/server/queries/complex/concentrated-liquidity/index.ts
packages/web/server/queries/complex/pools/incentives.ts

Allow position range APR query to fail, prevent caching of failed value (30s).

Query failure handling

---

packages/web/pages/pool/[id].tsx

Removes redirect of CL pool detail pages on mobile

Remove redirect on mobile

---

packages/stores/src/queries-external/pools/pools.ts

Fixes pool detail page for pools with low liquidity, like pool 1415.

Fix: fetch remaining pools with 0 min liquidity

---

packages/web/server/queries/imperator/filtered-pools.ts

temp: use pools from imperator

---

packages/web/server/queries/imperator/filtered-pools.ts

Revert imperator pools if numia starts working

---

packages/web/server/queries/complex/assets/price/providers/sidecar.ts
packages/web/server/queries/complex/pools/index.ts

* Use indexer for pools
* Fall back to CoinGecko for SQS prices

Publish Stage PR

---

packages/web/pages/api/edge-trpc/[trpc].ts
packages/web/pages/api/pools-edge-trpc/[trpc].ts

feat: Limit Edge Functions to One Region

---

packages/web/server/queries/complex/assets/index.ts
packages/web/server/queries/complex/pools/providers/indexer.ts
packages/web/server/queries/complex/pools/route-token-out-given-in.ts

Optimize some queries in our tRPC stack.
* Indexer getPools: unify to a single cache key even if specific pool IDs are requested. This will prevent multiple pools queries for requesting different pool IDs since the filtering is done after the pools are returned from `getFreshValue` (so there can be a single cache key). This should improve performance of router response.

tRPC query optimizations

---

packages/stores/src/account/base.ts
packages/stores/src/account/types.ts
packages/stores/src/tx/ibc/ibc-transfer.ts

Fix: tx rawLog parsing

---

packages/web/config/ibc-overrides.ts

Add Hava $HAVA Deposit Overrides to TFM
because it doesn't work with normal IBC on our frontend.
Update config/ibc-overrides.ts, adding HAVA and urls to TFM

Add Hava $HAVA Deposit Overrides to TFM

---

yarn.lock

Updated Babel dependencies
yarn upgrade --pattern babel

Updated Babel dependencies

---

packages/web/components/complex/all-pools-table.tsx

hide fees from pools table

---

packages/web/components/assets/categories.tsx
packages/web/components/table/cells/asset.tsx

Use ellipsis to tolerate longer text.
[Linear Task URL](https://linear.app/osmosis/issue/FE-313/broken-part)

Use ellipsis

---

packages/web/pages/api/simulate-transaction.ts

Edge will still help us avoid issues with CORS headers set on users' browsers, and will also include geo-distribution along with our nodes.
* Add edge config for simulate-transaction POST endpoint
Ensure the function is deployed on edge from the Vercel deployment page.

Run tx simulation query on edge

---

packages/server/src/queries/complex/assets/categories.ts
packages/server/src/trpc-routers/assets-router.ts
packages/server/src/utils/sort.ts

This list is now sorted by listing date, desc.

Sort new highlight by listing date desc

---

packages/web/pages/api/simulate-transaction.ts

uses the node Request/Response API

Fix simulate on edge runtime

---

packages/web/config/ibc-overrides.ts

To update DYM and NIM to use the correct deposit URL for the Dym portal
- Update ibc-overrides.ts depositURL for DYM and NIM
Validation successful--DYM Deposit now goes to the correct interface.

Update DYM and NIM Deposit Overrides

---

packages/math/src/pool/concentrated/math.ts
packages/server/src/queries/complex/README.md
packages/stores/src/account/__tests_e2e__/swap-exact-in-positions.spec.ts

chore: remove repetitive words

---

packages/web/components/layouts/main.tsx
packages/web/components/navbar/index.tsx

* Remove x overflow rule on main layout content
* Fix z indexing for token images vs top announcement banner

Fix layout

---

packages/web/components/assets/highlights-categories.tsx

Top gainers 24h style

---

packages/server/src/queries/twitter/twitter.ts

Right now build is failing due to twitter api errors, this is a fix for it.

fix: twitter search

---

packages/server/src/queries/complex/assets/market.ts
packages/web/pages/assets/[denom].tsx

Build time 16m > 4.5min.
Asset:
* Verified, non-preview, stable
* Active on CoinGecko
* Top 50 by volume according to /tokens/v2/all

Asset info page: only generate paths for top 50 tokens

---

packages/web/e2e/tests/swap.wallet.spec.ts

Removed check for token in amount, as route can be split.

Removed check for token in amount

---

packages/web/components/assets/categories.tsx

https://linear.app/osmosis/issue/FE-402/reorder-categories

Asset page: reorder categories

---

packages/web/e2e/tests/swap.wallet.spec.ts

- Added OSMO/USDC and back swap tests
- ATOM/USDC and back swap tests
[Linear FE-412](https://linear.app/osmosis/issue/FE-412)
In pipeline

Added OSMO/USDC and ATOM/USDC swap tests

---

packages/web/components/your-balance/your-balance.tsx
packages/web/pages/assets/[denom].tsx

https://linear.app/osmosis/issue/FE-429/asset-info-page-swap-modal-disappears-when-screen-width-is-condensed

Token Info: responsive swap tool

---

package.json
packages/web/package.json
yarn.lock

Updated Axelar to 0.16 to support Node.js 20.x

Bump Axelar to 0.16

---

package.json
yarn.lock

Just an Update Babel deps in lock file with yarn upgrade --pattern babel
and bump version to 7.24.5

Update Babel deps in lock file

---

packages/proto-codecs/package.json
packages/stores/package.json
packages/web/package.json
yarn.lock

Bump protobufjs to 7.2.6

---

packages/web/pages/_app.tsx

Assets page: remove new pill

---

packages/web/components/bridge/flow.ts
packages/web/components/bridge/immersive/index.ts
packages/web/components/bridge/immersive/provider.tsx
packages/web/components/bridge/legacy.tsx
packages/web/components/stepper/index.tsx
packages/web/components/stepper/progress-bar.tsx
packages/web/hooks/bridge.tsx
packages/web/hooks/use-feature-flags.ts
packages/web/tailwind.config.js

Sets up initial foundation for new deposit withdraw flows. Adds initial immersive flow view that can be toggled on with the [feature flag](https://app.launchdarkly.com/projects/default/flags/new-deposit-withdraw-flow/targeting?env=production&env=test&env=development&selected-env=development)
[Linear Task URL](jon/fe-418-immersive-flow-view)
* Extract old bridge flow into components folder and out of bridge context
* Check FF in bridge context
Check out depoist/withdraw links on preview.
* Toggling FF correctly switches between old and new bridge flows

Deposit/Withdraw: add FF and bridge flows

---

packages/web/components/assets/price.tsx

Assets page: limit price change 1 decimal

---

packages/bridge/README.md
packages/bridge/src/axelar/index.ts
packages/bridge/src/axelar/transfer-status.ts
packages/bridge/src/axelar/types.ts
packages/bridge/src/index.ts
packages/bridge/src/interface.ts
packages/bridge/src/skip/index.ts
packages/bridge/src/skip/transfer-status.ts
packages/bridge/src/skip/types.ts
packages/bridge/src/squid/const.ts
packages/bridge/src/squid/index.ts
packages/bridge/src/squid/transfer-status.ts
packages/web/server/api/routers/bridge-transfer.ts

MVP context needed for all bridge providers, with a focus on a home chain's IBC assets (in our case, Osmosis).
[Linear Task URL](https://linear.app/osmosis/issue/FE-450/bridge-providers-define-context)
* Remove chain list dependency
* Some cleanup of bridge providers
* Provider IDs
* Move display logic out of bridge providers

Bridge Providers: define context

---

packages/web/config/ibc-overrides.ts

Updates Picasso assets' Deposit/Withdraw URL Overrides
Updates URLs to Picasso's bridging app in ibc-overrides.ts

Update Picasso Assets' IBC Overrides

---

packages/utils/src/__tests__/api-client.spec.ts
packages/utils/src/api-client.ts

Remove headers from log

---

packages/web/components/swap-tool/index.tsx
packages/web/config/analytics-events.ts

* Explicitly log failed swaps that aren't rejected swaps
* Log fee value USD

Collect more swap event data

---

packages/tx/src/__tests__/events.spec.ts
packages/tx/src/events.ts
packages/tx/src/gas.ts
packages/web/hooks/use-swap.tsx

* Return eligible fee token in order returned from chain or config (base asset first, AKA OSMO)
* Fix issue with extracting sent coins from gas simulation events, add test case

Gas estimation fixes

---

packages/web/components/swap-tool/swap-tool-tabs.tsx
packages/web/components/trade-tool/index.tsx

Implement new designs for the tab system in the new Home page with "Buy", "Sell" and "Swap" options and manage it with query params.
[Linear Task URL 1](https://linear.app/osmosis/issue/LIM-105/implement-tab-system-with-nuqs)
[Linear Task URL 2](https://linear.app/osmosis/issue/LIM-106/implement-new-tabs-design)

Use query params for limit tool tabs and implement new designs

---

packages/web/hooks/use-swap.tsx

I've noticed that there are failed simulation queries that are sent while the tx is pending with debounced input. This sometimes causes simulations to be run with outdated account data causing errors.
This PR tweaks the query enabled flags to ensure a tx is makes state changes before balance, quote and simulation queries are sent again.
[Linear Task URL](https://linear.app/osmosis/issue/FE-471/support-external-url-providers)
* Improves handling of debounced input
* Improves handling of gas simulation and quote querying while a tx is pending
* Swap tool works as expected. Please monitor console for errors and screen capture (with error message) if you find any (particularly quote or gas estimation queries) and take note of repro steps.
* Switching & selecting assets
* Selecting max/half
* …

Avoid sending gas fee simulation queries while tx is pending

---

packages/web/components/twitter-section/twitter-section.tsx

Improve token info page twitter section images quality.
[Linear Task URL](https://linear.app/osmosis/issue/FE-551/improve-twitter-section-image-quality)

feat: :sparkles: improve twitter section image quality

---

packages/web/config/generate-cosmos-kit-wallet-list.ts
packages/web/config/wallet-registry.ts

change wallet order

---

packages/web/config/wallet-registry.ts

Commenting out for now while the TW team irons out some kinks

comment out trust wallet

---

packages/web/components/trade-tool/index.tsx

[Linear Task URL](https://linear.app/osmosis/issue/LIM-129/[ui]-add-button-for-claimable-orders)

[Limit Orders]: Add claimable orders button

---

.github/workflows/monitoring-e2e-tests.yml
packages/web/e2e/pages/swap-page.ts
packages/web/e2e/tests/select.spec.ts
packages/web/e2e/tests/swap.stables.spec.ts
packages/web/e2e/tests/swap.wallet.spec.ts
packages/web/playwright.config.ts

- reduced schedule time to 15 minutes
- added frontend quote tests

Added frontend quote tests

---

.github/workflows/monitoring-e2e-tests.yml
packages/web/e2e/tests/select.spec.ts

- Disabled nBTC/USDC due to no liquidity.
- Added random sleep to prevent same time execution on Prod and Stage

Temp fix for nBTC and same time execution

---

.github/workflows/monitoring-e2e-tests.yml

Removed sleep

---

packages/trpc/src/orderbook-router.ts
packages/web/components/place-limit-tool/index.tsx
packages/web/hooks/limit-orders/use-orderbook.ts

These changes alter the active order queries to include pagination.
- Altered `getAllActiveOrders` and `getActiveOrders` to include pagination

feat: pagination for limit order queries

---

packages/web/e2e/pages/swap-page.ts
packages/web/e2e/tests/swap.stables.spec.ts
packages/web/e2e/tests/swap.wallet.spec.ts
packages/web/package.json
yarn.lock

Looks like Playwright is loosing Approval page sometimes. To avoid this I merged together swap and approval functions to make sure they are in sync.

Approve tx inside swap function

---

packages/web/e2e/tests/swap.stables.spec.ts

Use allUSDT instead of USDT

---

packages/web/components/complex/orders-history/columns.tsx
packages/web/components/complex/orders-history/index.tsx
packages/web/components/transactions/order-history.tsx
packages/web/components/transactions/transaction-content.tsx

Add reference table headers
[Linear Task URL](https://linear.app/osmosis/issue/LIM-132/[ui]-add-base-reference-headers)

[Order History]: Add base reference headers

---

packages/trpc/src/assets.ts
packages/web/components/complex/portfolio-page.tsx
packages/web/components/pages/asset-info-page/your-balance.tsx
packages/web/components/ui/button.tsx
packages/web/localizations/de.json
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/gu.json
packages/web/localizations/hi.json
packages/web/localizations/ja.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/ru.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/pages/assets/[denom].tsx

This PR adds the new balance section to the detail page when a wallet is connected, and also removes the use of queries with mobx stores.
[Restyle balance section](https://linear.app/osmosis/issue/FE-570/restyle-your-balance-section)
[Token info page](https://linear.app/osmosis/issue/FE-6/token-info-page)

feat: add new balance section

---

.github/workflows/frontend-e2e-tests.yml
packages/web/e2e/pages/base-page.ts
packages/web/e2e/pages/portfolio-page.ts
packages/web/e2e/pages/swap-page.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts

Added Portfolio tests with wallet connected.
[Add automated test for a Portfolio](https://linear.app/osmosis/issue/FE-452/add-automated-test-for-a-portfolio)
- Added Portfolio tests
- Added Base page
- Added Portfolio page
- Added Portfolio tests to FE workflow

Added first portfolio tests

---

.github/workflows/monitoring-e2e-tests.yml

Due to cost analysis we decided to not run FE tests every 15 minutes.
[Linear Task URL](https://linear.app/osmosis/issue/FE-585)

Remove Stage frontend monitoring tests

---

packages/web/e2e/tests/swap.stables.spec.ts

- Added swap USDT.axl to kava.USDT
- Added swap kava.USDT to USDT.axl

Added kava.USDT tests

---

packages/server/src/queries/complex/pools/env.ts

Uploaded in https://daodao.zone/dao/osmosis/proposals/791
Confirmed migrated: https://celatone.osmosis.zone/osmosis-1/codes/842
Both testnet and mainnet will now be v1.0.3

Push new Astroport mainnet code ID

---

packages/web/components/control/token-select-limit.tsx
packages/web/components/place-limit-tool/index.tsx
packages/web/components/place-limit-tool/limit-price-selector.tsx
packages/web/components/place-limit-tool/limit-trade-details.tsx
packages/web/components/swap-tool/alt.tsx
packages/web/components/swap-tool/order-type-selector.tsx
packages/web/components/swap-tool/price-selector.tsx
packages/web/components/swap-tool/swap-tool-tabs.tsx
packages/web/components/transactions/transaction-content.tsx
packages/web/localizations/de.json
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/gu.json
packages/web/localizations/hi.json
packages/web/localizations/ja.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/ru.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/modals/review-limit-order.tsx
packages/web/modals/review-swap.tsx
packages/web/modals/token-select-modal-limit.tsx
packages/web/pages/index.tsx

Mass translate the Limit Orders and Order History pages
[Linear Task URL](https://linear.app/osmosis/issue/LIM-139/i18n-every-ui-label)

[Limit Orders / Order History]: Implement i18n

---

packages/server/src/queries/complex/orderbooks/historical-orders.ts
packages/server/src/queries/osmosis/orderbooks.ts
packages/trpc/src/orderbook-router.ts
packages/web/hooks/use-feature-flags.ts

These changes add a historical order element when an order is partially filled before being cancelled.
- Added additional orders for partially filled + cancelled orders

feat: partial filled past orders

---

packages/web/components/swap-tool/alt.tsx
packages/web/components/swap-tool/price-selector.tsx
packages/web/pages/index.tsx

[Linear Task URL](https://linear.app/osmosis/issue/LIM-163/implement-swap-from-another-asset-cta)

[Limit Orders]: Implement "Swap from another asset" CTA

---

packages/bridge/src/ibc/__tests__/ibc-bridge-provider.spec.ts
packages/bridge/src/ibc/index.ts
packages/web/components/bridge/immersive/amount-and-review-screen.tsx
packages/web/components/bridge/immersive/amount-screen.tsx
packages/web/components/bridge/immersive/crypto-fiat-input.tsx
packages/web/components/bridge/immersive/review-screen.tsx
packages/web/components/bridge/immersive/use-bridge-quotes.ts
packages/web/components/ui/button.tsx

If the gas cost in the selected quote exceeds the available balance when summed with the input amount, it is subtracted from the fiat and crypto input amounts. In effect, a new quote is loaded with an input that leaves enough balance to pay fees.
[Linear Task URL](https://linear.app/osmosis/issue/FE-613/amount-input-subtract-gas)

(Deposit/Withdraw) Subtract gas from input amount

---

.github/workflows/frontend-e2e-tests.yml
packages/web/e2e/pages/base-page.ts
packages/web/e2e/pages/pool-page.ts
packages/web/e2e/pages/pools-page.ts
packages/web/e2e/pages/swap-page.ts
packages/web/e2e/tests/pools.spec.ts

- Added Pools page tests
- Added tests to frontend regression workflow
[swaps-over-specific-pools](https://linear.app/osmosis/issue/FE-584)

Added Pools page tests

---

packages/web/components/alloyed-assets.tsx
packages/web/components/pages/asset-info-page/token-details.tsx
packages/web/pages/assets/[denom].tsx
yarn.lock

fix: :bug: fix token info sections

---

packages/web/e2e/tests/swap.wallet.spec.ts

Changed swap amounts to reflect lower prices :(

Updated swap amounts

---

packages/web/e2e/tests/swap.stables.spec.ts

Updated USDT.kava tests after a rename.

Updated USDT.kava tests

---

packages/web/components/pages/asset-info-page/token-chart.tsx
packages/web/components/pages/asset-info-page/token-details.tsx

Minor ui improvement for token info page:
1) Better price fallback if current price is missing
2) Fix text overflow inside token info description
3) Fix stat alignment

fix: minor token info

---

packages/web/localizations/de.json
packages/web/localizations/en.json
packages/web/localizations/es.json
packages/web/localizations/fa.json
packages/web/localizations/fr.json
packages/web/localizations/gu.json
packages/web/localizations/hi.json
packages/web/localizations/ja.json
packages/web/localizations/ko.json
packages/web/localizations/pl.json
packages/web/localizations/pt-br.json
packages/web/localizations/ro.json
packages/web/localizations/ru.json
packages/web/localizations/tr.json
packages/web/localizations/zh-cn.json
packages/web/localizations/zh-hk.json
packages/web/localizations/zh-tw.json
packages/web/pages/index.tsx

This PR removes the 1CT swap rotating banner and updates the copy in the code. 
[Remove banner above Swap tool](https://linear.app/osmosis/issue/FE-747/remove-banner-above-swap-tool)
[Change copy](https://linear.app/osmosis/issue/FE-749/change-copy)

(1CT) Remove Swap Rotating Banner and Change Copy

---

packages/web/e2e/pages/base-page.ts
packages/web/e2e/pages/transactions-page.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts
packages/web/e2e/tests/swap.stables.spec.ts
packages/web/e2e/tests/swap.wallet.spec.ts
packages/web/e2e/tests/transactions.wallet.spec.ts

- Added wallet test 
- Added more time for trx test
- Bigger viewport

Added wallet test and more time for trx test

---

packages/web/components/bridge/asset-select-screen.tsx

Add bg to sticky search box
[Linear Task URL](https://linear.app/osmosis/issue/FE-752/need-background-behind-search-assets-bar)

(Deposit/Withdraw) search box bg

---

packages/web/config/ibc-overrides.ts

Update Symbols in IBC Overrides
Updates the symbols in IBC Overrides to match the latest changes.
This change has not been tested locally, because I cannot get the FE to build locally.

Update Symbols in IBC Overrides

---

packages/web/config/ibc-overrides.ts

Add Mande $MAND Deposit Override
Add deposit and withdraw URL overrides for MAND on ibc-overrides (and a withdraw URL for NIM, because it should have had it the whole time)

Add Mande $MAND Deposit Override

---

packages/web/.gitignore
packages/web/e2e/pages/transactions-page.ts
packages/web/e2e/tests/select.spec.ts

- 20 seconds timeout for transactions
- Use USDC and USDT in select tests

Added fix for USDC types

---

packages/types/src/chain-types.ts
yarn.lock

Fixes FE type to match registry chain theme type

Fix theme type

---

packages/web/components/bridge/crypto-fiat-input.tsx

Allow decimal input before trimming decimals.

(Deposit/Withdraw) Allow decimal & 0 input

---

packages/web/e2e/pages/transactions-page.ts

Wait 1 minute for a transaction

Wait 1 minute for a transaction

---

packages/web/e2e/tests/swap.stables.spec.ts

Updated Axelar USD

---

packages/bridge/src/wormhole/index.ts

Small fix to portal query params after the team got back to me regarding the param format.
[Linear Task URL](https://linear.app/osmosis/issue/FE-789/fix-portal-external-url)

(Deposit/Withdraw) Wormhole portal bridge: update portal URL

---

packages/web/components/bridge/immersive-bridge.tsx

fix padding

---

.github/workflows/monitoring-e2e-tests.yml
packages/web/e2e/pages/portfolio-page.ts
packages/web/e2e/pages/transactions-page.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts
packages/web/e2e/tests/transactions.wallet.spec.ts

- Fixed Portfolio
- Transactions tests
- Skipped new Transaction test
[update-portfolio-and-transaction-tests](https://linear.app/osmosis/issue/FE-809/)

Fixed Portfolio and Transaction tests

---

packages/server/src/queries/complex/concentrated-liquidity/index.ts
packages/server/src/queries/complex/pools/bonding.ts
packages/server/src/queries/complex/pools/incentives.ts
packages/server/src/queries/data-services/pool-aprs.ts
packages/trpc/src/pools.ts
packages/web/components/cards/apr-breakdown.tsx
packages/web/components/complex/my-pools-card-grid.tsx
packages/web/components/complex/pools-table.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/components/pool-detail/share.tsx

Reverts osmosis-labs/osmosis-frontend#3392

Revert "feat: aprs should be shown as a range"

---

packages/bridge/src/axelar/index.ts
packages/bridge/src/ibc/index.ts
packages/bridge/src/skip/index.ts
packages/bridge/src/squid/error.ts
packages/bridge/src/squid/index.ts
packages/web/components/bridge/amount-and-review-screen.tsx
packages/web/components/bridge/amount-screen.tsx

Since Skip supports swaps in Cosmos, we return counterparties of all assets of the same variant as a supported asset of the given variant of Osmosis. This is validated against Skip's asset list, and it is assumed Skip knows how to swap it.
[Linear Task URL](https://linear.app/osmosis/issue/FE-794/alloyed-asset-not-recommended)

(Deposit/Withdraw) Recommend Alloyed asset

---

packages/web/components/earn/table/cells.tsx

fix: :bug: fix earn label rendering

---

packages/web/e2e/pages/portfolio-page.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts

Added portfolio functions back to tests

Added portfolio functions back to tests

---

packages/web/components/one-click-trading/one-click-trading-settings.tsx
packages/web/components/one-click-trading/one-click-trading-welcome-back.tsx

[Add Ledger Coming Soon Text to 1CT Settings](https://linear.app/osmosis/issue/FE-825/add-ledger-coming-soon-text-to-1ct-settings)
[Change footnote for fee to disable 1-CT](https://linear.app/osmosis/issue/FE-703/change-footnote-for-fee-to-disable-1-ct)

(1CT) Change footnote for fee to disable 1CT &  Add Ledger Coming Soon Text to Settings

---

packages/web/components/bridge/amount-screen.tsx
packages/web/components/bridge/asset-select-screen.tsx
packages/web/components/bridge/bridge-network-select-modal.tsx
packages/web/components/bridge/bridge-wallet-select-modal.tsx
packages/web/components/bridge/immersive-bridge.tsx
packages/web/components/bridge/review-screen.tsx
packages/web/components/complex/assets-page-v1.tsx
packages/web/components/drawers/token-select-drawer.tsx
packages/web/components/input/search-box.tsx
packages/web/components/navbar/index.tsx
packages/web/modals/wallet-select/use-selectable-wallets.ts
packages/web/stores/nav-bar.ts

Fixes from Design QA round 1. See linear subtasks for details:
[Linear Task URL](https://linear.app/osmosis/issue/FE-798/design-qa-1)

(Deposit/Withdraw) Design QA 1

---

packages/web/components/bridge/asset-select-screen.tsx
packages/web/components/bridge/bridge-network-select-modal.tsx
packages/web/components/bridge/bridge-wallet-select-modal.tsx
packages/web/components/bridge/immersive-bridge.tsx
packages/web/components/drawers/token-select-drawer.tsx
packages/web/components/stepper/progress-bar.tsx
packages/web/hooks/use-keyboard-navigation.ts

Fixes from Design QA round 2. See subtasks in linear issue for details.
[Linear Task URL](https://linear.app/osmosis/issue/FE-812/design-qa-2)

(Deposit/Withdraw) Design QA 2

---

.github/workflows/monitoring-e2e-tests.yml
packages/web/e2e/pages/swap-page.ts

Fix swap test locator

---

packages/bridge/src/skip/index.ts
packages/web/components/control/crypto-fiat-input.tsx

[Linear Task URL](https://linear.app/osmosis/issue/FE-829/fix-infinite-gas-adjustment-loop)

(Deposit/Withdraw) Max gas input: fix set state loop

---

packages/stores/src/ui-config/slippage-config.ts
packages/web/components/swap-tool/alt.tsx
packages/web/components/swap-tool/trade-details.tsx
packages/web/modals/review-swap.tsx

improve swap review screen and slippage setting

---

packages/web/components/bridge/asset-select-screen.tsx
packages/web/components/bridge/immersive-bridge.tsx
packages/web/components/input/search-box.tsx
packages/web/hooks/window/use-window-size.ts

Fix scrolling on mobile safari
[Linear Task URL](https://linear.app/osmosis/issue/FE-742/mobile-iphone-cant-scroll-assets)

(Deposit/Withdraw) Fix scroll on mobile

---

packages/web/components/bridge/asset-select-screen.tsx
packages/web/components/bridge/immersive-bridge.tsx

Store asset and direction in query params. The default direction will be deposit if only the asset is given.
[Linear Task URL](https://linear.app/osmosis/issue/FE-793/store-denom-and-direction-in-query-params)

(Deposit/Withdraw) Add direction & asset query params

---

packages/web/components/bridge/asset-select-screen.tsx

[Linear Task URL](https://linear.app/osmosis/issue/FE-651/unverified-assets-wont-show-balance-warning-icon-shouldnt-be-in-the)

(Deposit/Withdraw) Show Unverified Asset Balance

---

packages/stores/src/account/base.ts

[Linear Task URL](https://linear.app/osmosis/issue/FE-790/1ct-txs-doesnt-show-fe-in-memo)

(1CT) Add 1CT Memo

---

packages/web/hooks/limit-orders/use-place-limit.ts

These changes adjust the input quantity for buy limit orders.

[Limit Orders]: Input Quantity Fix

---

packages/web/components/control/token-select-limit.tsx
packages/web/components/place-limit-tool/index.tsx
packages/web/components/swap-tool/order-type-selector.tsx
packages/web/hooks/limit-orders/use-orderbook.ts

These changes adjust the initial state of the buy/sell tabs to behave as expected.
[LIM-205: Buy/Sell Initial Loading State](https://linear.app/osmosis/issue/LIM-205/buysell-initial-loading-state)
- Improved buy/sell button initial loading state

[Limit Orders]: Buy/Sell tab initial loading state

---

packages/bridge/src/axelar/index.ts
packages/bridge/src/ibc/index.ts
packages/bridge/src/ibc/transfer-status.ts
packages/bridge/src/skip/index.ts
packages/bridge/src/squid/index.ts
packages/stores/src/account/base.ts
packages/tx/package.json
packages/tx/src/index.ts
packages/tx/src/msg.ts
packages/web/components/input/scaled-currency-input.tsx

Various fixes
* If an IBC transfer's status couldn't be determined within one minute, display it as some unknown connection error
* Discovered this from some gateway and websocket issues with lavender fives dydx nodes
* Crypto amount input fix
* Catch errors from transaction stage and prevent query error from reaching error boundary (this only affects dev, not prod)
* Light refactor: move msg opts to tx package

(Deposit/Withdraw) Miscellaneous fixes

---

packages/web/pages/wormhole.tsx

Add additional security to verify that the link has not been tampered with when fetching the wormhole from unpkg.

Add `integrity` to wormhole <link/> and <script/>

---

packages/web/components/swap-tool/alt.tsx

swap re-layout

---

.github/workflows/monitoring-e2e-tests.yml
.github/workflows/monitoring-geo-e2e-tests.yml

- Fixed test workflow dependency

Fix test workflow dependency

---

packages/web/components/bridge/bridge-wallet-select-modal.tsx
packages/web/components/bridge/immersive-bridge.tsx
packages/web/components/screen-manager.tsx
packages/web/components/ui/button.tsx

The progress bar and header should be pinned, and in the asset select screen, the search bar should be pinned to that.
[Linear Task URL](https://linear.app/osmosis/issue/FE-855/fix-scroll-ux)

(Deposit/Withdraw) Fix Scroll UX

---

packages/web/components/bridge/amount-and-review-screen.tsx
packages/web/components/bridge/amount-screen.tsx
packages/web/components/bridge/bridge-provider-dropdown.tsx
packages/web/components/bridge/bridge-wallet-select-modal.tsx
packages/web/components/bridge/immersive-bridge.tsx
packages/web/components/complex/portfolio-page.tsx
packages/web/components/drawers/token-select-drawer.tsx
packages/web/components/pages/asset-info-page/balance.tsx
packages/web/components/table/asset-balances.tsx
packages/web/config/analytics-events.ts
packages/web/hooks/bridge.tsx
packages/web/pages/api/estimate-gas-fee.ts
packages/web/pages/stake.tsx

Final spec from discussion with Lucas
https://linear.app/osmosis/issue/FE-458/amplitude-events#comment-bbc8247f
[Linear Task URL](https://linear.app/osmosis/issue/FE-458/amplitude-events)
Tested manually with console logs.

(Deposit/Withdraw) Add Amplitude events

---

packages/server/src/queries/cosmos/rpc-status.ts
packages/tx/src/__tests__/gas.spec.ts
packages/tx/src/__tests__/poll-status.spec.ts
packages/tx/src/gas.ts
packages/web/components/bridge/quote-detail.tsx
packages/web/components/bridge/use-bridge-quotes.ts

[Linear Task URL](https://linear.app/osmosis/issue/FE-859/amount-screen-prevent-advancement-if-any-quotes-are-loading)
[FE-860 : Investigate SEI and INJ node incompatibilities](https://linear.app/osmosis/issue/FE-860/investigate-sei-and-inj-node-incompatibilities)
[FE-746 : Remove tilde (~) from anything with less than operator (<)](https://linear.app/osmosis/issue/FE-746/remove-tilde-from-anything-with-less-than-operator)
[FE-808 : Akash gas estimation + Keplr issues](https://linear.app/osmosis/issue/FE-808/akash-gas-estimation-keplr-issues)
* Fix endpoint compatibilities with some chains
* Use high gas price instead of avg gas price to increase chance of txs succeeding with enough balance to pay fee
* Fixes insufficient balance errors in Keplr for Akash and Injective
* Fix inequality …

(Deposit/Withdraw) Improvements

---

packages/web/e2e/tests/swap.stables-extra.spec.ts

- Moved kava.USDT tests to a separate spec file
- Added USDT/USDC swap test

Updated stable swap tests

---

.github/workflows/monitoring-geo-e2e-tests.yml

Decrease timeout for geo tests to 10 minutes

Decrease timeout for geo tests

---

packages/bridge/src/axelar/index.ts
packages/web/config/ibc-overrides.ts

Prevent Axelar from returning assets from the same chain.
[Linear Task URL](https://linear.app/osmosis/issue/FE-870/fix-withdrawdeposit-osmo-from-osmosis-to-osmosis)

(Deposit/Withdraw) Axelar: prevent supported assets from returning the same chain

---

packages/keplr-stores/src/price/index.ts
packages/web/components/place-limit-tool/index.tsx
packages/web/components/place-limit-tool/limit-price-selector.tsx
packages/web/hooks/limit-orders/use-place-limit.ts

[Limit Orders] v3 Max button logic

---

packages/web/config/ibc-overrides.ts

Add Penumbra $UM IBC Override to
https://stake.with.starlingcyber.net/#/ibc
- adds deposit and withdraw URL overrides for UM at ibc-overrides.ts
- 

Add Penumbra $UM IBC Override

---

packages/web/components/complex/orders-history/index.tsx

[Linear Task URL](https://linear.app/osmosis/issue/FE-913/page-width-adjusting-to-scroll-bar-fix-to-make-contents-fixed)

fix: :lipstick: fix order history table overflow

---

.github/workflows/frontend-e2e-tests.yml
packages/web/e2e/unzip-extension.ts

- Added timeout to frontend tests
- Bump Keplr wallet

Added timeout for frontend tests and bump Keplr

---

packages/web/components/funnels/concentrated-liquidity/supercharge-pool.tsx
packages/web/components/place-limit-tool/limit-price-selector.tsx
packages/web/components/pool-detail/concentrated.tsx
packages/web/components/pool-detail/share.tsx
packages/web/components/trade-tool/index.tsx
packages/web/modals/review-order.tsx
packages/web/modals/trade-tokens.tsx
packages/web/tailwind.config.js

These changes are for small design changes for the swap tool when opened from the pools page.
- Added a header to the modal
- Fixed the maximum width of the modal
- Fixed a few background colour issues

[Limit Orders - V3]: Swap Tool on Pools Page

---

packages/server/src/queries/complex/pools/providers/sidecar.ts

fix SQS total weight values

---

packages/pools/src/weighted.ts

fix: frontend bug breaking weighted LP (#3667)

---

packages/web/components/bridge/immersive-bridge.tsx

Fixes logging asset selected if using a query param to select the asset.

(Deposit/Withdraw) log asset selected from query params

---

packages/web/components/place-limit-tool/limit-price-selector.tsx
packages/web/hooks/limit-orders/use-place-limit.ts
packages/web/modals/review-order.tsx

These changes fix some small bugs with the price input:
- Inputting a large amount would crash due to a maximum decimal amount in percentage
- Altering percentage by a small amount for a small price wasn't updating as intended

[Limit Orders - V3]: Price Input Bug Fixes

---

packages/web/hooks/use-feature-flags.ts

These changes add geolocation based feature flagging for limit orders. This can be controlled via the `NEXT_PUBLIC_LIMIT_ORDER_COUNTRY_CODES` environment variable using country codes separated by commas, for example `POL,US,GB` for Poland, US and GB. If the environment variable is empty or undefined the feature flag is purely controlled by the current feature flag state.
[LIM-207](https://linear.app/osmosis/issue/LIM-207/add-geolocation-restrictions)

[Limit Orders - V3]: Geolocation Feature Flagging

---

packages/web/modals/trade-tokens.tsx
packages/web/pages/assets/[denom].tsx

These changes fix the swap tool used depending on the limit orders feature flag.

[Limit Orders - V3]: Swap Tool Feature Flags

---

packages/web/modals/token-select-modal-limit.tsx

fix: :bug: fix trade widget search

---

.github/workflows/frontend-e2e-tests.yml
.github/workflows/monitoring-geo-e2e-tests.yml
packages/web/e2e/pages/swap-page.ts
packages/web/e2e/tests/select.spec.ts
packages/web/e2e/tests/swap.stables.spec.ts

Test will use old Swap tool for Prod and new Trade tool for Stage/Preview environments.

Added feature flag to tests

---

packages/trpc/src/orderbook-router.ts
packages/web/components/table/asset-info.tsx

These changes include a tiny improvement to the limit orders query and fix a small issue with an incorrect background on the assets page.

fix: small orders query adjustment and bg fix for assets page

---

packages/web/e2e/pages/trade-page.ts
packages/web/e2e/tests/swap.wallet.spec.ts

Fix input locator in Trade page

Fix input and limit change locators

---

packages/web/components/place-limit-tool/index.tsx

Removes an invalid loading state

fix: denom selection loading state

---

.github/workflows/monitoring-geo-e2e-tests.yml
packages/web/e2e/test-config.ts

- Renamed variable USE_TEST_PROXY
- Explicit use of variable USE_TRADE

Renamed variables for a testing workflow

---

packages/web/e2e/pages/portfolio-page.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts
packages/web/playwright.config.ts

Due to portfolio page change added a search for a token for 2 reasons:
- make sure search works
- make sure token gets to a view

Added search for portfolio tests

---

.github/workflows/monitoring-geo-e2e-tests.yml

Added 3m timeout to trade test

Added 3m timeout to trade test

---

packages/web/hooks/use-swap.tsx

The trade page crashes if the URL token in or out is not found in our asset list. This PR fixes the issue by properly handling undefined values
https://linear.app/osmosis/issue/FE-1037/trade-page-crashes-due-to-outdated-token-symbol

(Trade page) Do not crash page with unknown denoms

---

packages/web/components/swap-tool/price-selector.tsx
packages/web/hooks/limit-orders/use-place-limit.ts

These changes apply the fixes from https://github.com/osmosis-labs/osmosis-frontend/pull/3777 for the buy and sell tabs

fix: invalid base/quote denom for buy/sell

---

packages/web/components/place-limit-tool/index.tsx
packages/web/components/swap-tool/alt.tsx
packages/web/hooks/use-swap.tsx

These changes fix a small issue with swap behavior when in given out feature flag is disabled.

[In Given Out]: Feature Flag

---

.github/workflows/monitoring-geo-e2e-tests.yml

Enable US quote tests to use trade app

Enable US quote tests to use trade app

---

packages/web/e2e/pages/trade-page.ts

Fix locator for Insufficient balance message

Fix locator for Insufficient balance message

---

.github/workflows/monitoring-claim-orders .yml

- Fixed Private Key name for claim all job

Fixed Private Key name

---

packages/web/components/alert/limit-orders-toast.tsx
packages/web/pages/_app.tsx

These changes fix the following:
- Clicking the toast arrow button did not redirect the user
- The close button background was incorrect

fix: limit toast arrow button action

---

.github/workflows/frontend-e2e-tests.yml
.github/workflows/monitoring-geo-e2e-tests.yml
packages/web/e2e/tests/select.spec.ts

- Fixed trade flag for select tests

Fixed trade flag for select tests

---

.github/workflows/monitoring-geo-e2e-tests.yml

- Removed trade flag for SG
- Run EU trades after SG swaps

Removed trade flag for SG

---

packages/web/e2e/tests/monitoring.wallet.spec.ts

- Lower limit buy to 107% from 110%

Lower limit buy to 107%

---

.github/workflows/monitoring-geo-e2e-tests.yml
packages/web/README.md
packages/web/e2e/README.md
packages/web/e2e/tests/stables.wallet.spec.ts

Updated a readme for tests

---

packages/web/components/complex/orders-history/index.tsx

These changes fix some squashing issues with the claimable orders row on mobile.

fix: claimable orders mobile

---

packages/bridge/src/ibc/transfer-status.ts
packages/web/components/assets/price.tsx

Increases IBC timeout to help alleviate issues with RPC.
-

Increase IBC transfer status connection timeout

---

packages/web/components/transactions/recent-activity/recent-activity-transaction-row.tsx
packages/web/components/transactions/transaction-details/transaction-details-content.tsx
packages/web/components/transactions/transaction-row.tsx

fix lint issue

---

packages/web/components/earn/filters/filter-context.tsx
packages/web/pages/earn/index.tsx

- we need a new link to earn from an asset from the portfolio page, this is a pre-requisite to that
- add a query param to earn page "search" that auto-populates search field
https://linear.app/osmosis/issue/FE-1065/porfolio-v3-add-query-param-for-earn-page-link
Uploading Screen Recording 2024-09-09 at 5.15.23 PM.mov…

add search from query param for earn

---

packages/web/e2e/pages/swap-page.ts
packages/web/e2e/pages/trade-page.ts
packages/web/e2e/tests/monitoring.wallet.spec.ts

- Updated swap/trade page
- Timeout to 10 secs

Updated swap/trade page

---

packages/server/src/queries/complex/pools/index.ts
packages/web/components/complex/pools-table.tsx

Filtering out pool 2159
https://linear.app/osmosis/issue/POL-1363/filter-out-pool-2159
- Filter out bad pool

filter out bad pool per request from adam and johnny

---

packages/web/e2e/pages/trade-page.ts
packages/web/e2e/tests/trade.wallet.spec.ts

- Added a timeout after a transaction
Will come up with something better soon.

Added a timeout after a transaction

---

.github/workflows/monitoring-limit-geo-e2e-tests.yml
packages/web/e2e/pages/trade-page.ts
packages/web/e2e/tests/monitoring.wallet.spec.ts
packages/web/package.json
yarn.lock

- Changed workflow to reduce number of alerts

Bump Playwright and Prod monitoring

---

packages/web/e2e/tests/monitoring.wallet.spec.ts

Skip Market Sell WBTC test

---

packages/web/e2e/tests/monitoring.limit.wallet.spec.ts
packages/web/e2e/tests/monitoring.market.wallet.spec.ts
packages/web/e2e/tests/portfolio.wallet.spec.ts

Increase order amounts

---

packages/server/src/queries/complex/pools/providers/__tests__/sidecar.spec.ts
packages/web/modals/variants-conversion.tsx

Adds fix that closes modal after the last conversion is completed and the user data refetches.

Fix: close modal on last conversion

---

.github/workflows/monitoring-limit-geo-e2e-tests.yml
packages/web/e2e/pages/trade-page.ts
packages/web/e2e/tests/monitoring.market.wallet.spec.ts

- More USD per Market Order
- Less timeout for a test

More USD per Market Order

---

packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts
packages/bridge/src/skip/index.ts
packages/web/components/bridge/use-bridge-quotes.ts

https://linear.app/osmosis/issue/FE-1216/error-withdrawing-atom-to-stargaze-using-skip

(Deposit/Withdrawal) Fix atom stargaze withdrawal

---

packages/web/e2e/tests/stables.wallet.spec.ts
packages/web/e2e/tests/trade.wallet.spec.ts

- Increased amounts for swaps as 0.25$ is too small
- Updated ATOM buy test

Updated ATOM tests and swap amounts

---

packages/server/src/queries/complex/portfolio/__tests__/assets.spec.ts
packages/server/src/queries/complex/portfolio/assets.ts
packages/server/src/queries/sidecar/portfolio-assets.ts
packages/stores/src/account/base.ts
packages/web/hooks/use-convert-variant.ts
packages/web/next-env.d.ts

- Add usdValue to the convert variant complete event.
- Change the FE label to OsmosisFE to make sure it does not collide with other labels set by other teams
https://linear.app/osmosis/issue/FE-1235/update-ampli-events-and-tx-memo

(Events) Update Ampli Events and TX memo

---

packages/web/components/chart/light-weight-charts/helpers/dimensions/positions.ts
packages/web/hooks/limit-orders/use-orderbook.ts

remove redundant words in comment
remove redundant words in comment

chore: remove redundant words in comment

---

packages/web/components/pages/asset-info-page/pools.tsx

Fix pools filtering by denom on assets page
BE-636
Passes denom as search string
<!-- _(Please pick either of the following options)_

BE-636 | Fix pools filtering by denom on assets page

---

.github/workflows/monitoring-quote-geo-e2e-tests.yml
packages/e2e/pages/base-page.ts
packages/e2e/tests/monitoring.limit.wallet.spec.ts
packages/e2e/tests/monitoring.market.wallet.spec.ts
packages/e2e/tests/swap.osmo.wallet.spec.ts
packages/e2e/tests/swap.usdc.wallet.spec.ts
packages/e2e/tests/trade.wallet.spec.ts
packages/web/components/navbar/index.tsx
yarn.lock

- Disconnect a wallet after each test set.

Refactor wallet connection logic and update monitoring alert text

---

packages/e2e/pages/base-page.ts

Enhance BasePage class by adding connectedWalletBtn locator and improving code consistency

---

packages/e2e/tests/monitoring.limit.wallet.spec.ts
packages/e2e/tests/monitoring.market.wallet.spec.ts
packages/e2e/tests/trade.wallet.spec.ts

- Change Monitoring e2e workflow
- Change Trade workflow

Refactor monitoring limit wallet tests for improved readability and consistency

---

.github/workflows/frontend-e2e-tests.yml
packages/e2e/playwright.config.ts
packages/e2e/unzip-extension.ts

Bump Keplr to 188 and add Json test report

Bump Keplr to 188 and add Json test report

---

.github/workflows/frontend-e2e-tests.yml
.github/workflows/monitoring-limit-geo-e2e-tests.yml

- update output handling in e2e test workflows and improve failure conditions

fix: update output handling in e2e test workflows and improve failure conditions

---

packages/e2e/pages/keplr-page.ts
packages/e2e/unzip-extension.ts

Update Keplr extension to version 0.12.209

---

packages/e2e/pages/keplr-page.ts
packages/e2e/setup-keplr.ts
packages/e2e/tests/claim.spec.ts
packages/e2e/tests/monitoring.limit.wallet.spec.ts
packages/e2e/tests/monitoring.market.wallet.spec.ts
packages/e2e/tests/monitoring.swap.wallet.spec.ts
packages/e2e/tests/portfolio.wallet.spec.ts
packages/e2e/tests/swap.osmo.wallet.spec.ts
packages/e2e/tests/swap.usdc.wallet.spec.ts
packages/e2e/tests/trade.wallet.spec.ts
packages/e2e/tests/transactions.wallet.spec.ts
packages/e2e/unzip-extension.ts

-  Refactor wallet setup process

Refactor wallet setup process

---

packages/web/utils/trading-view.ts

Currently, all timeframes (e.g., 5m, 1h, 4h) are requesting the same endpoint instead of updating based on timeframe. This PR fixes this issue by updating the endpoint based on the selected timeframe
https://linear.app/osmosis/issue/FE-1342/tradingview-charts-do-not-load-proper-volume-data-across-timeframes

Fix TradingView Charts Do Not Load Proper Volume Data Across Timeframes

---

packages/bridge/src/int3face/index.ts

Currently, when depositing DOGE, the flow is not intuitive. Users see “Skip Go” as the first option and are unlikely to realize that Int3face can bridge DOGE from the Dogecoin network. Additionally, for withdrawals, two links to Int3face are shown. Only one is necessary.
https://linear.app/osmosis/issue/FE-1356/improve-doge-deposit-flow-by-showing-int3face-bridge-external-link

Improve DOGE Deposit Flow by Showing Int3face Bridge External Link

---

packages/pools/src/router/types.ts
packages/server/src/queries/complex/swap.ts
packages/web/components/place-limit-tool/index.tsx
packages/web/components/swap-tool/index.tsx
packages/web/components/swap-tool/trade-details.tsx
packages/web/hooks/__tests__/fiat-getters.spec.ts
packages/web/hooks/fiat-getters.ts

[BE-740](https://linear.app/osmosis/issue/BE-740/log-ticket-for-previously-reported-pricing-issues)
This PR attemps to fix pricing discrepancies is the swap tool.
Main source of the changes stems from the fact that price impact can be negative. Negative impact means negative impact where user would receve less and positive impact represents arb opportunity.
This change has been tested by fixing existing and adding new relevant test cases

BE-740 | Fix pricing discrepancies is the swap tool

---

packages/web/components/bridge/amount-and-review-screen.tsx
packages/web/components/bridge/amount-screen.tsx
packages/web/components/bridge/bridge-provider-dropdown.tsx
packages/web/components/bridge/quote-detail.tsx
packages/web/components/bridge/review-screen.tsx
packages/web/components/bridge/use-bridge-quotes.ts
packages/web/components/control/crypto-fiat-input.tsx
packages/web/hooks/queries/assets/use-price.ts
packages/web/server/api/routers/bridge-transfer.ts

Ease asset and liquidity onboarding

---

packages/server/src/queries/sidecar/pools.ts

[BE-674](https://linear.app/osmosis/issue/BE-674/fix-transmuter-display-issue-for-pool-visibility)
Fixes filtering transmuter pool types in the pools list

BE-674 | Fix filter of Transmuter type pools

---

packages/web/components/bridge/use-bridge-quotes.ts

Fix a withdrawal issues that resulted in a lower amount to be withdrawn instead of the user inserted amount

fix: Multiply by 0.98 instead of dividing by 95

---

packages/e2e/unzip-extension.ts

fix: update keplr extension manifest zip file to version 0.12.270
