osmosis-labs/osmosis-frontend

src/components/common/DisplayLeftTime.tsx, src/pages/pool/components/PoolInfoHeader/index.tsx
This seems like a decent way to show an arbitrary number of denominations for a pool.
LMK what you think, we were thinking of using a '-' instead of a ':'.
Fixes #61
=> Issue #61: Show pool composition in pool detail header

src/stores/root.ts
Reduced fees on IBC Deposit from Secret, Cosmos & Terra by setting more appropriate gas limits.
=> Cheaper IBC deposit fees

src/config.ts
Modify Cheqd gas price step from default to 25,30,50 to account for 10^9 base token denom.
=> Change gasPriceStep for Cheqd

src/stores/osmosis/account/index.ts
The upgrade did a patch to create fewer locks. However there was a regression in gas amounts for folks who already have many locks pre-upgrade. We didn't catch this, really sorry :/
(We wrote a test for testing this ... just we tested the Keeper LockTokens function, not the `LockTokens` message. Hence we missed this)
Testing on mainnet, I get ~130k gas needed, so 400k should be more than enough for people with way too high gas params
=> Bump lock tokens gas due to Boron chain upgrade

src/components/SwapToken/TokenSelect/index.tsx
It seems strange to be able to select from only one available token that is also one that is already selected.
In LBP scenarios and from pool detail view, it is cleaner to not allow the empty token select dropdown to be used in the swap clipboard.
Additionally, I've removed the already selected token from the dropdown list.
=> Only allow token select drop down with > 1 token

src/config.ts
This simple PR only intends to enables back the IBC operations for Lum Network, which is now operational after client update proposal.
=> Enable operations for Lum Network

src/config.ts
Stargaze is improving QoS for public endpoints but unfortunately needs a DNS change.
We confirmed these changes with a build preview https://aad93b15.osmosis-frontend-6za.pages.dev/assets
=> update stargaze endpoints

src/stores/root.ts
Adding Pool #15 XPRT/OSMO to the Trade page. Pool is onboarded for Osmosis incentives, has sufficient liquidity (>$10M), low swap fee (0.2%), and there's no reason to force unbeknownst users to trade through ATOM when there is plenty of OSMO liquidity paired with XPRT.
=> Add XPRT/OSMO Pool to Trade Page

src/stores/root.ts
Remove 562 LUNA/UST from Trade page, because it provide no value to traders.
This pool with Swap Fee 0.535% and liquidity less than OSMO/UST (0.2%) and OSMO/LUNA (0.2%), it will never be able to offer a better trade than a double hop. This liquidity is not serving Osmosis, rather draining rewards and needlessly costing novice users.
To be clear, the reason for this removal has nothing to do with trying to enforce OSMO as a middle currency.
Addresses the original concern of Issue #154 (now closed)
https://github.com/osmosis-labs/osmosis-frontend/issues/154
=> Remove 562 LUNA/UST from Trade page

src/config.ts
Add pool 617 (CHEQ/ATOM) to lockupAblePoolIds so users can bond to it.
Upgrade External incentive gauges for pool 602 (CHEQ/OSMO).
Reorder Pool 613 to be in numeric ascending order amongst the other externally incentivized pools.
=> Update Cheq external incentives and bonding

src/config.ts
Adding NETA coingecko id as per {"id":"neta","symbol":"neta","name":"NETA"} in [CoinGecko APIv3 List](https://api.coingecko.com/api/v3/coins/list), which goes to [NETA CoinGecko Page](https://www.coingecko.com/en/coins/neta)
=> Add NETA coingecko id

src/dialogs/Transfer.tsx, src/dialogs/manage-liquidity.tsx, src/hooks/account/useCustomBech32Address.ts
Closes: #71 
Currently in the frontend, IBC Withdraw functionality doesn't allow users to specify the counter-party chain account address. They are limited to the relevant chain account  in their Keplr wallet. For many users this needlessly results in them having to send and pay for another transaction to reach their desired account.
Provide an edit button to allow users to specify a valid bech32 address on the counter-party chain for withdrawal. Warn users about the risk of wrong addresses and exchange deposit addresses.
New dialog:
Editing:
Invalid address (disables withdraw button):
Warning message:
=> Allow users to specify custom withdraw address

src/config.ts, src/dialogs/Transfer.tsx, src/pages/assets/AssetBalancesList.tsx
There have been complaints from the community support DAO that users have missed the warning and have deposited and lost funds to a CEX address.
Change warning from tooltip to large and prominent text box below the address boxes.
=> Change custom withdraw warning from tooltip -> textbox

src/config.ts
Based off of the UMEE PR: https://github.com/osmosis-labs/osmosis-frontend/pull/279
GRAV ibc denom:
```
osmosisd query ibc-transfer denom-trace E97634A40119F1898989C2A23224ED83FDD0A57EA46B3A094E287288D1672B44
denom_trace:
base_denom: ugraviton
path: transfer/channel-144
```
GRAV/OSMO pool:
```
osmosisd query gamm pool 625
|
address: osmo1mxcjnczrsd9ge4pkczpt9e84rntk08h27ez0d36yaxumsk2smdys3vsucj
id: 625
pool_params:
swap_fee: "0.002000000000000000"
exit_fee: "0.000000000000000000"
smooth_weight_change_params: null
future_pool_governor: 24h
total_weight: "1000000.000000000000000000"
total_shares:
denom: gamm/pool/625
amount: "57110877535043979209663548"
pool_assets:
- |
token:
denom: ibc/E97634A40119F1898989C2A23224ED83FDD0A57EA46B3A094E287288D1672B44
amount: "3420530213496"
weight: …
```
=> Add GRAV external incentives

src/stores/root.ts
now that there is over 7.5 million in liquidity in this pool, it qualifies to be included in the Trade Router.
=> Add Pool 612 to Trade router

src/pages/main/components/TokenAmountInput.tsx
This is regarding issue [#240](https://github.com/osmosis-labs/osmosis-frontend/issues/240).
The swap amount has been limited to `MAX_SAFE_INTEGER` value which is 9007199254740991.
The app is not crashing anymore when inputting a very large number.
=> Limit swap amount

src/config.ts
The gas prices for Provenance are incorrect. The values have been updated.
=> Frontier - Update Provenance gas prices

src/config.ts
We are seeing `Request failed with status code 501` when depositing LIKE to Osmosis after upgrading our chain with sdk 0.44 and dual prefix support. Would this PR fix the issue?
=> Update LIKE config with new prefix and no-legacy-stdTx

src/config.ts
Add CRBRUS 662 External Incentives
Cerberus was re-added to main because it became incentivized, but only the asset and pool was added, and the incentive gauge was forgotten.
=> Add CRBRUS 662 External Incentives

src/config.ts
Add 547 bondable, since users cannot unbond from 547
fixes #457
=> Add 547 bondable

src/config.ts
remove the 'axl-' prefix. E.g., 'axl-USDC' -> 'USDC'
=> Frontier - Remove axelar erc20 prefixes

src/config.ts
Correct g-WETH logo, which looked like etheruem before, now it looks like weth. and coinGecko id, was etheruem before, now is weth.
=> Correct g-WETH logo and cgid

packages/stores/src/ui-config/manage-liquidity/add-liquidity.ts
There is a problem that the price impact of adding single asset lp is too much.
The cause of the problem was to manually convert the value to a percentage by multiplying it by 100 while using `RatePretty`.
`RatePretty` is a function recently added to @keplr-wallet/unit, and it shows the value as a percentage when showing it to the user through toString() even if it uses the value without converting to percentage. This helps to code management by separating value ​​to display to the users and value ​​for internal logic.
=> Remove the percentage multiplication to `singleAmountInPriceImpact`

packages/web/hooks/use-keplr/context.tsx, packages/web/stores/account-init-management.tsx
- Skip the selection of wallet type modal on mobile browser environment (there is no other way to connect wallet other than wallet connect)
- If user enters frontend from keplr app, force to init account immediately.
=> Improve the wallet connection process on mobile environment

packages/web/components/alert/frontier-banner.tsx, packages/web/components/buttons/button.tsx, packages/web/components/buttons/show-more.tsx, packages/web/components/cards/go-superfluid.tsx, packages/web/components/cards/pool-card.tsx, packages/web/components/complex/pool/create/step1-set-ratios.tsx, packages/web/components/complex/sidebar-bottom.tsx, packages/web/components/control/menu-dropdown.tsx, packages/web/components/control/pool-token-select.tsx, packages/web/components/control/sort-menu.tsx, packages/web/components/control/tab-box.tsx, packages/web/components/control/token-select.tsx, packages/web/components/input/input-box.tsx, packages/web/components/table/index.tsx, packages/web/components/trade-clipboard/index.tsx, packages/web/modals/base.tsx, packages/web/modals/lock-tokens.tsx, packages/web/modals/manage-liquidity.tsx, packages/web/styles/globals.css
We've received comments that some visually impaired users are having trouble navigating some of the clickable UI elements since release of refactor.
Use native HTML `button` elements to let clickable items be tab-able. This PR changes:
* Frontier banner
* Slippage settings dropdown
* Modal close button
* Pool token select, in create pool and add liquidity modals
* Tab box (in manage liquidity modal)
* Token select, and it's dropdown tokens
* Gauges in lock tokens modal
* All pool cards
* Sort menu and it's dropdown's sort items
* Table elements, only if they're clickable and not linkable (links are also tab-able)
=> Accessibility improvements

packages/web/config/chain-infos.ts
-now that the Trade page, Pools page, and other interfaces can display lower and upper case, we no longer need the dash between tokens like g-USDC -> gUSDC.
=> Remove dashes from GravityBridge tokens

packages/stores/src/price/pool.ts, packages/web/hooks/use-visibility-state/index.ts, packages/web/stores/index.tsx, packages/web/stores/root.ts
Most of the data depends on information from pools. Also, since prices change in real time, it is important to know the latest information of pools and prices.
The above two information should be refreshed periodically.
- Refresh when user views another tab and comes back to the frontend.
- If the user is viewing the frontend, it refreshes every 30 seconds.
- If the user is not viewing the frontend, it refreshes every 5 minutes.
=> Auto-refresh when user returns from viewing another browser tab #579

packages/stores/src/account/index.ts, packages/web/components/trade-clipboard/index.tsx
For user onboarding purposes, swap should be requested with 0 fee. Add what was missing during refactoring.
=> Request swap msg with 0 fee explicitly

src/config.ts
This PR registers a new channel and ibc Denomination of Saage Testnet
1. Denom of Saage chain
2. Bech32 prefix of Saage
3. Added TLS to RPC, and REST endpoint
4. New Channel for Saage<>Osmosis IBC transfer
=> Testnet - feat: adding asset and chain info for saage-testnet-5

packages/web/config/feature-flag.ts
- Removed expired gauge-ids
+ Added new 7 and 14 day unbond guage-ids
=> Update VDL external incentives gauge-id

packages/web/config/chain-infos.ts
Changes:
1. Added `gasPriceStep` field for the Kichain in `chain-configs` to fix unusable low fees in keplr. Kichain's recommended `minimum-gas-price` is 0.025uxki.
2. Added new features as Kichain has upgraded to include Cosmwasm v0.26.
=> Update default fees and add features for Kichain

packages/web/config/feature-flag.ts
Adds gauges to 
- pool 719 - https://www.mintscan.io/osmosis/txs/E5B6170A8E23F0EBEB612F307374B2D55AE0D559AB33489943F88EB90E5AAC62 -gaugeID - 4520
- pool 15 - https://www.mintscan.io/osmosis/txs/3195BED17E0C5E8B545FF1FFF68401A0F894849C297803E07F19B5266E2D5F62 - gaugeID - 4521
=> add xprt/usdc, xprt/osmo pool external incentives.

packages/web/config/ibc-assets.ts
because it doesn't rebase on Osmosis, so users don't get staking rewards. Hence, virtually pointless, and potentially confusing.
=> remove steth

packages/web/config/feature-flag.ts
Adds the new external incentives for pool #747 OSMO/ECH with gaugeID 4700, 7 day bonding period, starts 1657927785
=> Add External Incentive Gauge

packages/stores/src/ui-config/fake-fee-config.ts, packages/stores/types/ui-config/fake-fee-config.d.ts, packages/web/components/trade-clipboard/index.tsx, packages/web/hooks/ui-config/use-fake-fee-config.ts
Users can send tx with 0 fee because some validators allow to include the tx with 0 fee to the block.
However, these validators are becoming fewer and fewer. Therefore, 0 fee tx is processed slowly.
To decrease this problem, users who have OSMO pay a fee by default.
- Add `shouldZero` option to `FakeFeeConfig`
- On the trade clipboard, check the user's OSMO balance and send tx without fee if it is less than 0.001 OSMO.
- When not paying a fee, set `shouldZero` in `FakeFeeConfig`.
=> Set zero fee for the swap tx only if user doesn't have enough OSMO

packages/web/config/chain-infos.ts
xcDOT appears to come across to Osmosis as a 10 exponent token.
Sent 12.17 xcDOT from Moonbeam to Osmosis with 0.17 charge.
Shows in Mintscan as 120,000.000000, shows on frontier as 0 available (<$0.01)
Tested WGLMR and that does appear to use 18.
=> Update DOT Exponent

packages/web/config/ibc-assets.ts
Reverts osmosis-labs/osmosis-frontend#711
as per notice of Moonbeam being enabled again:
https://twitter.com/Axl_Satellite/status/1554467539333402625
=> Revert "disable DOT and WGLMR"

packages/web/config/feature-flag.ts
A new external incentive for TGD gauge was created as announced in https://twitter.com/TgradeFinance/status/1555479394147352576
=> Add TGD gauge to pool 769 (TGD/OSMO)

packages/web/config/ibc-assets.ts
Currently many users have to use Keplr to transfer EVMOS from osmosis, due to evmos app congestion.
Enabling the withdrawal option will be helpful to evmos users
> for deposits, users have other options in addition to the evmos app
=> Allow to withdraw EVMOS asset

packages/web/config/ibc-assets.ts
It appears Sifchain is experiencing an exploit, and is no longer producing blocks.
[Link to Telegram message](https://t.me/c/1430596792/14115)
[Mintscan](https://www.mintscan.io/sifchain)
=> Disable ROWAN transfers

.gitignore, packages/web/components/cards/pool-card.tsx, packages/web/components/complex/all-pools-table-set.tsx, packages/web/components/complex/external-incentivized-pools-table-set.tsx, packages/web/components/complex/sidebar-bottom.tsx, packages/web/components/layouts/main.tsx, packages/web/components/table/assets-table.tsx, packages/web/components/table/cells/transfer-button.tsx, packages/web/components/table/cells/types.ts, packages/web/components/table/index.tsx, packages/web/components/trade-clipboard/index.tsx, packages/web/config/index.ts, packages/web/config/user-analytics-v2.ts, packages/web/hooks/index.ts, packages/web/hooks/use-amplitude-analytics.ts, packages/web/hooks/use-keplr/context.tsx, packages/web/integrations/axelar/transfer.tsx, packages/web/modals/ibc-transfer.tsx, packages/web/package.json, packages/web/pages/_app.tsx, packages/web/pages/assets/index.tsx, packages/web/pages/index.tsx, packages/web/pages/pool/[id].tsx, packages/web/pages/pools/index.tsx, packages/web/stores/account-init-management.tsx, yarn.lock
We already are using Matomo for user analytics, but Josh and I recommend using Amplitude. It is scalable and has a lot of useful data analytics tools. Also, [It is highly secure and has a strict privacy policy.](https://amplitude.com/amplitude-security-and-privacy) Keplr Wallet is already using it. So Let's start with using both Matomo and Amplitude and eventually transitioning to Amplitude would be good.
=> Add user analytics events to use on Amplitude

packages/web/config/feature-flag.ts
Updating external incentives gauges for Cerberus $CRBRUS
Removing gauge for 1 day bonding period
Adding new gauge ID 29666 - 7 day bonding period - 360 epochs
Adding new gauge ID 29667 - 14 day bonding period - 360 epochs
=> Updating external incentives gauges for CRBRUS

packages/pools/src/weighted.ts, packages/pools/types/weighted.d.ts, packages/stores/src/account/index.ts, packages/stores/src/account/msg/make-msg.ts, packages/stores/src/account/msg/proto/generated/codecimpl.d.ts, packages/stores/src/account/msg/proto/generated/codecimpl.js, packages/stores/src/queries/pools/num-pools.ts, packages/stores/src/queries/pools/pool.ts, packages/stores/src/queries/pools/pools.ts, packages/stores/src/queries/pools/types.ts, packages/stores/types/account/msg/make-msg.d.ts, packages/stores/types/queries/pools/types.d.ts, packages/web/stores/root.ts
- Change camelCase to snake_case for gamm module (Ref: https://github.com/osmosis-labs/osmosis/pull/1656/files)
- Change the store prefix key for queries store. The cached value in indexed db possibly can make the crash because cached value is not snake_case. Thus, make sure to ignore the cached values by change the prefix key.
Currently, no testnet running well, so not yet tested.
=> Osmosis v12

packages/pools/src/weighted.ts, packages/pools/types/weighted.d.ts, packages/stores/src/account/index.ts, packages/stores/src/account/msg/make-msg.ts, packages/stores/src/account/msg/proto/generated/codecimpl.d.ts, packages/stores/src/account/msg/proto/generated/codecimpl.js, packages/stores/src/queries-external/pool-fees/index.ts, packages/stores/src/queries/pools/num-pools.ts, packages/stores/src/queries/pools/pool.ts, packages/stores/src/queries/pools/pools.ts, packages/stores/src/queries/pools/types.ts, packages/stores/types/account/msg/make-msg.d.ts, packages/stores/types/queries/pools/types.d.ts, packages/web/stores/root.ts
- These are the changes made by @Thunnini applied to the latest version of the frontend as of 09-29-2022
- ⚠️  This should not be merged until the frontend nodes are upgraded ⚠️
=> Osmosis v12 upgrade - frontend changes

packages/stores/src/queries-external/index.ts, packages/stores/src/queries-external/pool-fees/index.ts, packages/stores/src/queries-external/store.ts, packages/stores/types/queries-external/index.d.ts, packages/stores/types/queries-external/pool-fees/index.d.ts, packages/stores/types/queries-external/store.d.ts, packages/web/pages/pools/index.tsx, packages/web/stores/root.ts
Testing: you should be able to see in the frontier/main preview, it has the correct historical data for mainnet. For testnet preview, it has testnet data (I think it's returning all 0 right now).
=> Use testnet historical data (Imperator) API on testnet

packages/web/config/feature-flag.ts
https://www.mintscan.io/likecoin/proposals/57
We just renewed external incentive on LIKE/OSMOS(553) according to proposal, and gauge on LIKE/ATOM(555) would be removed
https://www.mintscan.io/osmosis/txs/A1B47107AB27423A94EC0CEA4B883EE69783ACEE294341874BD5E4C6AB55C6D7
=> Update gauge for likecoin pool 553 and 555 

packages/web/hooks/ui-config/index.ts, packages/web/hooks/ui-config/use-transfer-config.ts, packages/web/integrations/ethereum/metamask.ts, packages/web/integrations/ethereum/walletconnect.ts, packages/web/integrations/wallets.ts, packages/web/modals/connect-non-ibc-wallet.tsx, packages/web/pages/assets/index.tsx, packages/web/stores/assets/transfer-ui-config.ts
Filters the bridge integration wallet list from containing non-mobile supported wallets, and notifies the user that this asset is not selected:
Closes #883
Closes #867 
Later, may be able to enable mobile MetaMask (in the MetaMask mobile browser) if MetaMask mobile would let us send deeplinks to Keplr. See: https://github.com/MetaMask/metamask-mobile/issues/4615.
Or, perhaps we could use WalletConnect to deep link to MetaMask as described in issue 867.
=> Filter non-mobile-enabled wallets

packages/web/config/feature-flag.ts
As per Proposal 347 https://www.mintscan.io/osmosis/proposals/347 Will go live Epoch of 24th October.
=> Add Gravity Externals

packages/web/config/ibc-assets.ts, packages/web/integrations/axelar/source-chain-config.ts, packages/web/integrations/axelar/types.ts, packages/web/integrations/ethereum/types.ts
Update Ropsten to Goerli
Update sourceChain names list to those accepted by Axelar
Update Chainlist Networks list
Add Moonbase and USDC withdraw/deposit network
Add IS_TESTNET var for eth<>Axl network name mapping
Add contract address for USDC on other networks (not yet withdrawable)
Builds successfully, USDC deposit switches Metamask to correct network for Ethereum, Mooneam on Mainnet, and to Goerli and Moonbase on Testnet.
=> Fix axelar chain map, chainlist names, add usdc to moonbase

packages/web/pages/index.tsx
Allows use of stJUNO/JUNO and seJUNO/JUNO in the router by including pools with at least 10,000 JUNO present to be used.
=> Add Juno pairs to router

packages/pools/src/weighted.ts
`poolAssets` is defined as `WeightedPool.poolAssets` which is an array of objects. from the definition of [`Array.prototype.find()
` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), `.find` returns **undefined** if there is no matched element from the given array.
=> update hasPoolAsset return condition

packages/web/config/chain-infos.ts
As per title, this PRs updates the rpc and rest endpoints for testnet to:
https://rpc.testnet.osmosis.zone/
https://lcd.testnet.osmosis.zone/
=> Update rpc and rest testnet endpoints

packages/web/config/ibc-assets.ts
Axelar's axlWBNB (WBNB.axl) aught to be listed on the Main site since at least one of its pools (#840 OSMO/WBNB) will be incentivized, as decided by Osmosis Governance. ([see passing vote on Keplr](https://wallet.keplr.app/chains/osmosis/proposals/360))
Will come into effect November 20, as per the proposal text.
=> WBNB.axl to Main site

packages/web/components/input/search-box.tsx, packages/web/components/types.ts, packages/web/modals/token-select.tsx
Mostly for accessibility:
When swapping tokens, we can open a modal to select a new token in the token list. 
This modal has a search field, which should be focused right when the modal opens. 
This way, people can search for their tokens without clicking inside the input field.
=> add focus on search box when opening tokens select modal

packages/web/components/cards/bond-card.tsx
This happens on prod OSMO/STARS
=> Fix bond card (single pool view) content overflow when APR value is 3 digits

packages/math/src/pool/__tests__/stable.spec.ts, packages/math/src/pool/stable.ts, packages/math/types/pool/stable.d.ts
This PR implements relevant math/calc functions for stableswap. Specifically, it implements the following:
* `calcOutGivenIn`
* `calcInGivenOut`
* `calcSpotPrice`
* `solveCfmm`
To align precision bounds with our Go implementation, we also implement a wider precision decimal type for internal calculations
TODO:
* More calc tests
* Basic spot price tests
* BigDec implementation
* Precision issue fixes
=> Internal math for stableswap

packages/web/components/complex/add-liquidity.tsx, packages/web/localizations/dayjs-locale-es.js, packages/web/localizations/dayjs-locale-ko.js, packages/web/localizations/es.json, packages/web/modals/keplr-connection-selection.tsx, packages/web/pages/_app.tsx
Fix #1011 Non-localized stablecoin type
`add-liquidity.tsx`
* use collateral type to key into localization file
`dayjs-locale-es.js`
* update to Day.js locale object as detailed in [docs](https://day.js.org/docs/en/i18n/i18n)
`dayjs-locale-ko.js`
* same as above
`es.json`
* add stablecoin type translation
`_app.tsx`
* set locale object for day.js localization as detailed in [docs](https://day.js.org/docs/en/customization/customization)
Would like a sanity check that this is the way to go for the above solutions. If so, I can update all the localization json specific to day.js, but will need additional translations for stablecoin types to add to general localization files.
Could not replicate bug of "Unbonded" not being translated, although it's wrapping in certain languages.
=> Fix #1011 Non-localized stablecoin type

packages/web/config/ibc-assets.ts
Change CRBRUS to unstable since users are losing funds trying to IBC between chains (Cerberus chain needs to update their IBC client)
Unverified because CRBRUS no longer receives incentives.
=> Change CRBRUS to unstable, unverified

packages/web/config/ibc-assets.ts
Removing a couple more assets (NETA, BOOT) from Main due to disqualification.
=> Make NETA, BOOT unverified

packages/web/integrations/axelar/hooks/use-deposit-address.ts
https://github.com/osmosis-labs/osmosis-frontend/issues/968
When a users account is changed the axelar deposit address is regenerated for the new account.
=> Regenerates withdraw address when changed

packages/stores/src/ui-config/manage-liquidity/bond-liquidity.ts, packages/stores/types/ui-config/manage-liquidity/bond-liquidity.d.ts, packages/web/components/cards/bond-card.tsx, packages/web/modals/lock-tokens.tsx, packages/web/pages/pool/[id].tsx
* Users shouldn't be able to bond if there's no active gauges
* If a user has locked tokens, display the bond card even if gauges are expired to allow them to unlock
=> Pool Detail: Fix bond duration cards 

packages/web/integrations/axelar/source-chain-config.ts
Update Axelar's Ethereum Fees again
=> Update Axelar's Ethereum Fees

packages/web/config/chain-infos.ts, packages/web/config/ibc-assets.ts
src: channel-403, dst: channel-11
New IBC denom hash can be confirmed by using their transfer website: https://app.ech.network/ibc
SHA256("transfer/channel-403/aechelon") = ibc/47EE...177D
This will make the old denom unofficial. Users' old ECH tokens would then be unlisted in the Assets page (should we change it to "ECH (old)"?
Currently looks like this:
Getting odd behaviour from the token search:
Edit: The complexity of this seemingly simple change as blown up massively. It might be more easily possible if there were a way to change between channels (but still only seeing 1 version at a time). But at this point it is my recommendation to consider abandoning the idea of displaying 2 version at once, and simply ask users to view pools containing ECH to see, trade, and LP their …
=> Update ECH IBC Channels

packages/math/src/pool/stable.ts
Hi, formula was implemented a bit off. 
Previous implementation was like this:
```
const term1 = cubicCoeff.mul(xOut); // ax 
const term2 = quadraticCoeff.mul(xOut); //bx 
const term3 = linearCoeff.mul(xOut); // cx
const res = term1.add(term2).add(term3); // ax+bx+cx
``` 
But as commented above it calculates ax+bx+cx instead of ax^3+bx^2+cx
The fix can be like this as in this pr:
```
// ax^3 + bx^2 + cx 
const term1 = cubicCoeff.mul(xOut).mul(xOut).mul(xOut);
const term2 = quadraticCoeff.mul(xOut).mul(xOut);
const term3 = linearCoeff.mul(xOut);
const res = term1.add(term2).add(term3)
```
or like this similar to horners method
```
// horners method
// ax^3 + bx^2 + cx = x(c + x(b + ax))
let res = cubicCoeff.mul(xOut); // ax
res = res.add(quadraticCoeff).mul(xOut); // (ax+b)x
res = …
```
=> Bug fix in iterKCalculator

packages/web/config/chain-infos.ts, packages/web/config/ibc-assets.ts
Reverts osmosis-labs/osmosis-frontend#1135
Seems to have made IXO amounts disappear...
The currency registrar seems to have counterparty chain still as impacthub-3 instead of the new ixo-4
=> Revert "Fix IXO Chain ID"

packages/web/config/chain-infos.ts
- Hi, we just updated our $IBCX core contract address for our testnet launch (#1149).
- Future updates for our testnet deployments will not PRs; We'll just migrate them into this address. Thanks!
=> Update contract address for testnet $IBCX

packages/stores/src/ui-config/trade-token-in-config.ts, packages/web/components/trade-clipboard/index.tsx
* Initial tokens constructed with the trade token in config should only be used if they're both in sendable currencies
Areas to test:
* Selecting tokens in the swap tool, both on the swap page and in various pool detail pages (2 token, 3+token)
=> Fix token select in pool detail page

packages/web/config/chain-infos.ts
Reverting this change as Users have pointed out that their transactions are failing after this change. I did some testing, and whenever I use this new LCD endpoint, I get this error. 
1. Do more testing for the new LCD and pinpoint the error cause (note sequence mismatch error)
2. Open Bug Issue
=> Revert "V14 - Update LCD"

packages/web/pages/api/active-gauges.ts
Change /active-gauges/ api call to /gauges/.
Instead of returning 28k 'active' gauges (only past start times), /gauges/ returns 30.5k gauges.
An alternative would be to append a query for just the upcoming gauges, which is much shorter (I saw only 4 gauges when I checked, 3x (a 1-day, 7-day, and 14-day) for a new pool + one new superfluid gauge). I figured the alternative with 2 queries would be worse than 9% more gauges having to be filtered from a single query.
-file name 'active-gauges' becomes somewhat a misnomer now...
=> Update External Gauges Query

.github/workflows/push-docker-images.yaml, docker/Dockerfile, docker/Dockerfile.frontier, docker/Dockerfile.testnet
This PR fixes the errors related to the docker image build:
- It downgrades node to use `16.19.0` due to the following error when building:
```bash
#12 2.488 [2/4] Fetching packages...
#12 100.0 error @axelar-network/axelar-cgp-solidity@4.3.1: The engine "node" is incompatible with this module. Expected version ">=16 <17". Got "18.12.1"
#12 100.1 error Found incompatible module.
#12 100.1 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
- Fixes problems in the workflow when using the date in the image tag
=> Fix errors in docker CI

packages/stores/src/bridge-history/index.ts, packages/stores/src/bridge-history/types.ts, packages/web/components/table/transfer-history.tsx, packages/web/integrations/axelar/queries.ts, packages/web/integrations/axelar/transfer-status-source.ts, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Axelar changed its API schema: https://docs.axelarscan.io/cross-chain/transfers-status.
Notable changes: 
- `data.source` No longer exists. It's instead called `data.send`
- We must use `data.id`  instead. 
- Id includes the source chain. So to get the id, we have to: `data.id.split("_")[0]`
- insufficient_fee Is now located in `data.send`
=> fix: Bridge Transfer Status UI Instability

packages/web/config/chain-infos.ts, packages/web/config/ibc-assets.ts, packages/web/integrations/axelar/source-chain-config.ts
-bridged via Axelar
-there are native USDC variants--not already bridged variants.
-frontier for now, just below Ethereum USDC 
-I see no indication that the name is too long for any UI element, but cannot verify swaps without any pools (although, I don't think that will be an issue, either)
-QA Validation complete
=> Add polygon.USDC and avalanche.USDC

packages/web/pages/api/active-gauges.ts
Lowers the threshold of how many days in advance a gauge will appear from 7 days to just 1 day.
It would be nice to extend to show gauges upcoming several days in advance, but we'll need additional design to add start a date. For now, just 1 day in advance is the only way to not mislead people into thinking they'd get incentives at next epoch even when it wouldn't start for another week.
=> Reduce upcoming gauge days

packages/web/config/chain-infos.ts, packages/web/config/ibc-assets.ts
Re-enable IXO. now that the ibc connection is restored.
Updatechain id from impacthub-3 to ixo-4
https://www.mintscan.io/osmosis/proposals/412
Validated that transfers work.
=> Re-enable IXO

packages/stores/src/queries/fallback-query-store.ts, packages/stores/src/queries/pools/pools.ts, packages/stores/src/queries/pools/types.ts, packages/stores/src/queries/store.ts, packages/web/stores/root.ts, yarn.lock
This is an automated approach to switching to the slower pools query when the optimized query object fails to fetch. This should allow our frontend to still be usable without imperator (or other) data services. This only recently became a concern once a core and important query, the pools query, was moved to data services instead of directly from the node due to performance issues.
=> Fallback to node pools query if main query store fails

packages/web/config/ibc-assets.ts
Because they were on Main once before
=> Move IXO back to main

packages/web/integrations/axelar/transfer.tsx
When we started querying for the transfer fee, it broke the comparison of the input amount and the transfer fee that would block users from transferring if the amount wasn't greater then the fee that would be subtracted.
=> Hotfix: Axelar Transfer: Fix insufficient fee bug

packages/web/components/cards/bond-card.tsx, packages/web/modals/profile.tsx, packages/web/pages/pools/index.tsx, packages/web/utils/formatter.ts
Closes #1330 
Prevents text wrap, only allowing the following possibilities:
=> Fix: APR overflow

packages/web/components/drawers/token-select-drawer.tsx, packages/web/components/trade-clipboard/index.tsx, packages/web/modals/token-select.tsx
* Re-query pools in route when details are expanded (helps address #1274)
* Limit available balance to 8 decimals. Closes #1346 
* Only show swap route vis in home page, not in pool detail page
TODO
=> Swap tool fixes

packages/stores/src/derived-data/pool/bonding.ts, packages/stores/src/derived-data/pool/details.ts
* Check amount of shares instead of $ value of shares, since prices may not be available in some environments
=> v15: Hotfix: Use shares instead of value

packages/web/config/chain-infos.ts
to correct USDC.axl fromdisplaying Noble as the source chain. It must do a search for the symbol (assuming each symbol is unique)
Before:
After:
=> Update nUSDC symbol

packages/web/config/chain-infos.ts, packages/web/config/price.ts
to use pool 935 EBL/OSMO
and commented out where coinGeckoId: pool:<token> was undefined--for: hard, swp, usdx, muse, ctk
=> Update EBL pricing

packages/web/components/trade-clipboard/index.tsx, packages/web/modals/trade-tokens.tsx
When opening the trade tokens modal on any pool detail page without wallet connected, the modal now properly redirects to connect wallet modal. Previously, the connect wallets modal appeared behind the swap tool, and was not accessible.
=> fix: connecting wallet redirect in trade tool on pool detail page

packages/web/pages/index.tsx
100,000 REGEN
unlocks qREGEN, NCT, etc.
Confirmed, qREGEN found in Swap page
Note: the Console error about no pools found was already there and can be seen in production
=> Add REGEN to swap router

packages/web/config/ibc-assets.ts
Due to external incentive matching prop passing: https://www.mintscan.io/osmosis/proposals/480
Confirmed, WHALE appears on Main
=> WHALE to main

README.md
Hey there, we want to get you more contributors to your repository!
Therefore, I added a badge which lets users contribute to your translations.
The badge endpoint allows you to create a dynamic badge that display real-time data on your project. For instance, you can use it to showcase your project's localization progress or the number of errors/warnings on your Github repository. This means that whenever someone views the badge, they will see the most up-to-date information about your project.
We would be really happy if you decide to place this into your README to let people contribute to your translations 🥰
– Thank you,
Felix
=> add translation badge to README

packages/web/config/chain-infos.ts, packages/web/stores/root.ts
This pull request updates the Osmosis frontend from osmo-test-4 to osmo-test-5. The following changes were made:
Replaced references to osmo-test-4 with osmo-test-5 in the codebase.
These changes were necessary to ensure compatibility with the latest version of the Osmosis protocol. We are testing this changes on a new environment on vercel that will show up on this PR.
=> Change osmo-test-4 to osmo-test-5

packages/web/integrations/axelar/hooks/use-deposit-address.ts, packages/web/integrations/axelar/transfer.tsx
We had one more user report getting the wrong address. I'm using a different approach to get around the race condition in the Promise.then callback. I think if a user switched between un/wrapped at the right moment, that .then callback would contain the wrong data, and the wrong address would get set in state.
In this case, we use another `useDepositAddress` hook to manage the generation of the autowrap address with completely different state. Since it's separate state entirely, it should be more reliable.
Also, since it's separate state I re-enabled the toggle at the top for slightly better UX. They can't click transfer until the relevant deposit address is loaded.
@arispech please repeat the same tests for last weeks hotfix for transfers
For both deposit and withdraw:
* Test …
=> Hotfix: axelar native wrap deposit address

packages/math/src/big-dec.ts, packages/math/src/pool/__tests__/stable.spec.ts, packages/math/src/pool/concentrated/__tests__/math.spec.ts, packages/math/src/pool/concentrated/__tests__/quotes.spec.ts, packages/math/src/pool/concentrated/__tests__/tick.spec.ts, packages/math/src/pool/concentrated/const.ts, packages/math/src/pool/concentrated/math.ts, packages/math/src/pool/concentrated/quotes.ts, packages/math/src/pool/concentrated/tick.ts, packages/math/src/pool/concentrated/types.ts, packages/math/src/pool/stable.ts, packages/math/src/rounding.ts, packages/pools/src/concentrated.ts, packages/stores/src/queries/concentrated-liquidity/liquidity-net-in-direction.ts, packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
Inspired by the changes in these chain PRs, in order:
* https://github.com/osmosis-labs/osmosis/pull/4957 (first commit)
* https://github.com/osmosis-labs/osmosis/pull/5022 (second commit)
* https://github.com/osmosis-labs/osmosis/pull/5019 (no changes on frontend)
TODO:
=> (CL) simplify: remove exponentAtPriceOne param, rounding changes

packages/web/components/trade-clipboard/index.tsx
Use the swapping out currency instead of the in currency for calculating min out amount. Was displaying fine when the out currency had the same decimals as in currency, but was displaying improperly for out currencies with 18 decimals (ETH, EVMOS, etc.)
=> Hotfix: currency used in calc

README.md
I feel like an Asset Listings section should just link the user to the proper location and full docs on asset listings, but for now at least the reference is there now in the root level README
=> Update README.md with Asset Listings section

packages/web/components/cards/hero-card.tsx, packages/web/components/cards/icon-link.tsx, packages/web/pages/apps/index.tsx
Fixing the bugs I pushed 🙃 
The popup blocker was being triggered because we were essentially opening the cosmos eco form in two places, once via the link, and once via `window.open`. I had forgotten to remove `window.open` when a reviewer asked to have the button wrapped in an `<a>` tag. 
@jonator also removed the default export per your request
=> fix popup bug and height bug

packages/web/components/cards/app-display-card.tsx, packages/web/components/cards/hero-card.tsx, packages/web/pages/apps/index.tsx
The following PR addresses some issues with the thumbnails views on the apps page on multiple displays but focused mostly on sm and lg devices. 
Here is a summary of the changes made in the affected files:
**packages/web/components/cards/app-display-card.tsx:**
Updated the CSS styles for the card image, including background size, position, and repeat.
Adjusted the height of the card image container.
Modified the minimum height of the card's content container.
**packages/web/components/cards/hero-card.tsx:**
Modified the CSS styles for the hero image container, including background size, position, and repeat.
Adjusted the height of the hero image container for different screen sizes.
Added a gradient overlay to the hero image.
Adjusted the layout and spacing of the card's content. …
=>  Refactor card components and optimize app display layout for app page. 

packages/web/config/chain-infos.ts, packages/web/config/ibc-assets.ts, packages/web/config/price.ts
This change is required because Nolus testnet was re-initialized.
=> Update nolus testnet

packages/web/config/feature-flag.ts, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Removes Autonomy Banner which has been up for 4 days
=> Remove Autonomy Banner

packages/stores/src/account/__tests_e2e__/collect-rewards.spec.ts, packages/stores/src/account/index.ts, packages/stores/src/queries-external/README.md, packages/stores/src/queries-external/concentrated-liquidity/index.ts, packages/stores/src/queries-external/concentrated-liquidity/position-range.ts, packages/stores/src/queries-external/store.ts, packages/stores/src/queries/concentrated-liquidity/position-by-id.ts, packages/stores/src/queries/concentrated-liquidity/types.ts, packages/web/components/assets/icon.tsx, packages/web/components/buttons/chart-button.tsx, packages/web/components/cards/my-position/expanded.tsx, packages/web/components/cards/my-position/index.tsx, packages/web/components/cards/my-position/status.tsx, packages/web/components/chart/concentrated-liquidity-depth.tsx, packages/web/components/chart/token-pair-historical.tsx, packages/web/components/cl-deposit-input-group/index.tsx, packages/web/components/complex/add-conc-liquidity.tsx, packages/web/components/main-menu.tsx, packages/web/components/pixels/pallete.tsx, packages/web/components/pool-detail/concentrated.tsx, packages/web/localizations/en.json, packages/web/modals/increase-concentrated-liquidity.tsx, packages/web/modals/remove-concentrated-liquidity.tsx, packages/web/pages/apps/index.tsx, packages/web/pages/bootstrap/index.tsx, packages/web/public/icons/left-right-arrow.svg, packages/web/public/icons/sprite.svg
Improve and polish the my position card.
[ClickUp Task URL](https://app.clickup.com/t/863gxjv4v)
- Improves position component header, more closely matching Figma
- For assets in the expanded position view, if there's more than 2 they will be organized in a uniform 2x2 table, with the USD value in the 3rd column
- Add placeholder text if there are no assets, like no rewards
- Show current price in depth chart of pool overview
Visual testing
=> (CL) My pos cleanup

packages/stores/src/account/amino-converters.ts, packages/stores/src/account/base.ts
Fix the following bugs: 
[ClickUp Task URL](https://app.clickup.com/t/866ad98b0)
=> fix: Account Sequencing and Accurate IBC Transfer Amount

packages/math/src/pool/concentrated/math.ts, packages/math/src/pool/concentrated/tick.ts, packages/stores/README.md, packages/stores/src/account/__tests_e2e__/collect-rewards.spec.ts, packages/stores/src/account/__tests_e2e__/positions.spec.ts, packages/stores/src/account/index.ts, packages/stores/src/account/msg-opts.ts, packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts, packages/web/components/complex/my-positions-section.tsx, packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts, packages/web/modals/increase-concentrated-liquidity.tsx
Since we're no longer aggregating positions by price range and don't have charging periods, we should use the AddToPosition message instead of creating a new position with the same range. This is the functionality behind the increase liquidity modal.
[ClickUp Task URL](https://app.clickup.com/t/863gxjgk4)
- Adds the `MsgAddToPosition` message
- e2e tests
- Wires the message up to the increase liquidity modal
- Fixes for rounding to nearest tick
- Sorts position card list by join time
- E2e tests work
- Add to position increases the liquidity of a position
=> (CL) Migrate to increase liquidity message

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts, packages/web/modals/add-liquidity.tsx, packages/web/modals/increase-concentrated-liquidity.tsx
It seems **not** refreshing the depth chart after creating or increasing a position caused the charts to break in the expanded view for the new/changed position. 
https://app.clickup.com/t/86780cqt2?comment=90060018069050
https://app.clickup.com/t/86780cqt2?comment=90060018070654
- Refreshing depths when creating or adding to a position seemed to fix the charts. Note: I added the refresh logic in the "view" layer since we don't pass the poolId to the account layer since it's not needed there. It seems to make sense to add it in the view layer since our view happens to use the depth data. It's good the account layer doesn't make that assumption.
- For remove liquidity, I added the fix to the `jonator/remove-liquidity` branch since it's WIP
- Since we `useStore` in the `useUIConfig` hook, …
=> (CL) Depth chart data fixes

packages/web/components/alert/tx-event-toast.ts, packages/web/hooks/ui-config/use-lock-token-config.ts, packages/web/hooks/ui-config/use-remove-liquidity-config.ts, packages/web/hooks/ui-config/use-superfluid-pool.ts
- Fix the transaction window not opening after refreshing the page. This was caused by outdated callbacks given account was not included as a dep. 
- Use correct types for `prettifyTxError`
[ClickUp Task URL](https://app.clickup.com/t/866ad98b0)
=> fix: Transaction Not Popping Out and Correct Types for `prettifyTxError`

packages/stores/src/account/base.ts, packages/stores/src/account/utils.ts, packages/web/components/table/assets-table.tsx, packages/web/config/generate-chain-infos/source-chain-infos.ts
Currently, there is a bug in ibc-go-v7 (#1691), where transactions signed with 'signAmino' result in an error on chains such as Stride and Injective. PR intends to manage these errors by opting for 'signDirect' when required. However, it's important to note that the Cosmostation wallet doesn't support 'signDirect'. As a result, deposits to Injective and Stride have been disabled.
Please note that injective will not be disabled in the assets table since its deposit and withdrawal redirect to an external page.
[ClickUp Task URL](https://app.clickup.com/t/866agfwwq)
=> (MW) Use Direct Signing for Chains affected by ibc-go-v7

packages/web/stores/kv-store.ts
Adding as a hot fix since it's producing so many issues in Sentry.
In short, this wraps our KVStore implementation with a catch block that ignores a specific known error.
[ClickUp Task URL](https://app.clickup.com/t/862k0daaz) (sentry errors linked there)
- Looks for a specific error message on the `get` and `set` methods of the KVStore implementations used on our frontend. I would have preferred to use `e instance of InvalidStateError`, but I couldn't find where `InvalidStateError` is defined.
1. Open any fresh page
2. Clear cache in browser
3. Notice error message _does not_ appear in console
Cross examine the same workflow with app.osmosis.zone to ensure it _is_ being logged to the console there.
=> Hotfix: catch specific error from KV Store

packages/web/integrations/core-walletconnect/client.ts
Display WalletConnect QR code after disconnect so that users can change between devices if needed. 
[ClickUp Task URL](https://app.clickup.com/t/38nrqwm)
- Cleanup WalletConnect V2 pairings
=> feat: Clear Pairings on Disconnect

packages/stores/src/account/base.ts, packages/web/components/table/assets-table.tsx, packages/web/config/generate-chain-infos/source-chain-infos.ts
Remove the IBC V7 Hot Fix. This will re-enable the deposit button in the assets table for affected wallets like Ledger and WalletConnect. 
- Re-enable asset deposit button for Stride
- Remove error message for unsupported wallets.
=> fix: Remove IBC V7 Hot Fix

packages/stores/src/account/base.ts, packages/stores/src/account/cosmos/index.ts
This PR solves the unauthorized error users received when doing IBC transfers to chains like Gitopia. The issue lay in the `revision_number` being "0". If a chain lacks a version number, this value should be omitted from the transaction message, otherwise, it will fail.  
This PR also resolves an issue when transactions are executed before the `TxTracer`'s detection. To maintain accuracy, we'll now utilize the values from tx_result as needed.
- Use `tx_result` when needed if transaction is executed before being found by tracer.
- Remove revision from message if value is "0"
=> fix: Unauthorized Error While Signing some IBC Asset Transactions

package.json, packages/web/package.json, yarn.lock
Fixed the CLI lint error "no inlang config found". 
1. Add a `--config` parameter to the lint command. 
2. Update the inlang CLI (because why not).
=> fix inlang lint command

packages/web/config/ibc-assets.ts
This project seems to be dead. <$200 liquidity... There are an increasing number of pending IBC transfers out of Osmosis yet the project no longer has any relayers, and therefore the ability to deposit/withdraw should be disabled.
I haven't tested this change locally, but I looked at past PRs and this seems to be acceptable.
=> Arkh unstable - disable IBC from frontend

packages/stores/src/account/amino-converters.ts, packages/stores/src/account/utils.ts
This PR fixes the pool creation flow, and this message: 
The error pertains to a discrepancy between the amino and proto messages. The proto messages are incapable of incorporating decimal numbers because they are converted into a `BigInt` on the chain side. Considering our need for a decimal number in the amino message, we can still maintain the decimals in the `toAmino`. However, we need to adjust the `fromAmino` function. This function represents the body passed to the proto message and must accommodate a decimal format compatible with the proto buffer. 
To clarify our transaction signing process: we begin by obtaining the amino message object via the `toAmino` function, which is then signed using the wallet. This signed object is then transformed into a proto-compatible message using …
=> fix: Pool Creation Broadcast

packages/pools/src/concentrated.ts, packages/stores/src/ui-config/trade-token-in-config.ts
When calculating the display spot price for a CL pool, we messed up the in over out logic depending on the token being swapped in. This should fix the swap tool for CL pools.
=> fix: invert in over out spot price

packages/stores/src/account/osmosis/index.ts, packages/stores/src/account/utils.ts, packages/web/components/cards/my-position/expanded.tsx, packages/web/components/cards/my-position/index.tsx, packages/web/components/cards/my-position/status.tsx, packages/web/localizations/en.json
Show unstake status when a user is unstaking a position.
Stretch: auto refresh time and requery position status when position end time is reached.
Either migrate a staked gamm share position, or stake a full range position, then unstake and ensure status is updated.
=> Show unstake position status

packages/math/src/pool/concentrated/__tests__/quotes.spec.ts, packages/math/src/pool/concentrated/__tests__/tick.spec.ts, packages/math/src/pool/concentrated/one-for-zero.ts, packages/math/src/pool/concentrated/zero-for-one.ts
…
The issue I've experienced is not being unable to generate quotes due to a lack of precision.
Precision must be increased to 36 post-launch for quote generation to work correctly in all cases.
If liquidity is high enough here:
https://github.com/osmosis-labs/osmosis-frontend/blob/c7889f4e4186bdb5862abc9a0275aeb5f3d377d6/packages/math/src/pool/concentrated/math.ts#L145
It will divide `amountRemaining` all the way to zero, leaving the sqrt price with no update. That will lead to the new sqrt price being equal to the current sqrt price. As a result, we failed to calculate the quoted amount and swap.
- added a more descriptive error to all swap steps
- added a repro test
Covered by test
=> test/fix: more descriptive error message when failing quotes due to lack of precision

packages/stores/src/ui-config/decimal.ts, packages/stores/src/ui-config/index.ts, packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts, packages/web/components/complex/add-conc-liquidity.tsx, packages/web/modals/increase-concentrated-liquidity.tsx, packages/web/utils/formatter.ts
Use Dec to support larger direct price inputs. Note: it gets rounded to the nearest tick, so some values are not possible to directly input (especially larger prices). The original issue was likely caused by the Intl number formatter, so I created a way to get around that for Dec type. I use the IntPretty type to trim decimals still. Now all prices (even when rounded to ticks) are derived from raw user input, instead of being set as an action. You'll notice this when the input box is focused, the raw value is there but the derived value is displayed.
- Support large prices with Dec type
TODO
Enter large prices in both inputs.
=> Fix input price

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
Hard code tick spacing 1000.
https://app.clickup.com/t/860r9zaxq
To prevent excessive tick granularity on-chain, we hard code it to 1000 via frontend
Test in prod
=> hard code tick spacing 1000

packages/stores/src/account/__tests_e2e__/swap-exact-in-positions.spec.ts
Adding swap e2e tests in zero for one direction
Noticed that in zero for one direction, an edge case we special-cased on chain is hit frequently:
https://github.com/osmosis-labs/osmosis/blob/844c172f50cb602b6af030e1d7abbca28d2dbddc/x/concentrated-liquidity/swaps.go#L400-L403
However, this is not launch blocking and happens when swapping directly to tick only
https://app.clickup.com/t/860r9zvcv
- added zero for one tests (same as one for zero but other direction)
- small refactor to reduce code duplication
=> test(CL): e2e zero for one swap tests

packages/math/src/index.ts, packages/math/src/pool/concentrated/__tests__/math.spec.ts, packages/math/src/pool/concentrated/__tests__/quotes.spec.ts, packages/math/src/pool/concentrated/__tests__/tick.spec.ts, packages/math/src/pool/concentrated/const.ts, packages/math/src/pool/concentrated/math.ts, packages/math/src/pool/concentrated/one-for-zero.ts, packages/math/src/pool/concentrated/quotes.ts, packages/math/src/pool/concentrated/swap-strategy.ts, packages/math/src/pool/concentrated/tick.ts, packages/math/src/pool/concentrated/types.ts, packages/math/src/pool/concentrated/zero-for-one.ts, packages/math/src/utils.ts, packages/pools/src/concentrated.ts, packages/stores/src/account/__tests_e2e__/positions.spec.ts, packages/stores/src/account/__tests_e2e__/swap-exact-in-positions.spec.ts, packages/stores/src/account/osmosis/index.ts, packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts, packages/web/components/cards/my-position/index.tsx, packages/web/components/pool-detail/concentrated.tsx, packages/web/modals/remove-concentrated-liquidity.tsx
Updating precision to align closer with the chain for quote estimation. The goal is to avoid failing via frontend due to invalid slippage bound.
[ClickUp Task URL](https://app.clickup.com/t/860r9zvey)
- Changed Dec to BigDec where applicable to match chain
- Refactored dependencies
- Updated test vectors in `math` package
- Test vectors are taken directly from chain code
- Recalculated in Python manually where no chain test was found
- Ran all static tests
* Everything passed but `packages/web` . Unfortunately, I cannot build it to run for some reason. @jonator for awareness
=> refactor: CL math precision increase

packages/pools/src/concentrated.ts, packages/pools/src/errors.ts
Better error message to explain what's up with not giving enough tokens in
[ClickUp Task URL](https://app.clickup.com/t/862k3p20d)
- new error message similar to `NotEnoughLiquidity`
- Replace `NotEnoughLiquidity` with new error
- `Ran yarn test` in root
=> refactor: better error message when not enough quoted

packages/stores/src/account/osmosis/index.ts, packages/stores/src/account/osmosis/tx-response.ts, packages/web/stores/root.ts
After creating or adding to a position, refresh position metrics with the new position ID with a delay of 30s to wait for indexer to run.
- Import queries external store into account store (optional)
- Refresh position metrics 30s after tx fullfillment
Create or add to a position, notice API call 30s later (it will error due to env issues, if not using cl preview).
=> Refresh position metrics after creating or adding to position

packages/web/pages/_app.tsx
Adding the 'laptopOrLarger' flag to our Launch Darkly initialization. This should allow us to target whether or not a user is on mobile when LD initializes i.e. and hide certain features from mobile users.
- Add laptopOrLargerFlags
- bunch of linting fixes
=> update ld config to check for laptoporlarger

inlang.config.js
This PR is based on this issue: https://github.com/inlang/inlang/issues/1082
- Added ignore to inlang.config.js
- Should work with the new patch of the plugin
=> fix: inlang.config.js ignore `__tests__` folder

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
Switch moderate and aggressive strategy values. Moderate was being to aggressive by setting a tight range and aggressive too moderate by setting a bigger range. 
[ClickUp Task URL](https://app.clickup.com/t/863h750nh)
=> (CL) Fix Price Strategy

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts, packages/web/components/chart/token-pair-historical.tsx, packages/web/components/complex/add-conc-liquidity.tsx
- Set initial custom range when add liquidity modal mounts.
=> (CL) Set Initial Custom Range when Add Liquidity Modal Mounts

packages/stores/src/account/osmosis/types.ts
Prior to this PR, I would get out of gas issues when doing large swaps on edgenet.
For example, a swap crossing 160 ticks would fail. With this change, my manual e2e tests with large swap amounts work out.
There are too many variables to control with CL swaps. As a result, we should err on the side of caution and overestimate the gas amounts per crossed ticks.
For v17, there is already effort started to reduce gas amounts in swaps.
[ClickUp Task URL](https://app.clickup.com/t/860ratnbr)
- Manually tested swapping large amounts with significant price impact back and forth on edgenet
- Printed the number of crossed ticks. The max number observed was 160
=> fix: increase gas per crossed tick in swaps

packages/web/pages/assets/index.tsx
Includes account's position balances and all rewards in "Total assets" portion of assets page overview:
=> Include position assets in assets page total assets

inlang.config.js, package.json, yarn.lock
Make `inlang lint` command work again
**Note:** to always use the newest version change `inlang lint` to `npx @inlang/cli@latest lint` in the lint command.
- update @inlang/cli to newest version (^0.11.7" > ^0.13.3")
- update `inlang.config.js` with the newest version of `@inlang/plugin-standard-lint-rules@3`
=> Update `inlang.config.js` & `@inlang/cli` to fix lint command

packages/web/config/generate-chain-infos/source-chain-infos.ts
Composable's Chain Name was showing a Centauri, but they want it to show as 'Composable'.
-Update source-chain-config.ts centauri chain name
=> Update Composable Chain Name

packages/web/config/price.ts
The token CUB was missing a pricing config. Now it has a pool so we can price it.
Added pool 1072 to Cub price config (incorrectly configured to pool 1046, which doesn't have CUB)
=> Update CUB price

packages/web/config/ibc-assets.ts
(JP69) Disables HUAHUA Deposit and Withdraw links.
(JP69) Because the v500 upgrade removed the ibc transfer module from the module manager.
(JP69)-adds isUnstable to huahua in ibc-assets.ts
(JP69) validation after Vercel build....
Confirmed that transfers do not work anymore.
The build indeed disables the Deposit and Withdraw functions.
=> Disable Chihuahua deposit/withdraw button

packages/stores/src/currency-registrar/__tests__/unsafe-ibc.spec.ts, packages/stores/src/currency-registrar/unsafe-ibc.ts
From discussion with Jeremy and Sunny, we all agreed it would be more useful to display a slice of the IBC denom instead of "UNKNOWN" for the denom. This would at least make the UI usable when differentiating tokens.
=> show IBC denom instead of UNKNOWN

packages/stores/src/queries/pools/cfmm-cl-link.ts, packages/stores/src/queries/store.ts, packages/stores/src/queries/tendermint/node-info.ts
Falls back to pre v17 queries in the CFMM <> CL link query store if pre v17.
[ClickUp Task URL](https://app.clickup.com/t/863hazkth)
* I still use the new single links query store, but now check the node version and fall back to the old individual query stores as needed
Connect dev env to edgenet, which is on v17 dev env:
Change env to point to mainnet:
* You should be able to see now on stage that the old link queries are called. Remember, the 400s are expected since that's what's returned when a link doesn't exist for a give pool ID:
=> Fall back to pre v17 queries

packages/web/pages/index.tsx
Fixes he Low Res versions of the background image (the supercharged Wosmongton) had a broken reference (accidentally doubled the extension as: .png.png).
- removes '.png' from the double .png.png in the low res supercharged wosmo background image reference in /pages/index.tsx
=> Fix Background Image

packages/math/src/pool/stable.ts, packages/pools/src/router/__tests__/routes.spec.ts, packages/pools/src/router/routes.ts, packages/pools/src/stable.ts, packages/stores/src/ui-config/trade-token-in-config.ts, packages/web/pages/index.tsx
With stableswap pools, our math layer would throw a prototype error with `cannot input more than y reserve` as the message. This essentially meant that there was not enough liquidity in the pool for the given amount (confirmed with @AlpinYukseloglu ). 
Problem: that Error would bubble up and would not be handled by our routing and swap UI config layer. It was basically considered an unexpected error. Now, in our pools layer, we catch that specific prototype error and cast it into a `NotEnoughLiquidityError` so it can properly be handled in our router. 
The error would arise _repeatedly_ as our router was testing various splits into a route containing a stableswap pool.
UPDATE: the fix was we were letting some 0 liq stable pools (and CL pools) into the router. The fix was to remove those …
=> Fix: map y reserve error to `NotEnoughLiquidity` error

packages/web/config/ibc-assets.ts
-Fixes SEI withdraw link. Goes to TFM, but was in the wrong direction (Sei to Osmosis), now goes Osmosis to Sei
-Replaces the TFM withdraw URL overrides for SEI
=> Asset Integrations: Fix SEI Withdraw link

packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Remove `notifi.title` translation to fix CI.
=> feat: Remove `notifi.title` Translation Key

packages/web/components/navbar/index.tsx
Currently, the notification button is visible on mobile devices. If the user clicks on it, the app crashes. This PR Hides the notification button in the mobile nav bar according to the feature flag
=> hotfix: Mobile Notification Feature Flag

packages/web/config/ibc-assets.ts
- To make LUMEN of LumenX unstable (unable to Deposit and Withdraw) because the chain has been killed.
See the LumenX is now killed: https://github.com/cosmos/chain-registry/blob/8f2f39b28966f0913fa36c3d66a114ebbb53dca9/lumenx/chain.json#L4
- add isUnstable: true to lumen in ibc-assets.ts
=> Asset Integrations: LUMEN Unstable

packages/math/src/pool/concentrated/__tests__/tick.spec.ts, packages/math/src/pool/concentrated/tick.ts, packages/pools/src/concentrated/fetch-tick-data-provider.ts, packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
Currently, there is a bug in price to tick conversion when converting prices greater than 1. This PR refactors the conversion to make it simpler, and, as a result, fixes the bug. The 2 problematic cases are added as unit tests. This PR also fixes the logic for ramping the next tick bound to query by better handling pools with a negative current tick.
- Add test cases
- Refactor
- Fix tick ramping query logic
=> refactor: make price to tick clearer and fix bug

packages/stores/src/account/types.ts, packages/web/components/navbar/index.tsx, packages/web/config/wallet-registry.ts, packages/web/integrations/notifi/notifi-popover.tsx
In the upcoming updates, Osmosis will be introducing various wallet variations. However, not all these wallets have the features needed for certain services, such as notifications. To address this, we've included a `features` property in the wallet registry in this PR. This allows the frontend to determine which wallets have the essential capabilities for each service.
- Add features property
- Disable notifications for xDefi, and Leap.
=> feat: Add Wallet Features Array

packages/web/components/cards/my-position/expanded.tsx
Every position can be delegated to a new validator, so, the select validator modal should appear each time instead of defaulting to an existing SF staking validator.
[ClickUp Task URL](https://app.clickup.com/t/86a0jgc8g)
* Clicking go superfluid on a position should always open the select validator modal
=> fix: go sf should open select validator modal

packages/web/components/navbar/index.tsx, packages/web/hooks/use-feature-flags.ts
[ClickUp Task URL](https://app.clickup.com/t/86a0nk2ut)
- Add a feature flag to show/hide notifications on mobile phones
=> feat: Hide Notifications Based on Feature Flag on Mobile Phones

.vscode/osmosis-frontend.code-workspace, packages/stores/src/derived-data/pool/bonding.ts, packages/stores/src/derived-data/pool/share-pool-details.ts, packages/web/components/pool-detail/share.tsx
Fixes showing bond duration for superfluid pools, such as pool 1, if it's superfluid. Even if there are no internal gauges in that pool.
* Should be able to bond to superfluid pools, such as pool 1
* Should see external gauges, such as in pool 903. Should just see durations where there are incentives or un/bonded shares.
=> Superfluid share pool detail: fix bonding to longest duration

packages/web/integrations/notifi/notifi-context.tsx
Notification sign up failing with Leap wallet because of Leap's deterministic signature.
For Leap wallet to work we need to invoke signArbitrary with a string, not Uint8Array (Leap wallet team updated the built )
=> [Notifi] fix sing-up crash with Leap wallet

packages/stores/src/derived-data/pool/bonding.ts
For some reason it was working before, but I missed adding the check for the longest duration if superfluid enabled.
=> fix check for SF duration

packages/web/integrations/notifi/notifi-subscription-card/fetched-card/signup-view.tsx
`onClickVeirfy` function of signupView needs a catch clause to prevent the "Request rejected" error from bubbling to the error boundary when a user rejects the enable notifications signature popup
=> [Notifi] handle user reject enable notification

packages/web/hooks/use-feature-flags.ts, packages/web/pages/assets/[denom].tsx
[ClickUp Task URL](https://app.clickup.com/t/8669axbau)
You can access the page by navigating to `/assets/osmo`
=> [Token Info] Create Asset Page Behind Feature Flag

packages/web/components/complex/pool/create/index.ts
To update the hardcoded pool creation fee to 1000, as it was changed to after the upgrade.
[ClickUp Task URL](https://app.clickup.com/t/86a0rejp2)
update POOL_CREATION_FEE to "1000 OSMO"
=> fix: Update Pool Creation Fee to 1000 OSMO

packages/web/integrations/notifi/notifi-popover.tsx
Fix the issue that the Unread Count Badge prevents the mouse from hovering the bell icon button
=> [Notifi] fix unread count badge prevents hovering the bell button

packages/web/hooks/data/use-routable-pools.ts, packages/web/pages/index.tsx, packages/web/utils/background-routes/index.ts
In the `useRoutablePools` function, reactions were not being disposed of properly. As a result, each time the pools were refreshed, an additional reaction was created, which sent multiple messages to the worker. This led to a continuous infinite loop.
[ClickUp Task URL](https://app.clickup.com/t/86a0rkhne)
- Dispose of `reloadPoolsReaction` correctly to avoid a memory leak
- Use Events to propagate message responses to the background router
=> fix: Swap Tool Memory Leak 

packages/web/sentry.client.config.ts
Disabling sentry for now as we are not using it and we are overloading the /monitoring endpoint
[ClickUp Task URL](https://app.clickup.com/t/86a0txnrk)
Disabling sentry
=> disable sentry for now

packages/stores/src/ui-config/user-upgrades.ts
Superfluid exists on the new pools, migration should be available again: https://www.mintscan.io/osmosis/proposals/621
N/A
Reverted previous PR https://github.com/osmosis-labs/osmosis-frontend/pull/2121
This change has not been tested locally, just a reversion
Enables migration in 3 pools that was previously disabled.
=> Unskip migrations on previously broken Superfluid pools

packages/web/pages/stake/index.tsx
Adding a call to check if the user hasValsetPref, which is diff than existing delegations
[ClickUp Task URL](https://app.clickup.com/t/86a0twmkd)
- adds query for hasValsetPref to index page
=> add call to hasvalsetPref

packages/web/integrations/notifi/notifi-modal-context.tsx, packages/web/integrations/notifi/notifi-modal.tsx, packages/web/integrations/notifi/notifi-popover.tsx, packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx, packages/web/integrations/notifi/notifi-subscription-card/notifi-subscription-card.tsx
1. Support closing popover/ modal while clicking internal link
2. Related to the [comment](https://github.com/osmosis-labs/osmosis-frontend/pull/2035#discussion_r1322053181) in previous PR, refactor the card open effect.
=> [Notifi] Support closing notification popover/ modal while clicking internal link

packages/stores/src/queries-external/token-historical-chart/index.ts, packages/stores/src/queries-external/token-pair-historical-chart/types.ts, packages/stores/src/ui-config/asset-info-config.ts, packages/stores/src/ui-config/index.ts, packages/web/components/buttons/button.tsx, packages/web/components/chart/token-pair-historical.tsx, packages/web/components/navbar-osmo-price.tsx, packages/web/hooks/ui-config/index.ts, packages/web/hooks/ui-config/use-asset-info-config.ts, packages/web/package.json, packages/web/pages/assets/[denom].tsx, packages/web/tailwind.config.js, packages/web/utils/__tests__/number.ts, packages/web/utils/number.ts, yarn.lock
This PR adds the initial section for token chart. Due to a change in priorities, I won't proceed with the token info page at this time. Still, we should consider merging this update, as it incorporates a gradient design for token charts, which will also enhance the CL pools chart.
[ClickUp Task URL](https://app.clickup.com/t/86a0pv1q1)
- Add token info UI config
- Add Gradient to token pair chart
=> [Token Info] Add Token Chart Section

packages/pools/src/__tests__/concentrated.spec.ts, packages/pools/src/concentrated/fetch-tick-data-provider.ts, packages/pools/src/concentrated/pool.ts, packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
This PR addresses the data discrepancy in Imperator’s CL pool's current tick liquidity, which caused a negative fee error when referencing outdated ticks. The issue likely stemmed from a network delay. To ensure accuracy, we now retrieve the latest `currentLiquidity` data directly from the on-chain `liquidity_net_in_direction` query.
[ClickUp Task URL](https://app.clickup.com/t/86a0tz493)
- Use `currentLiqudity` from `liquidity_net_in_direction` query
=> fix: Negative Fee CL Error

packages/web/config/generate-chain-infos/source-chain-infos.ts
To fix that USDC.axl looks like it's from Quasar in the Swap page
[ClickUp Task URL](https://app.clickup.com/t/86a0vqfd4)
- Add quasar.- prefix to quasar ibc fee assets
=> fix: USDC.axl appearing as Quasar source

packages/web/config/wallet-registry.ts
Seems like  [Keplr mobile is not going to support signArbirary anytime soon](https://github.com/chainapsis/keplr-wallet/issues/664). 
We need to disable notification while connecting through Keplr mobile
=> [Notifi] Disable notification while connecting through Keplr mobile

packages/stores/src/queries-external/pools/pools.ts, packages/stores/src/queries-external/pools/types.ts, packages/web/pages/api/pools.ts, packages/web/pages/index.tsx, packages/web/pages/pool/[id].tsx, packages/web/queries/complex/pools.ts
Low liquidity pools aren't instantly accessible on the paginated pool query. This causes an unnecessary redirect to the `/pools` page after reloading since the pools aren't present during the initial request, and `poolExists` does fetch more data despite it being available. This PR fixes `poolExists` method by fetching pools as needed until the desired pool is found. 
[Assetlists PR](https://github.com/osmosis-labs/assetlists/pull/669/)
- Fetch pools in `poolExists` despite them not being available on first request
- Add skeleton loader to individual pools page, while `poolExists` is loading
=> fix: Consider Pagination When Retrieving Pools in `poolExists`

packages/web/etc/noop/README.md, packages/web/etc/noop/index.js, packages/web/etc/noop/package.json, packages/web/next.config.js
This performance boost is copied from Keplr!
Copied from my code comment:
```
// Replace libsodium with a no-op API. It is only imported from within cosmJS to support
// argon2i and ed25519, both functionalities which in the context of Cosmos would only get used within
// an extension wallet. Libsodium is ~190kb gzipped, 500kb parsed, so this meaningfully reduces client load.
// (And it gets bundled twice)
//
// It should never be getting used. This is copied from what Keplr does:
// https://github.com/chainapsis/keplr-wallet/blob/master/package.json#L103-L104
```
Thank you @JoseRFelix for the help with understanding how we use webpack vs turbopack, and @MaxMillington for discussions leading to this!
N/A
Lower bundle size by marking 
I have tested that yarn analyze no longer shows the …
=> Replace libsodium with a no-op functionality

packages/web/pages/api/pool/[id].ts
Individual get pool by id is failing because the API route is trying to get the id from search parameters instead of the pathname.
=> fix: Individual Pools Query

packages/web/next.config.js, packages/web/package.json, yarn.lock
```
// bip39 is only used in the context of extension wallet, so we can replace it.
// replacing it with a no-op breaks build, so we can at least replace it with a lighter weight version for now.
// ideally this becomes replaced with an API-compatible no-op.
```
Saves 70kb gzipped, 200kb parsed size.
We should just sanity check the FE works. I don't know of any reason why bip39 would get loaded. Its worth sanity checking that other languages don't break when you select them.
=> Replace bip39 with bip39-light

packages/stores/src/queries-external/pools/pool.ts
Removes some extra cloning of price pretty data overhead. Expected speedup to be a bit minor as we still have the same number of heap allocations going on.
From looking at profiles, it appears to me we are spending 200-350ms of JS execution time in this function.
Once #2188 is in, will try further speedups:
```
// TODO: Improve performance, to do so, we should in sequence try:
// - add a += op to Dec
// - Make priceStore.calculatePrice return something in the form of a Dec
// - Try changing the Dec usage to Number (float) in the codebase
// - Make a priceStore function to calculate result in float
```
In the meantime, I'm trying to see if theres a reliable way for me to unit benchmark the speed improvement, besides comparing manual chrome perf profiles.
=> Minor speedup to pool TVL logic

packages/web/pages/stake/index.tsx
The validators next step modal was accidentally removed, which breaks the flow. This puts it back in.
[ClickUp Task URL](https://app.clickup.com/t/86a0ym0xt)
Add next step modal
=> add validators next step modal back to the flow

package.json, packages/keplr-hooks/package.json, packages/keplr-stores/package.json, packages/keplr-stores/src/common/query/json-rpc.ts, packages/stores/package.json, packages/stores/src/currency-registrar/unsafe-ibc.ts, packages/web/package.json, packages/web/stores/assets/utils.ts, yarn.lock
This PR removes the import keplr-wallet/crypto, and by proxy crypto-js.
I anticipate this saving 50kb of parsed size, and 10kb off of the gzip. I cannot validate this right now, due to seemingly unrelated build issues.
=> Remove keplr-wallet/crypto and therefore crypto-JS import

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
If the user specifies a very tight range, the ticks could be the same. If they round to the same value, I add +/- padding of 1000 ticks to both min and max in the tick range.
* Added padding to min and max tick if rounded ticks are the same
If you select a super tight range, the add liquidity message should still succeed
=> CL: Prevent ticks from being the same

packages/web/config/price.ts
MANTA, YieldETH, ETH.wh and USDC.wh all had invalid pools which were recreated in https://www.mintscan.io/osmosis/proposals/623 This updates the price feed to use these new pools. Currently only Manta has no liquidity in.
=> Fix invalid Supercharged pool pricing

packages/pools/src/router/__tests__/routes.spec.ts, packages/pools/src/router/routes.ts, packages/stores/src/ui-config/trade-token-in-config.ts
Picks best swap; direct or split. Adds ordering to preferred pools to place transmuter pools first.
* Ordered preferred pools
* Find max out for direct & split routes
=> Router: remove force split, add ordered preferred pools

packages/web/hooks/data/use-routable-pools.ts
Seems the limit for routable pools' TVL was lowered, causing low liq pools to be chosen. This increases the limit and therefore increases the liquidity of chosen pools for routing.
USDC.axl > ATOM route should now be fixed and should be lower price impact.
=> Router: Increase necessary TVL of pools

packages/pools/src/router/routes.ts
The current status on the ATOM / USDCaxl bug:
- Noticed that route finder selects routes with 4 hops that get filtered out because # of tokenOutDenoms do not match the # of pools
* Reasons are still unclreas
- Realized that there are a bunch of pools with fewer hops
- However, the router greedily selects 4 (4 hop) routes that are buggy and get invalidated
The temporary solution is to allow  the router to search up to not 4 but 6 routes. As a result, we decrease the frequency of the bug happening in prod.
This was tested locally and fixed the ATOM / USDCaxl bug.
A proper solution to the mismatch between # of tokenOuteDenoms and # of pools is to be found in a subsequent change
=> fix: router is bricked due to invalidating long routes

packages/pools/src/router/routes.ts
Properly fixes the "no routes for this trade bug" (screenshot attached)
The problem stemmed from the fact that the router selected 4 4-hop routes where, for some of them, the number of token out denoms mismatched the number of pools, falling validation as a result.
In https://github.com/osmosis-labs/osmosis-frontend/pull/2242, we made a hotfix to increase the number of routes considered from 4 to 6. This allowed router to pick up routes with fewer hops and make routing work.
However, that fix is inappropriate and only decreases the frequency of the issue occurring.
It was observed that routes with fewer hops never had this mismatch. As a result, a guess was made that we somehow modify the shared inputs in the recursive function. In JavaScript arrays are pass-by-reference. As a result, if …
=> fix: proper fix for no routes for this trade bug

packages/math/src/pool/concentrated/__tests__/quotes.spec.ts, packages/math/src/pool/concentrated/one-for-zero.ts, packages/math/src/pool/concentrated/zero-for-one.ts, packages/pools/src/concentrated/pool.ts
This PR refactors logic for retrieving spot price before and after CL quotes.
It makes it easier to reason about and debug.
Additionally, it adds some checks in the swap strategy to make sure that the next sqrt price is located in the right direction relative to the current given swap strategy. This helps catching errors early.
=> refactor: stricter checks for spot price debugging in CL math

packages/web/components/navbar/index.tsx, packages/web/config/wallet-registry.ts, packages/web/modals/profile.tsx, packages/web/modals/wallet-select.tsx
This fixes some bugs introduced by breaking changes in the latest Cosmos Kit upgrade.
- Type error fix
- Change wallet image tag to `img` from Next's `Image` to support externally linked wallet images
- Fix Cosmos Kit breaking change fee setting
This change has been tested locally by rebuilding the website.
=> Cosmos Kit Upgrade type fix

packages/stores/src/ui-config/manage-liquidity/add-concentrated-liquidity.ts
Uses pool tick spacing param instead of 1000 for rounding the tick when a user is creating a position. This should allow users to make tighter positions with no issue.
I was told by @czarcas7ic that we no longer need to round to 1000th nearest tick, which was a concern at launch.
=> CL Add Liq: use pool tick spacing instead of 1000

packages/stores/src/ui-config/trade-token-in-config.ts, packages/web/utils/background-routes/index.ts
Currently, for some amounts our router completely breaks in the ATOM / USDC.axl pool.
This is because the quotes are not able to complete under 6 seconds.
This PR doubles the timeout to 12 seconds.
The bottleneck has been identified in performing too many iterations of the split routing search.
By decreasing it to 10, we will only perform 10 iterations per recursive call. This dropped quote latency from ~20 seconds to ~4 seconds on my machine for the problematic hand-picked amounts cases.
While this might decrease the router efficiency, it will help us stabilize it for the time-being. We can find the perfect split after we figure out a way to optimize the current recursive algorithm.
Tested locally in my environment
=> fix: double router timeout and decrease max split iterations to 10

packages/pools/src/router/routes.ts
Currently, we fail to skip direct quotes with low liquidity due to `Promise.all` never resolving. This stems from not being able to catch errors for individual quotes inside the map.
The solution is to add `await` inside the map logic so that we can handle any error from individual quotes and skip them silently.
Tested locally.
=> fix: failing to skip direct quotes with low liq

packages/pools/src/router/routes.ts
Prioritize shorter routes before filtering for unique routes. Shorter routes tend to have less fee and total price impact.
The way this works is it sorts by length before they get filtered for unique pools across routes. Then, longer routes will be filtered for uniqueness after shorter routes.
=> prioritize shorter routes

packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx
There was a minor interface change of notifi BE data yesterday. This causes the interface mis-match  with FE side.
Make fallback value to changed data interface.
=> [Notifi] transaction.hash not found issue

packages/web/components/pool-detail/share.tsx
On balancer pools, 24hr Trading Volume is shown first and Pool Liquidity next. It's vice-versa on CL pools.
This PR makes the display consistent among all pools with Pool Liquidity first and 24h Trading Volume next.
**Before:**
**After changes (testing on localhost):**
=> Update Pool liquidity-24h Volume display order

packages/web/components/complex/all-pools-table.tsx
Sort pools page by volume instead of liquidity
=> Order pools page by volume instead of liquidity

packages/web/integrations/notifi/notifi-subscription-card/fetched-card/history-rows.tsx
The data filed `denomMetadata` is simplified to `denomFormatted`.
We need to add as fallback to `denomFormatted`
=> [Notifi] denomMetadata.display not found issue

packages/web/config/generate-chain-infos/source-chain-infos.ts, packages/web/config/price.ts
To fix the price of IBCX token, which on most pages wasn't working.
- update IBCX pool price to use 1042 instead of 1022
It suddenly started working as soon as I added the CoinGeckoId property to the testnet IBCX.
=> bug: Fix IBCX Price

packages/web/config/generate-chain-infos/source-chain-infos.ts
To fix a bug that showed rATOM as a Realio token instead of just a StafiHub token
- remove rATOM under Realio in source-chain-config (and was already still under StafiHub)
=> bug: Fix rATOM Chain Placement

packages/web/components/table/assets-table-v1.tsx, packages/web/components/table/assets-table-v2.tsx, packages/web/components/table/cells/types.ts, packages/web/config/initial-assets-sort.ts
I know assets v2 is coming out, but I think this is a nice win in the interrim. (It currently makes the assets page low utility for me as a user). Currently putting 0 balance osmosis native assets to the top prevents a lot of utility for me.
This PR:
- Reduces some code duplication in constructing the TableCell object
- Changes FiatValueRaw from a string to a Decimal
- Removes `isCw20` from native asset (seems like a leftover bug that it was there)
- Removes sorting 0 balance native assets to the top. Right now it puts them at the bottom which isn't ideal, but I think significantly better than now. Should get unified with however else we determine default asset sorting.
=> Make assets table no longer sort 0-balance native assets to top

packages/web/modals/base.tsx
=> fix: Handle Modal Overflow

packages/web/integrations/nomic/transfer.tsx
Fixes an issue where the incorrect denom was selected when the user tried to withdraw nBTC without having an nBTC balance. h/t @kamal-sutra
=> Prevent trying to withdraw nBTC with a zero balance

packages/web/components/complex/pool/create/index.ts
Reduced pool creation warning to 400 OSMO as per https://www.mintscan.io/osmosis/proposals/669
N/A
Reduced pool creation warning to 400 OSMO as per https://www.mintscan.io/osmosis/proposals/669
This change has not been tested locally, identical in scope to previous change https://github.com/osmosis-labs/osmosis-frontend/commit/f3ba19377e508ed292b9557cbf516f227b715bb4
Does this pull request introduce a new feature or user-facing behavior changes? (yes)
- How is the feature or change documented? Will be updated in main docs
=> Update Pool Creation fee

packages/web/components/cards/bond-card.tsx, packages/web/components/complex/all-pools-table.tsx
This temporarily increases the barrier to showing the warning for high APR pools, when a number of our pools are accurately having high APRs due to swap volumes.  Will revisit once changes in #product-osmo-incentives is complete
=> Increase apr amount to show warning for

packages/web/.env, packages/web/config/asset-list/generate-asset-lists.ts, packages/web/config/env.ts, packages/web/config/ibc-overrides.ts, packages/web/server/queries/github/index.ts, packages/web/server/queries/github/query-latest-commit-hash.ts
Use commit hash to generate asset lists to avoid waiting for GitHub's CDN to refresh its cache.
=> feat: Use Commit Hash to Generate Asset Lists

packages/web/config/ibc-overrides.ts
Asset list changed `Bonk` symbol. This broke our build because it failed to pass the verification for IBC overrides available assets.
=> fix: Stage Build (Asset Mismatch)

packages/web/components/cards/my-position/index.tsx
Updates for latest figma files, lowers vertical spacing to 20px from 32
=> Lower vertical spacing of pool positions

packages/web/config/price.ts
To fix the pricing for QWOYN. The last PR to define its price was not validated. It was configured to look for osmo as the destCoin, when it's really in a USDC.axl pool.
They also made a new pool 1295
- update qwoyn in price.ts to have dest coin of usdc.axl instead of OSMO, and switched from 1291 to 1295
=> fix: $QWOYN Price

packages/web/config/ibc-overrides.ts
The integrated Axelar bridging is incorrectly associated with Neutron wstETH instead of wstETH.axl ever since changing to Neutron's for the canonical wstETH. As a result, transfers of these assets don't work anymore.
- update wstETH to "wsteth.axl" in ibc-overrides.
=> fix: wstETH transfer

packages/web/components/pool-detail/concentrated.tsx
Open the CL create position modal with the `open_create_position` query parameter. URLs will look like the following: `https://app.osmosis.zone/pool/1267?open_create_position=true`.
=> feat: Open Create Position When Query Param is Present

packages/web/config/asset-list/__tests__/asset-lists.ts, packages/web/config/asset-list/utils.ts
Match our explorer URL with the previous chain info URL syntax by removing the dollar sign coming from the chain registry.
=> fix: Remove Dollar Sign from Explorer URL

packages/stores/src/queries-external/coingecko-coin-infos/index.ts, packages/web/components/token-details/token-details.tsx
added markecap fallback inside details page.
=> feat: Add market cap fallback for details page

packages/pools/src/router/routes.ts
Transmuter is currently not being picked up in the router:
https://app.osmosis.zone/?from=USDC.axl&to=USDC
The bug stems from the fact that we change the order of pools with the `unshift` call while validating preferred pools. As a result, all the preferred pools end up getting reversed in terms of the order. Eventually, due to the max split parameter, tranmsuter ends up being filtered out.
The solution is to maintain two arrays:
1. Preferred pool array that maintains the original order where transmuter is most preferred
2. Non-preferred pools
Then, merge the two arrays into 1 while preserving the order.
Tested locally.
=> fix: transmuter is not being picked up in router

packages/proto-codecs/scripts/get-proto.sh
Previously the script would immediately try to checkout after a sparse clone. I believe if the checkout was a tag that didn't include changes in the sparse cloned files, it would not be found. Now, I fetch all refs (including tags) before checkout.
Also, I removed the git pull/fetch if the repos already exist since they all get deleted anyways in the beginning of the script. Since it only takes around 60s I think it's safer to clone every time.
=> Fix generate protos: fetch tags after sparse clone

packages/web/components/drawers/token-select-drawer.tsx, packages/web/hooks/input/use-amount-input.ts
I haven't been able to replicate, but I added an extra check to make sure the asset exists before showing activate unverified assets modal in swap drawer.
=> Prevent showing unverified modal

packages/web/components/drawers/token-select-drawer.tsx, packages/web/hooks/use-swap.ts, packages/web/server/api/edge-routers/assets.ts, packages/web/server/queries/complex/assets/index.ts, packages/web/utils/trpc.ts
The initial attempt to select a recommended asset like USDT was broken because the asset was not available in the assets array during the first fetch. To resolve this, we now also include a search for the asset within the recommended assets array.
=> fix: Select Recommended Assets

packages/web/hooks/use-feature-flags.ts, packages/web/hooks/use-swap.ts
In case anything goes wrong with other routers, we can have kill switches for other routers besides sidecar.
[TFM FF](https://app.launchdarkly.com/default/test/features/tfm-router/targeting)
[Legacy FF](https://app.launchdarkly.com/default/test/features/legacy-router/targeting)
=> Add TFM and legacy router feature flags

packages/utils/src/api-client.ts, packages/web/components/drawers/token-select-drawer.tsx, packages/web/components/swap-tool/index.tsx, packages/web/hooks/data/data-filter.ts, packages/web/pages/assets/[denom].tsx, packages/web/server/queries/complex/assets/__tests__/assets.spec.ts, packages/web/server/queries/complex/assets/index.ts
[ClickUp Task URL](https://app.clickup.com/t/86a1g2bb3)
=> feat: Make Asset Search Less Fuzzy and Remove Skeleton for Swap Details 

packages/pools/src/router/routes.ts, packages/pools/src/router/types.ts, packages/web/components/swap-tool/index.tsx, packages/web/hooks/use-swap.ts, packages/web/integrations/sidecar/router.ts, packages/web/integrations/tfm/router.ts, packages/web/modals/trade-tokens.tsx, packages/web/pages/pool/[id].tsx, packages/web/server/api/edge-routers/swap-router.ts, packages/web/server/queries/complex/route-token-out-given-in.ts
Restores the prior functionality of the trade tokens modal on the pool detail page of forcing a swap through the pool the user is viewing instead of finding the optimal route through all pools.
[ClickUp Task URL](https://app.clickup.com/t/86a1mq7j8)
* Add `forcePoolId` to router interface
* Implement above in sidecar and legacy routers, for TFM, it returns 0 as out amount since their API does not support this
* Add above as parameter to query in pool detail page swap modal
* Hide route visualization if in modal
* All pool detail pages should force a swap through that page's pool
* The route visualization should be hidden on pool detail page trade token modals
=> Force swap in pool in pool detail page

packages/web/config/feature-flag.ts
With CCTP launching and USDC liquidity overtaking USDC.axl on Osmosis we should switch this recommended asset to USDC via Noble.
N/A
Changes USDC.axl on swap page to USDC
This change has not been tested locally
- Does this pull request introduce a new feature or user-facing behavior changes? Yes
- How is the feature or change documented? (not documented)
No documentation for changing highlighted swap assets.
=> Switch USDC.axl to USDC on Swap widget

packages/web/components/token-details/token-details.tsx
Add target blank for social link inside token details page.
=> Feat: add target blank for external links

packages/web/server/api/edge-routers/assets.ts
If the `getAssets` tRPC function is given a user address, it tries to calculate the fiat value of the users balance. But, if it's a new token and the price config is not there yet, it will throw an error. Instead, let's silently fail and return undefined for the fiat value.
=> Fix: `getAssets` tRPC: catch user asset value calculation

packages/web/config/feature-flag.ts, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Adds an Announcement banner for the $Namada launch claim.
Which reads: "Osmosis users may be eligible for the Namada launch claim."
link: [Check your $NAM eligibility here!] (https://rpgfdrop.namada.net/)
with 12 translations
Adds the description and link text to 12 localization files.
Activates the banner in config/feature-flag.ts
=> Announcement Banner: Namada

packages/web/components/input/input-box.tsx, packages/web/modals/bridge-transfer-v2.tsx
[Only Track Transfer When ETH TX is Successful](https://app.clickup.com/t/86a1np0h7)
[Do not Select Whole Input on Click](https://app.clickup.com/t/86a1nwern)
=> feat: Only Track Transfer When ETH TX is Successful and Do not Select Whole Input on Click

packages/web/components/navbar/index.tsx, packages/web/modals/external-links-modal.tsx, packages/web/pages/_app.tsx
Currently, Leaving Osmosis Modal has a 'don't show again' checkbox that allows users to opt out of seeing the modal every time they click on an external website (e.g. Levana or Mars)
We still want this, except the user should be able to opt for the 'Leaving Osmosis' modal.
[ClickUp Task URL](https://app.clickup.com/t/86a1p9x8e)
=> feat: Remember Leaving Osmosis Modal Per Site

packages/web/server/api/edge-routers/assets.ts
I forgot that I added a param that's required to specify the fiat value sort, instead of always sorting by default. This is because with the assets info procedure (to be used with new assets table) I want to be able to specify the sort direction and whether I want it sorted in first place.
=> Fix sort fiat value descending

packages/web/integrations/notifi/notifi-subscription-card/fetched-card/fetched-card.tsx, packages/web/integrations/notifi/notifi-subscription-card/notifi-subscription-card.tsx
We found the issue that the login process will be blocked until the users refresh the dapp if the jwt token in browser is expired. 
This only happens when the users have not login visit dapp for long (> two weeks). 
This PR is to fix the issue above.
=> [Notifi V5.1] fix jwt expiry login issue

packages/web/integrations/tfm/router.ts, packages/web/server/api/edge-routers/swap-router.ts
Use our own `getAssetPrice` function to calculate the difference in price resulted from TFM's router.
=> (TFM Router) Calculate price impact for TFM

packages/web/components/animation/bridge/index.tsx, packages/web/components/complex/bridge-from-to-network.tsx, packages/web/components/complex/transfer.tsx, packages/web/components/control/token-select.tsx, packages/web/integrations/axelar/transfer.tsx, packages/web/integrations/ethereum/hooks/use-amount-config.ts, packages/web/integrations/ethereum/hooks/use-erc20-balance.ts, packages/web/integrations/ethereum/hooks/use-native-balance.ts, packages/web/integrations/ethereum/hooks/use-tx-gas-estimate.ts, packages/web/integrations/ethereum/use-tx-receipt-state.ts, packages/web/integrations/nomic/transfer.tsx, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json, packages/web/modals/bridge-transfer-v2.tsx, packages/web/modals/pre-transfer.tsx, packages/web/pages/assets/index.tsx
For mobile users who cannot use Metamask, provide an option to manually enter their wallet address, enabling them to transfer assets directly to this address.
[ClickUp Task URL](https://app.clickup.com/t/86a1g2bf8)
=> fix: Withdraw UI on Mobile

packages/stores/src/derived-data/pool/concentrated.ts, packages/web/components/cards/apr-breakdown.tsx, packages/web/components/pool-detail/concentrated.tsx, packages/web/components/table/cells/apr-breakdown.tsx, packages/web/pages/pools.tsx
* Add numa's APR breakdown to CL pool detail page
* Use numa's totalAPR in the pool cards for CL pools, instead of imperators 7d swap fee APR
=> CL: add APR breakdown to pool detail page

packages/web/config/asset-list/utils.ts
Currently our build excessively logs missing currencies in our asset list, which is expected to be common and is not fatal to our app.
=> Silence Keplr compatible chain error

packages/stores/src/currency-registrar/unsafe-ibc.ts, packages/types/src/asset-types.ts, packages/utils/src/asset-utils.ts, packages/web/modals/wallet-select.tsx, packages/web/stores/assets/assets-store.ts
Previously, we considered an empty `traces` array a native Osmosis token. Unfortunately, there will be assets that are native to Osmosis and also have a trace like `liquid-stake`. This PR finds the last ibc denom instead of assuming it's the last entry.
[ClickUp Task URL](https://app.clickup.com/t/86a1raryg)
=> fix: Assets That do not Have an IBC Trace

packages/web/components/navbar-osmo-price.tsx, packages/web/server/api/edge-routers/assets-router.ts
* Use tRPC for getting OSMO currency, asset info (price change) and historical price data. This allows us to leverage fine-grained caching on the edge functions thereby reducing direct data queries.
* Remove/reduce dependency on current chain, price, and queries stores
* Remove adding buy OSMO clicked metadata to amplitude, as we currently aren't querying that [event](https://app.amplitude.com/data/osmosis-zone/Osmosis%20%F0%9F%A7%AA/events/main/latest/Sidebar%3A%20Buy%20OSMO%20clicked?view=All&tab=USED%2520BY&propertyValidityFilter=All%2520Properties). We can re-add metadata if we want in the future, at a time where our tRPC query infra is more mature.
=> Use tRPC for sidebar OSMO asset price data

packages/web/components/complex/pool/create/index.ts
Adjusts pool creation fee warning to 100 USDC
According to https://www.mintscan.io/osmosis/proposals/699
N/A
Adjusts pool creation fee warning to 100 USDC
This change has not been tested locally
=> Update Pool Creation Fee to 100 USDC

packages/web/components/complex/paginated-table.tsx, packages/web/utils/openTab.ts
A cosmwasm pool in a pool row, it should open in a new tab since they link to Celatone
[Cosmwasm pools in pool row should open in new tab](https://github.com/osmosis-labs/osmosis-frontend/issues/2564)
Added the target in Nextjs Link component
closes: https://github.com/osmosis-labs/osmosis-frontend/issues/2564
=> Cosmwasm pools in pool row should open in new tab

packages/web/components/cards/apr-breakdown.tsx, packages/web/components/pool-detail/concentrated.tsx, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Numia includes superfluid APRs in the total APR. Was added shortly after release of our UI. This includes superfluid staking returns in the breakdown.
=> Include superfluid in APR breakdown

packages/web/config/ibc-overrides.ts
Update Picasso Deposit/Withdraw URLs since the old ones go to 404 now. Updated for PICA, KSM and DOT, all of which use the Trustless app.
Validation Successful
=> fix: Update Picasso Deposit/Withdraw URLs

packages/web/server/api/__tests__/utils.spec.ts, packages/web/server/api/utils.ts, packages/web/server/queries/complex/assets/index.ts, packages/web/utils/__tests__/search.spec.ts
I missed a test case for cursor pagination for when the list of items is less then the length of a single page. I added a test to handle that case, and this allows a list filtered to one item (i.e. "dydx" in the issue) to appear with a useInfiniteQuery hook.
[ClickUp Task URL](https://app.clickup.com/t/86a1t4yn4)
* Fix returning single page of items that is less in length vs single page size
* Add test case for this
* Add basic tests for search
* As seen in the bug task linked above, you should now be able to search dydx and see just dydx as a result.
=> Fix pagination + search

packages/web/components/navbar/index.tsx
If the link text is not translated, the FE displays the default "Click here to learn more". This PR will display the property regardless of its translation.
=> fix: Link Text When It's Not Translated

packages/web/server/api/__tests__/pagination.spec.ts, packages/web/server/api/edge-routers/assets-router.ts, packages/web/server/api/pagination.ts
This is in prep for assets table.
Currently, each time the next page of a list is requested by useInfiniteQuery, the entire list of items is refetched. Often, this isn't bad as usually that underlying data is pulled from the cache. But, in the case of user balances of assets, each requested page triggers a balances query.
These changes wrap the list of items in a cache, and invalidate that list of items if any of the input changes or the cursor is reset to 0. With useInfiniteQuery, the cursor will be set to 0 when the query is invalidated.
This allows us to cache user balances while paginating.
[ClickUp Task URL](https://app.clickup.com/t/86a0vf1e7)
* Add `maybeCachePaginatedItems`
* Rename utils to pagination
* Should notice slight perf improvements to swap tool drawer scrolling …
=> Add cached cursor-based pagination

packages/web/modals/validator-next-step.tsx, packages/web/pages/stake.tsx
"link" should point to stake learn more modal
[ClickUp Task URL](https://app.clickup.com/t/86a1qpbpz)
- convert to unstyled button, link up to stake learn more modal
https://github.com/osmosis-labs/osmosis-frontend/assets/30577966/efff2ffa-f3cd-42ec-b9b7-a99c910b5a3d
=> Add stake learn more modal via button

packages/web/components/your-balance/your-balance.tsx
fixed buy button now it's hide on disconnected wallet state.
on the token detail page, on stage, if you go to OSMO and click on "Buy OSMO" with the wallet disconnected, a black screen appears, this is because the component doesn't work without having a wallet connected, which is why the button is now hidden.
=> Fix: hide buy button

packages/web/components/table/asset-info.tsx, packages/web/hooks/use-show-unlisted-assets.ts, packages/web/hooks/use-swap.ts, packages/web/server/api/edge-routers/assets-router.ts, packages/web/server/queries/complex/assets/index.ts, packages/web/server/queries/complex/assets/user.ts
Assets that don't have a keyword should still be visible when the 'unverified assets' flag is activated because they are not unlisted, and also not verified.
Users who enable the 'unlisted asset preference' should be able to view these assets in both the swap tool and the asset table.
From a technical standpoint, we will introduce a new filter to the map trpc queries, specifically `getAssets` and `getAssetInfos`. However, we won't apply this filter to `getAsset` or `getAssetInfo`, as these more detailed queries are not directly visible to users unless they specifically choose the asset. Thus, it's acceptable to always retrieve unlisted assets for these queries. This approach ensures backward compatibility with other modules, like swap.
[ClickUp Task …
=> fix: No Keyword Assets and Get Unlisted Assets from TRPC

packages/web/pages/pool/[id].tsx, packages/web/server/api/edge-routers/assets-router.ts, packages/web/server/api/edge-routers/swap-router.ts, packages/web/server/queries/complex/assets/__tests__/assets.spec.ts, packages/web/server/queries/complex/assets/index.ts, packages/web/server/queries/complex/assets/price.ts, packages/web/server/queries/complex/assets/user.ts, packages/web/server/queries/complex/pools/index.ts, packages/web/server/queries/complex/pools/providers/imperator.ts
We found when getting the testnet to work, our tRPC procedures failed too silently, often with no message. I think throwing and bubbling exceptions is a great way to surface the root cause of issues, and helps us save time from having to step-through debug.
Going forward, our strategy with tRPC complex functions is to throw early and often. Then, we can catch these errors with `catch()` calls at the procedure level, or let it bubble up to the browser console, where the error and call stack can be read. This should not greatly affect end-user UX, as they should not see their browser crash, but ideally they'd see an error UI or at least no UI for the desired data.
[ClickUp Task URL](https://app.clickup.com/t/86a1z26fp)
* `getAsset`, `getAssetPrice`, `calcAssetValue`, `getPool` throw instead …
=> tRPC: Throw errors more aggressively & fix pool detail page SSR

packages/web/components/control/language-select.tsx, packages/web/modals/settings.tsx
As mentioned here: https://github.com/osmosis-labs/osmosis-frontend/pull/2697#issuecomment-1894293695, there is a graphical bug in the language select, this PR fixes this issue.
=> Fix: language select overflow

packages/web/hooks/input/use-search-query-input.ts
added search filter inside pools page query filters.
In the pools page, it is convenient to keep track in the query params also of the text string searched by the user, so that the page state can be restored when sharing the link.
It is also useful to be able to open the pools page in which I display for example only OSMO pools.
=> Feat: add search filter inside pools page url query

packages/web/hooks/use-swap.ts
In production, when I go to the detail page of a token and then change assets via the related assets section, the swap component does not update with the new default values to make the swap.
This PR fixes this misbehavior
=> Fix: swap tool reset on page change

packages/web/hooks/use-feature-flags.ts
This PR will allow third party devs to get all the feature flags working even if they do not have the LD client ID by providing default values to the existing flags.
=> allow the app to work even if developer does not have LD key in env

packages/web/server/api/edge-routers/pools-router.ts, packages/web/server/queries/complex/pools/incentives.ts, packages/web/server/queries/complex/pools/market.ts
Instead of getting pools data, then fetching and mapping incentives data, then fetching and mapping market data; I fetch pools, incentives, and market data concurrently (via Promise.all) then combine the data per pool once the queries are complete. This makes use of the slower sidecar pools provider much more feasible as we are only as slow as the slowest of the above queries.
[ClickUp Task URL](https://app.clickup.com/t/86a1uagzk)
=> Optimize pools page query

.vscode/launch.json
Progress towards: https://github.com/osmosis-labs/osmosis-frontend/issues/2739
This PR adds a VS code debugger configuration.
It enables starting the app and setting breakpoints in the `web` package. I'm still investigating how to achieve setting breakpoints in other packages and tracking progress in #2739.
=> chore: web package debugger configuration for vs code

packages/stores/src/account/base.ts, packages/stores/src/account/types.ts, packages/stores/src/account/utils.ts
Adding TX TTL for better feedback during spam and timely mempool eviction.
This PR introduces and additional field for transaction body and makes the necessary changes to serialize and sign it.
This will allow the chain to evict the transaction from mempool after reaching a certain height. This will be useful during times of spam or congestion where users will get some sort of feedback about transaction failure.
Today, due to a poor chain UX, the feedback is not always present.
The configuration is set to 10. At the current block time of 5 seconds, this gives user transactions approximately 50 seconds to succeed.
- We should set the timeout offset value via config: https://github.com/osmosis-labs/osmosis-frontend/issues/2740
- We should also update `cosmjs` and `cosmos-kit` deps as they …
=> feat: timeout height (transaction TTL)

packages/stores/src/account/base.ts, packages/stores/src/account/types.ts
Closes #2740
Setting up tx timeout offset to be set via environment variable.
Already added the vercel env for all environments:
- Tested swaps in preview
=> feat: configure timeout height via environment variable

packages/web/server/queries/complex/pools/providers/__tests__/imperator.spec.ts, packages/web/server/queries/complex/pools/providers/imperator.ts
The Route Visualization was incorrectly showing the swap fees for each pool, such as displaying 20% for Avax when it should be 0.2%. This error occurred because the backend was miscalculating the swap fee based on the Imperator response. The Imperator API already returns fees as a percentage, so we need to convert them to a base value first.
Before 
After
[ClickUp Task URL](https://app.clickup.com/t/86a24bej6)
- Correctly calculate swap fee percentage on Imperator pool provider
=> fix: Route Visualization Swap Fees

packages/web/.env, packages/web/components/cards/apr-breakdown.tsx, packages/web/config/feature-flag.ts, packages/web/server/queries/complex/pools/incentives.ts
* feat: hide external boost with feature flag
* feat: allow using env vars to exclude boosted pools
* improvement: remove console log
=> feat: Hide External Boost APR with Build Feature Flag (#2762)

packages/web/components/complex/assets-page-v1.tsx, packages/web/components/table/assets-table-v1.tsx, packages/web/stores/assets/assets-store.ts
The Assets store was not taking into account the verified status of native Osmosis tokens. This PR adds the same checks to native balances as with IBC tokens.
=> feat: Acknowledge Verified Status of Native Tokens

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts
When opening new position with in an LP, the ratio of the two tokens normally shows the percentage. Now, since yesterday, it alsways shows 50 50 in both tokens but the value ratio changes. The % percentage value does not get updated. Please fix.
The token balance is showing 50%/50%, but when I put in the amounts, the ratio changes to 60%/40%. The transaction in Keplr shows the correct amounts.
[ClickUp Task URL](https://app.clickup.com/t/86a21c18d)
=> Fix: pool ratio percentage calc

packages/web/components/complex/add-liquidity.tsx, packages/web/modals/lock-tokens.tsx
This PR fixes a bug that didn't feel like adding liquidity to classic pools, the UI was breaking down
=> Fix: add liquidity for classic pools

packages/utils/src/api-client.ts, packages/web/config/cache.ts, packages/web/server/api/edge-routers/pools-router.ts, packages/web/server/queries/complex/pools/providers/imperator.ts, packages/web/server/queries/complex/pools/providers/sidecar.ts, packages/web/utils/async.ts
Following #2800, pools query sometimes took to long to load and the function was timing out. Most likely, the edge function was running out of memory because of individually cached pools. This PR reverts this change and increases the TTL.
=> fix: pools timeout

packages/web/pages/assets/[denom].tsx
There is some reactivity or mobx query store bug causing pools to be infinitely queried in the token detail pages.
I'll disable this non-critical feature for now until I can integrate asset list v2, which includes the list of recommended assets. This prevents us from having to query pools.
=> Fix: temporarily disable recommended assets

packages/web/integrations/tfm/router.ts
This PR fixes TFM error propagation.
Previously, it would return "Unexpected TFM error" without sufficient context to debug.
Now:
=> fix: TFM router tRPC error propagation

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts
If you try to select a moderate or aggressive strategy, the card does not remain selected but the custom one is set by default.
https://app.osmosis.zone/pool/1325
[ClickUp Task URL](https://app.clickup.com/t/86a27gv87)
=> Fix: cl pool strategy selection reset

packages/web/config/feature-flag.ts
- remove pool 1423 from hardcoded boost exclusion
=> Remove pool 1423 from hardcoded boosts

packages/web/server/api/edge-routers/swap-router.ts
As with stDYDX, if an asset isn't configured for pricing yet we should not let that fail the router queries. Instead, we can simply omit the price data from the response.
=> Router: silent failure for missing asset price config

packages/stores/src/tx/utils.ts
Noticed that the error feedback breaks with a strange message when users do not have enough balances.
Traced it to this change. Upon adding this change, observed that a more meaningful error is returned
=> fix: undefined error message breaking feedback

packages/web/components/token-details/token-details.tsx, packages/web/package.json, packages/web/pages/assets/[denom].tsx, packages/web/server/api/edge-routers/assets-router.ts, packages/web/server/queries/base-utils.ts, packages/web/server/queries/coingecko/coin.ts, packages/web/server/queries/coingecko/index.ts, packages/web/server/queries/coingecko/list.ts, packages/web/server/queries/coingecko/price.ts, packages/web/server/queries/complex/assets/market.ts, packages/web/server/queries/complex/assets/price.ts, yarn.lock
* Reduce excessive querying of market caps per asset
* Add batched querying for CoinGecko coins and prices
* Validates that a CoinGecko ID is active on CoinGecko before querying CoinGecko
[ClickUp Task URL](https://app.clickup.com/t/86a293kn6)
- Add [DataLoader](https://www.npmjs.com/package/dataloader#batch-function) package for batching queries by ID into a query by multiple IDs
Should notice improved performance for assets page v2. Also, the Vercel logs should show decreased requests.
=> Optimize asset queries

packages/web/components/complex/all-pools-table-v2.tsx
Fixes Astroport PCL pool not appearing in the pools table
=> fix: Astroport PCl pool type not appearing in the v2 table

packages/web/components/complex/all-pools-table-v2.tsx, packages/web/server/api/edge-routers/pools-router.ts, packages/web/server/queries/complex/pools/market.ts
Currently, our pools page bricks if volume data is unavailable.
This PR fixes the issue by avoiding to format the volume column in such a case.
It calculates the number of pools that have volume formatted. If greater than half, volume column is displayed and the missing pools show "N/A"
If less than half, then we do not show the volume column
This is related to the `/fees/v1/pools` query
Tested this by force throwing an error from the endpoint.
See:
I added the error mock here: https://github.com/osmosis-labs/osmosis-frontend/blob/a1660e2e3244adb0653f370a3ff6a9f7983d2d10/packages/web/server/queries/imperator/pools-fees.ts#L17-L20
=> fix: hide volume column on error on pools page v2

.github/workflows/jest-tests.yml, packages/web/integrations/bridges/axelar/axelar-bridge-provider.ts, packages/web/integrations/bridges/axelar/axelar-transfer-status-source.ts, packages/web/integrations/bridges/axelar/types.ts, packages/web/integrations/bridges/skip/skip-bridge-provider.ts, packages/web/integrations/bridges/skip/skip-transfer-status-source.ts, packages/web/integrations/bridges/skip/types.ts, packages/web/integrations/bridges/squid/const.ts, packages/web/integrations/bridges/squid/squid-bridge-provider.ts, packages/web/integrations/bridges/squid/squid-transfer-status-source.ts, packages/web/integrations/bridges/types.ts, packages/web/modals/bridge-transfer-v2.tsx, packages/web/package.json, packages/web/server/queries/base-utils.ts, packages/web/server/queries/complex/assets/__tests__/assets.spec.ts, packages/web/server/queries/complex/concentrated-liquidity/__tests__/concentrated-liquidity.spec.ts, packages/web/server/queries/complex/pools/market.ts, packages/web/server/queries/complex/pools/providers/__tests__/sidecar.spec.ts, packages/web/server/queries/complex/pools/providers/sidecar.ts, packages/web/stores/root.ts, packages/web/utils/cache.ts
Reduces client bundle size by removing import of server code for use in bridge providers' transfer status source objects. Adds remote cache object (implemented with Vercel KV). Found root bundle to be reduced from 2.14 to 2.11 mb.
It's also worth noting that I dove into our [Vercel KV store in prod](https://vercel.com/osmo-labs/osmosis-frontend/stores/kv/store_cGqHAHqmtP0OA8YD/cli) and tweaked the settings to auto prune keys when full, and added more read replicas: Washington DC, Dublin, and Singapore.
* Add remote cache and use in sidecar pool provider
* Uses superjson to let us easily cache complex objects
* Refactor bridge providers to track transfer statuses directly in the respective transfer status source implementations
* Fix tests that are intended to run in node env (vs dom env) …
=> Add remote cache support, remove server imports

packages/web/config/ibc-overrides.ts
Update ibc-overrides for polygon.USDC.axl, avalanche.USDC.axl, and moonbeam.DOT.axl
Were using the old symbols
_(E.g.: This pull request improves area A by adding ...._ -->
Update ibc-overrides.ts to use the updated symbols for these assets.
=> Update ibc-overrides for polygon.USDC.axl, avalanche.USDC.axl, and moonbeam.DOT.axl

packages/web/components/complex/all-pools-table-v2.tsx, packages/web/server/queries/imperator/pools-fees.ts
Similar to https://github.com/osmosis-labs/osmosis-frontend/pull/2849, it hides the fees column that currently formats "0" instead of being completely hidden
Tested by hardcoding an error and then removing: [6f5bfe2](https://github.com/osmosis-labs/osmosis-frontend/pull/2855/commits/6f5bfe27940a59756d019ecbfda8fd20d4dd4e4e)
=> hide fees column similar to volume on failure

packages/web/components/complex/all-pools-table-v2.tsx
Fixes the condition for volume and fee display to show them when more than half is available.
The condition was made too strict in: https://github.com/osmosis-labs/osmosis-frontend/pull/2855 and we should relax it
=> fix: dispaly volume and fees when half is available

packages/web/hooks/use-swap.ts
It could get batched with another more expensive tRPC query, causing unnecessary delays in asset info loading in swap tool.
=> Remove batching from select assets

packages/web/components/input/search-box.tsx, packages/web/components/pool-detail/share.tsx, packages/web/server/queries/complex/assets/price.ts, packages/web/server/queries/complex/pools/providers/__tests__/indexer.spec.ts, packages/web/server/queries/complex/pools/providers/indexer.ts
The way we formed the cache key may cause some unnecessary cache misses in the remote cache. The `getAssetPrice` receives an object identifying the asset with either `coinMinimalDenom` or `sourceDenom`. So, we may get cache misses depending on what identifier is used.
This change has us query the asset list with those identifiers and using the the valid asset's `coinMinimalDenom` as the sole cache key. On Osmosis, it will be a guaranteed unique representation/identifier for that asset.
Also, I narrowed the type to fail builds if at least one identifier is not provided, which may prevent future bugs.
You can see the simplification when querying the cache directly:
=> Use only `coinMinimalDenom`  for price cache key

packages/web/server/queries/complex/assets/price.ts
When working on new assets page, I found, even with fast read times, the remote cache of prices was causing user asset breakdown and assets table to take a long time to load. For now, let's disable it and wait for SQS prices endpoint.
=> Disable remote cache for prices

packages/web/components/navbar/index.tsx, packages/web/hooks/use-swap.ts, packages/web/modals/profile.tsx, packages/web/server/api/edge-routers/assets-router.ts, packages/web/stores/index.tsx
I realized the performance issue of loading to/from assets in swap tool was from needlessly getting the user's balance as well as the asset info. I refactored the tRPC procedure name to make this clearer, and only get the currency in the to/from portion of the swap tool.
=> Fix: get only asset info in swap tool

packages/web/config/ibc-overrides.ts
Update DYM Deposit Override to Dymension Protal, which now supports Osmosis and works with Metamask (when Osmosis Pro's Leap MetaMask snaps doesn't work for all Metamask users)
Update ibc-overrides.ts DYM Deposit transfer override to point to Dymension Portal instead.
=> Update DYM Deposit Override

packages/web/server/queries/complex/pools/index.ts
We moved our pools query to SQS since all of our indexer data sources were down. This saved our prod environment since we had no source for pools.
However, since we still need to calculate pool TVL from prices for SQS pools, I've often noticed performance issues in prod.
So, with the indexer back up, I'm going to switch our pools provider back to the indexer until we can get USDC TVL from the sidecar pools query.
=> Use indexer for pools

packages/web/server/queries/complex/assets/price/providers/sidecar.ts
Try to get price from CoinGecko if SQS fails to provide a price.
=> SQS prices: fall back to CoinGecko for missing prices

packages/web/server/queries/complex/concentrated-liquidity/index.ts, packages/web/server/queries/complex/pools/user.ts
Add some more fault tolerance to getUserPools to catch errors and timeouts and return data as missing instead of failing the procedure.
=> getUserPools: Catch query errors

packages/web/server/queries/complex/assets/price/providers/sidecar.ts
SQS now returns prices for 0 dec tokens
Before merging this, this should not return an error:
https://sqsprod.osmosis.zone/tokens/prices?base=ibc%2FE27CD305D33F150369AB526AEB6646A76EC3FFB1A6CA58A663B5DE657A89D55D
=> SQS prices: remove 0 dec check

package.json
In our package.json, we specified that the Node.js version should be 18 or higher under engines. When Node.js version 20.x became the LTS version, our builds started failing because Vercel updated the Node.js version to 20.x, in line with our specified condition. Unfortunately, this version introduces changes that break our libraries. To resolve this, we will set the Node.js version in our package.json to specifically use version 18.x.
=> fix: Lock Node Version to 18.x

packages/web/pages/wormhole.tsx
fixes the query for Osmosis $W balance on the Wormhole Page, needed for bridging W back to Solana.
Before change:
We have CORS errors, and error saying "failed to fetch balances":
and Balances on Osmosis fails to load:
After change:
No more CORS errors, and balance loads:
Adds gateway rpc to wormhole config in web/pages/wormhole.tsx, as recommended by Wormhole team.
I didn't touch math, so I'm not sure why math is failing lint check
=> fix: Osmosis $W balance on Wormhole Page

packages/web/hooks/ui-config/use-asset-info-config.ts
This PR improves fallback handling for token info page graphs, in particular even if a token explicitly wants to use coingecko, however we try to retrieve the data from numia, if we get no results then we use coingecko services.
=> Feat: improve token info chart price fallback

packages/server/src/queries/complex/assets/price/providers/sidecar.ts
Lower sidecar batch loader prices cache to 1 minute.
Upon discussing this with @jonator , realized that this is a batch loader cache. Propose lowering it to 1 minute still as 10 minutes feels excessive.
=> docs: comment for batch loader cache 

packages/server/src/queries/complex/assets/market.ts, packages/server/src/trpc-routers/assets-router.ts
* Use prices from /tokens/all instead of batched queries to SQS prices
=> Optimize market assets tRPC procedure

packages/server/src/queries/complex/assets/market.ts, packages/server/src/trpc-routers/assets-router.ts, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
You should now see volumes for WBTC:
[Linear Task URL](https://linear.app/osmosis/issue/FE-193/make-sure-all-volumes-are-showing-correctly)
* Key API data by coinMinimalDenom instead of symbol (and double check casing)
* Update volume table header text to match designs
=> New assets page: make sure all volumes are showing correctly

packages/web/hooks/queries/assets/use-coin-price.ts
In addition to this cache client side, we also have it in SQS. We should incrementally lower the TTL in the client, to avoid the caching complexity and staleness problems around prices.
If this works well and performance is unaffected, we can evaluate further going down to 1-2 seconds
=> refactor: lower coin price cache and stale time from 5 to 3 seconds

packages/web/hooks/use-feature-flags.ts
We decided to avoid delaying launch of new assets page & portfolio page on mobile responsiveness by disabling these new pages just on mobile regardless of FF state.
[Linear Task URL](https://linear.app/osmosis/issue/FE-238/ff-off-on-mobile)
* Force FF to false on mobile
=> Disable assets & portfolio pages on mobile

packages/server/src/queries/complex/pools/index.ts
Use SQS as the provider of pools on testnet, as it's more immediately available compared to pools from indexer as we don't have an indexer for testnet yet.
=> Use sqs for pools on testnet

.github/workflows/frontend-e2e-tests.yml
Need to split e2e tests between stage and master branches. Workflow is initiated upon on successful deployment.
Looks like at that point of time GitHub does not recognize a branch inside the test step.
- Separate job for master e2e tests
- Separate job for stage e2e tests
...
=> Split E2E workflow per stage/master branch

packages/types/src/asset-types.ts
Make logoURIs optional in cosmos counterparty.
=> Asset list type: counterparty optional logoURIs

.github/workflows/frontend-e2e-tests.yml
Test workflow now runs on environments:
- Production – osmosis-frontend
- Preview – osmosis-frontend
[Linear FE-60](https://linear.app/osmosis/issue/FE-60)
Updated E2E test workflow to start on successful deployments to preview or production.
This change has been tested on branch but must be merged to see how it performs.
=> Run E2E tests on Production and Preview deployments

packages/web/components/swap-tool/index.tsx
* Use valid number in swap event property (remove "$" by using `toDec()`)
* Include property in swap started event
* Change swap button disabled to more explicitly be if there's a quote available, instead of if it's loading (more accurate)
=> Swap Amplitude event: use valid number in swap event

packages/web/components/funnels/balances-moved.tsx, packages/web/components/table/asset-info.tsx
https://linear.app/osmosis/issue/FE-309/make-portfolio-banner-an-anchor-link
=> Assets page: use anchor for balances moved banner

packages/web/config/generate-lists.ts, packages/web/stores/assets/assets-store.ts
Use `counterparty` instead of `transferMethod` for getting the chain name
=> Fix asset list build: get chain name from first counterparty (IBC)

packages/web/components/token-details/token-details.tsx
this pr fixes this formatting error, now a compact form is used by removing the scientific notation.
[Linear Task URL](https://linear.app/osmosis/issue/FE-406/fix-circulating-supply-formatting)
=> fix: circulating supply formatting

packages/server/src/queries/complex/assets/price/historical.ts, packages/server/src/queries/data-services/token-historical-chart.ts, packages/web/hooks/ui-config/use-asset-info-config.ts
Migrate to the new numia service to get the chart, instead of using the token symbol we can now use the denom, this should reduce the errors of searching for a token.
[Linear Task URL](https://linear.app/osmosis/issue/FE-310/migrate-from-tokensv2symbol-to-tokensv2denom)
=> feat: add token chart queries by denom

packages/server/src/queries/complex/assets/market.ts, packages/server/src/queries/data-services/token-data.ts, packages/server/src/trpc-routers/assets-router.ts, packages/web/components/table/asset-info.tsx
Data was added to:
https://stage-proxy-data-api.osmosis-labs.workers.dev/tokens/v2/all
[Linear Task URL](https://linear.app/osmosis/issue/FE-247/add-1h-and-7d-price-change-columns)
=> Add 1h, 7d price change to assets table

packages/web/components/assets/categories.tsx, packages/web/components/navbar/index.tsx
Fix z index for mobile dropdown menu and category sample images:
>
=> Fix z index for mobile nav menu

packages/web/components/swap-tool/index.tsx
I updated it to rely on missing quotes instead of just loading state (which is conditional, therefore less reliable), but missed the disconnected wallet state.
=> Swap tool: fix button disabled

packages/server/src/queries/complex/concentrated-liquidity/index.ts, packages/server/src/queries/complex/pools/bonding.ts, packages/server/src/queries/complex/pools/incentives.ts, packages/server/src/queries/complex/pools/share.ts, packages/server/src/queries/osmosis/incentives/index.ts, packages/server/src/queries/osmosis/incentives/lockable-durations.ts
Improve performance by not querying params for lockable durations, which are not expected to change. See linear issue.
[Linear Task URL](https://linear.app/osmosis/issue/FE-302/hardcode-lockable-durations-query-response)
=> Remove lock duration query

packages/web/config/ibc-overrides.ts
Adding pica assets deposit overrides
adds deposit and withdraw URLs for new PICA assets to Update ibc-overrides.ts
=> Deposit Overrides for Ethereum Assets via Picasso

packages/server/src/trpc-routers/__tests_e2e__/swap-router.test.ts, packages/web/e2e/pages/swap-page.ts, packages/web/playwright.config.ts
- Added 1 re-try for E2E Swap tests
- Added longer wait for a quote (swap button to be enabled)
- Skipped low liquidity test (TFM - ATOM <> OSMO)
=> Added 1 re-try and longer wait for a quote

.github/workflows/server-e2e-tests.yml, packages/server/src/trpc-routers/__tests_e2e__/swap-router.test.ts
- Run Server E2E Workflow every 30 minutes
- Changed Alert name
- Fix USDC/USDC.axl test
[Linear Task FE-455](https://linear.app/osmosis/issue/FE-455/remove-low-liquidity-e2e-tests)
Added schedule:
- cron: "*/30 * * * *"
=> Run Server E2E Workflow every 30 minutes

.gitignore, tsconfig.json
This PR improves the development workflow by enabling TypeScript declaration maps. This enhancement allows for better debugging and navigation by linking declaration files back to their original source files.
- Enabled TypeScript declaration maps in the `tsconfig.json` file.
=> improvement: Enable TSC Declaration Maps

packages/bridge/package.json, packages/keplr-hooks/package.json, packages/keplr-stores/package.json, packages/math/package.json, packages/pools/package.json, packages/proto-codecs/package.json, packages/server/package.json, packages/stores/package.json, packages/types/package.json, packages/utils/package.json, turbo.json
The ts config for project references was recently added to allow IDEs to reference the source folder as the definition instead of the build folders. So, f12 now works across packages.
However, for turbo build caching to work properly the output of the recently added tsproject build needs to be included in build output for each package. Also, for local development to work better, the file needs to be deleted when cleaning.
=> Clean and cache output of tx project build output

packages/stores/src/ibc-history/index.ts, packages/web/stores/ibc-notifier.tsx
Only use one handler in the IBC history store to ensure only one callback is called even if multiple mount cycles occur on the component that adds the handler.
=> Show 1 IBC complete toast

packages/web/components/earn/filters/filters-modal.tsx, packages/web/components/earn/filters/top-filters.tsx
removed token holding filter if we're using yout strategy tab.
Inside the earn page we are going to remove "token holding" filter if you're inside "your strategies" tab, because the data is already filtered for the tokens you have.
This PR also ensure that we render `<SearchBox />` using `outline` variant everywhere inside the earn page.
=> feat: remove token holding filter and minor ui bug

packages/server/src/queries/complex/assets/price/historical.ts, packages/web/components/cards/my-position/expanded.tsx, packages/web/components/pool-detail/concentrated.tsx
Adjust TTL values for price chart since the last closing price is used for current price display.
=> Display latest price from pool instead of historical price data

packages/web/integrations/kado/index.tsx
Adding additional allow params and wBTC to kado iframe integration
[Linear Task URL](https://linear.app/osmosis/issue/FE-438/kado-url-params-edit)
- Adding additional allow params and wBTC to kado iframe integration
=> update kado iframe integration

packages/web/config/ibc-overrides.ts
Add Deposit IBC Overrides for Solana Assets via Picasso
-add LST, jitoSOL, edgeSOL, wSOL, solana.USDT, to ibc-overrides, with deposit and withdraw URL going to Picasso App (transfers with Solana)
=> Add Deposit IBC Overrides for Solana Assets via Picasso

packages/web/components/swap-tool/index.tsx, packages/web/hooks/use-swap.tsx
When wallet is disconnected and there's no account, disable gas fee queries and only show connect wallet button
=> Fix quote loading state when wallet disconnected

packages/web/hooks/use-swap.tsx
[Vercel Logs](https://vercel.com/osmo-labs/osmosis-frontend/logs?slug=app-future&slug=en-US&slug=osmo-labs&slug=osmosis-frontend&slug=logs&page=1&timeline=past30Minutes&startDate=1717521244055&endDate=1717523044055&levels=error&selectedLogId=1717522995240299524043600000&selectedLogTimestamp=1717522995240&forceEndDate=1717523032957)
I've noticed an increase in failed gas estimation queries in Vercel logs. Our UI gracefully handles these failed queries but it should still be prevented.
It's hard to reproduce but it might be a race condition where an estimation query is enabled when it shouldn't be. I added more checks to the query enabled flags to ensure the quote and estimation queries are only sent when current state is valid.
=> Swap tool gas estimation: add more checks to query enabled

packages/web/config/ibc-overrides.ts
$WHINE deposit and withdraw URL overrides to Picasso bridging interface
Update ibc-overrides.ts to include $WHINE deposit and withdraw URL overrides to Picasso bridging interface
=> Add $WHINE Deposit/Withdraw URL Override

packages/web/components/swap-tool/index.tsx, packages/web/hooks/use-swap.tsx
Before, we logged events if the broadcast failed (could be network error or signature rejection). Now, the promise that rejects that causes the error to be logged should largely come from failed txs on chain. Other lower priority errors, like random network errors or signature rejections, should be ignored.
=> Swap failed events: only reject committed txs with code !== 0

packages/web/components/chart/light-weight-charts/chart.tsx, packages/web/components/chart/light-weight-charts/linear-chart.ts, packages/web/components/chart/light-weight-charts/utils.ts, packages/web/components/chart/price-historical-v2.tsx, packages/web/components/chart/price-historical.tsx, packages/web/hooks/ui-config/use-asset-info-config.ts, packages/web/pages/assets/[denom].tsx
This PR introduce a price axis on the right for the token info page chart.
[Linear Task](https://linear.app/osmosis/issue/FE-505/add-price-axis-to-charts)
=> feat: add price axis to charts

.github/workflows/frontend-e2e-tests.yml, packages/web/e2e/pages/swap-page.ts, packages/web/e2e/tests/swap.stables.spec.ts, packages/web/e2e/tests/swap.wallet.spec.ts
Make e2e workflow run faster by re-using wallet between tests.
- Make tests setup wallet just once
- Fix some typos
=> Make tests setup wallet just once

packages/server/src/queries/github/token-info.ts, packages/web/.env
This PR changes the pointing of the CMS api from the old deprecated CMS repo to the assetlist repo.
> Note: we should change env vars from this one:
> `CMS_REPOSITORY_PATH=token-info/main/contents`
> To this one:
> `CMS_REPOSITORY_PATH=assetlists/main/osmosis-1/generated/asset_detail`
[Linear Task URL](https://linear.app/osmosis/issue/FE-538/migrate-from-cms-repo-to-assetlist-repo)
=> feat: :sparkles: add new cms config

packages/web/hooks/limit-orders/use-place-limit.ts
Previous calculations when placing a limit order assumed the quote asset to be a stablecoin. These changes are to adjust for the current quote asset's fiat price for the case where the quote asset is not a stablecoin.
[LIM-109: Adjust Limited Order to Account for Quote Asset Price](https://linear.app/osmosis/issue/LIM-109/adjust-limit-order-placing-to-account-for-quote-asset-price)
- Adjusted `usePlaceLimit` calculations to account for `quoteAssetPrice` (the current fiat value of the quote denom)
=> feat: normalised price values against USD for limit orders

packages/server/src/env.ts
This PR allows to override `NUMIA_BASE_URL` via an env variable.
This is needed to support different network (e.g. testnet)
In the future we could merge all the data services env vars into one.
=> Add NEXT_PUBLIC_NUMIA_BASE_URL env var

packages/bridge/src/__tests__/mock-chains.ts, packages/bridge/src/axelar/__tests__/axelar-transfer-status.spec.ts, packages/bridge/src/ibc/__tests__/ibc-transfer-status.spec.ts, packages/bridge/src/ibc/transfer-status.ts, packages/bridge/src/skip/__tests__/skip-transfer-status.spec.ts, packages/bridge/src/squid/__tests__/squid-transfer-status.spec.ts, packages/tx/src/tracer.ts
I accidentally committed the IBC provider tests to stage in the past, but they are quite simple.
This PR introduces the test suite for the IBC status provider, which has quite a few async operations. In short, it sets up a Promise.wait to either wait for an IBC ack confirming the transfer, or for the IBC timeout height to be reached on the counterparty chain from polling.
[Linear Task URL](https://linear.app/osmosis/issue/FE-473/add-unit-tests-for-ibc-bridge-provider-and-transfer-status)
* Adds unit tests for IBC transfer status provider
* Makes minor improvements to the status provider and providers it uses
* All tests pass
=> Add IBC status provider tests

.github/workflows/frontend-e2e-tests.yml, .github/workflows/server-e2e-tests.yml
Added Slack alerts for FE E2E tests
[Linear Task FE-536 URL](https://linear.app/osmosis/issue/FE-536)
=> Added Slack alerts for FE E2E tests

packages/web/e2e/tests/swap.stables.spec.ts, packages/web/e2e/tests/swap.wallet.spec.ts
Just a config change to have a bigger viewport for Playwright tests. Will be better for screenshots on fail.
=> Bigger viewport for Playwright

packages/web/config/ibc-overrides.ts
Update BERLIN to "BERLIN-legacy" because it was hardcoded and now doesn't match the assetlist.
Update BERLIN to "BERLIN-legacy" in ibc-overrides.ts
=> Update BERLIN symbol to match the assetlist

packages/server/package.json, packages/server/src/queries/twitter/twitter.ts, packages/server/src/utils/remote-cache.ts, yarn.lock
Replace vercel kv with upstash for twitter cache and generic remote cache.
[Linear Task URL](https://linear.app/osmosis/issue/FE-520/change-vercel-kv-to-upstash)
=> feat: replace vercel kv with upstash

packages/tx/src/__tests__/gas.spec.ts, packages/tx/src/gas.ts, packages/web/components/pool-detail/share.tsx
Currently, the WBTC spot price is too high relative to OSMO. This causes a 0 amount of WBTC to be calculated as an alternative fee amount. We need to handle this by ensuring the alternative fee token amount is greater than 0, and otherwise searching for other fee tokens.
* Check for 0 alternative fee token amount, continue if <= 0
* Add test case
* Unit tests pass
* 0 fee amounts are not suggested when estimating a tx execution
=> Handle 0 fee amount estimations

packages/web/pages/assets/[denom].tsx
Currently full screen which we should move away from. Max width should be 1280px with 40px inner padding.
[Linear Task URL](https://linear.app/osmosis/issue/FE-553/adjust-max-width-to-new-standard)
=> feat: :lipstick: add asset page max container

packages/bridge/jest.config.js, packages/bridge/src/axelar/__tests__/axelar-bridge-provider.spec.ts, packages/bridge/src/axelar/index.ts, packages/bridge/src/ibc/index.ts, packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts, packages/bridge/src/skip/index.ts, packages/tx/src/gas.ts
Applies our new gas estimation function to existing bridge providers for Cosmos transactions. Includes the advanced features included in the new function, such as fee markets and alternative fee tokens.
[Linear Task URL](https://linear.app/osmosis/issue/FE-521/add-gas-estimation-to-existing-bridge-providers)
* Skip provider: estimate cosmos txs
* Axelar provider: estimate cosmos txs
=> Bridge Providers: add gas estimation for cosmos txs

packages/web/components/navbar-osmo-price.tsx, packages/web/hooks/use-feature-flags.ts, packages/web/pages/index.tsx
Adds a feature flag for `limitOrders` that toggles between the current swap page and the new limit orders swap page.
[LIM-117: Integrate Feature Flags](https://linear.app/osmosis/issue/LIM-117/integrate-feature-flags)
- Added a `limitOrders` feature flag
- Readded old swap page under `HomeV1` and renamed the new component (`Home` -> `HomeNew`)
- Swapping between the two versions can be done by toggling the `limitOrders` feature flag
=> feat: limit orders feature flag 

packages/web/components/control/token-select-limit.tsx, packages/web/components/place-limit-tool/index.tsx, packages/web/components/trade-tool/index.tsx, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/modals/review-limit-order.tsx
Replaced `OrderDirection` enum with a `type` that can be either `"bid"` or `"ask"`
- `OrderDirection` is now a `type` instead of an `enum`
=> refactor: replace OrderDirection enum with string literal

packages/server/src/queries/complex/pools/transmuter.ts
Right now there is a bug on production, the percentage we show in the alloyed asset is miscalculated because it does not take into account that each asset has different decimals.
=> fix: :bug: transmuter pool liquidity percentage calc

packages/server/src/queries/complex/orderbooks/active-orders.ts, packages/server/src/queries/complex/orderbooks/index.ts, packages/server/src/queries/complex/orderbooks/tick-state.ts, packages/server/src/queries/osmosis/orderbooks.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/price-selector.tsx, packages/web/hooks/limit-orders/use-orderbook.ts
These changes add the required queries and hooks to get all active limit orders for a user.
[LIM-137: Tick Info Query](https://linear.app/osmosis/issue/LIM-137/[services]-tick-info-query)
[LIM-138: Query for all Active Orders Info](https://linear.app/osmosis/issue/LIM-138/[services]-query-for-all-active-orders-info)
- Added the following queries:
- `queryOrderbookTicks`: Gets tick state for the provided tick IDs
- `queryOrderbookTickUnrealizedCancelsById`: Gets the amount of unrealized cancels for the given tick IDs
- Exposed the above queries via cached complex server functions
- Exposed the above queries via two orderbook router methods 
Pagination will be added in a following PR
=> feat: all active limit orders hook

packages/server/src/queries/complex/orderbooks/active-orders.ts, packages/server/src/queries/complex/orderbooks/index.ts, packages/server/src/queries/complex/orderbooks/tick-state.ts, packages/server/src/queries/osmosis/orderbooks.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/price-selector.tsx, packages/web/hooks/limit-orders/use-orderbook.ts
Add "Orders" tab to Transactions page
[Linear Task URL](https://linear.app/osmosis/issue/LIM-130/[tx-page]-add-order-history-to-the-transactions-page)
=> feat: Order history page

packages/stores/src/account/base.ts
Wallet tx validation will fail if `isNeededForTx` is present (only conditionally returned) along with gas amount.
=> Fix: remove `isNeededForTx` being returned by gas estimation

packages/math/src/pool/concentrated/__tests__/tick.spec.ts, packages/math/src/pool/concentrated/tick.ts, packages/trpc/src/orderbook-router.ts
These changes add a `price` field to `MappedLimitOrders` that show a representation of the ratio between the quote and base asset at the tick for the given order.
- Added `tickToPrice` function in the `math` package
- Added price calculation when mapping order info in `getTickInfoAndTransformOrders`
Added several test cases for `tickToPrice` in `tick.spec.ts`
=> feat: Order price mapping

packages/tx/src/gas.ts
Got reports that people are still having issues with 1 uwbtc amounts being used for gas, resulting in a chain error. This adds a check to also ensure that more than 1 unit of gas is estimated, otherwise other fee tokens will be tried.
Also changes unit type to `Int` as it gets truncated into a string integer value above.
=> Increase check for low precision

packages/bridge/src/ibc/__tests__/ibc-transfer-status.spec.ts, packages/bridge/src/ibc/index.ts, packages/bridge/src/ibc/transfer-status.ts, packages/bridge/src/index.ts, packages/web/stores/root.ts
We will pass IBC transfers here to be tracked by this provider from IBC transfers initiated by the new deposit/withdraw flow.
[Linear Task URL](https://linear.app/osmosis/issue/FE-559/add-ibc-transfer-status-provider-to-status-receiver)
* Add IBC transfer status provider to our transfer status UI config in root of repo
=> Add IBC transfer status provider to store

packages/web/components/input/limit-input.tsx, packages/web/components/place-limit-tool/index.tsx
Disable input switching on market orders and just show fiat/token est. conversion
[Linear Task URL](https://linear.app/osmosis/issue/LIM-144/[ui]-disable-input-switching-on-market-orders)
=> [Limit Orders]: Disable input switching on market orders

packages/server/src/queries/complex/orderbooks/denoms.ts, packages/server/src/queries/complex/orderbooks/index.ts, packages/server/src/queries/complex/orderbooks/tick-state.ts, packages/server/src/queries/osmosis/orderbooks.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/complex/orders-history/cells/filled-progress.tsx, packages/web/components/complex/orders-history/columns.tsx, packages/web/hooks/limit-orders/use-orderbook.ts, packages/web/hooks/use-feature-flags.ts
These changes add a conversion from placed quantity in coin minimal amounts to a raw denom amount by dividing by 10 to the power of the number of decimals in the placed asset, i.e. if a coin has  6 decimals and we placed 1000000 minimal then the raw value would be 1 (1000000/10^6).
- `useOrderbookAllActiveOrders` returns raw denom value in `placed_quantity` field
- `useOrderbookAllActiveOrders` returns an `output` field
- Added a `queryOrderbookDenom` query
- Wired in order data for input and output values to order history page
=> feat: Placed quantity in denom values 

packages/web/config/wallet-registry.ts, packages/web/modals/wallet-select/use-selectable-wallets.ts
[Linear Task URL](https://linear.app/osmosis/issue/FE-592/implement-cryptocom-mobile-wallet)
=> (Wallet Addition) Display Crypto.com Wallet in App Browser

packages/web/.env, packages/web/hooks/use-swap.tsx, packages/web/stores/index.tsx
Pass `isOneClickTradingEnabled` flag to the max balance gas estimation query to ensure the extension options are included
=> Use 1ct flag when estimating max balance gas

packages/server/src/queries/osmosis/orderbooks.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/complex/orders-history/cells/filled-progress.tsx, packages/web/components/complex/orders-history/index.tsx, packages/web/hooks/limit-orders/use-orderbook.ts, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/hooks/use-feature-flags.ts
These changes add a query to retrieve all claimable orders and include the results of that query in the order history page. This is a separate query as the current active orders query is paginated and may not return all claimable orders. Also includes is the ability to batch claim all filled orders.
There are also some changes to accommodate for changes in the smart contract.
[LIM-157: Claimable Orders](https://linear.app/osmosis/issue/LIM-157/[services-ui]-claimable-orders)
[LIM-158: Batch Claim Orders](https://linear.app/osmosis/issue/LIM-158/[services]-batch-claim-orders)
- Added `getClaimableOrders` to orderbook router
- Added `useClaimableOrders` hook
- Wired in `Claim All` button on order history page
=> feat: added claimable orders

packages/server/src/queries/complex/earn/strategies.ts, packages/web/hooks/use-get-earn-strategies.ts, packages/web/pages/earn/index.tsx
By default, platforms are now set according to CMS data
=> fix: default platforms

packages/server/src/queries/complex/orderbooks/active-orders.ts, packages/server/src/queries/complex/orderbooks/historical-orders.ts, packages/server/src/queries/complex/orderbooks/index.ts, packages/server/src/queries/osmosis/orderbooks.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/complex/orders-history/columns.tsx, packages/web/hooks/limit-orders/use-orderbook.ts, packages/web/hooks/use-feature-flags.ts
These changes add historical data (provided by Numia) on a user's limit orders. Orders are retrieved from Numia and mapped to the expected interface for display and merged with active orders for pagination.
These changes also include fixes for displaying the in/out amount for an order on the order history page.
**Currently data from Numia is replaced by placeholder data.**
[LIM-136: Add Endpoint to get Past Orders](https://linear.app/osmosis/issue/LIM-136/[services]-add-endpoint-to-get-past-orders)
- Added `queryHistoricalOrders` Numia query
- Renamed unrealized cancels query to `get_unrealized_cancels`
- Added order sorting for active/historical orders
=> feat: historical limit orders 

.github/workflows/monitoring-e2e-tests.yml, packages/web/e2e/tests/portfolio.wallet.spec.ts
Always run delete-deployments for Synthetic Monitoring E2E tests workflow
=> Always run delete-deployments for Synt Monitoring

packages/web/next.config.js
To make sure favicon is cached for 10 days
This PR should close the bounty https://github.com/osmosis-labs/osmosis-frontend/issues/3357
[Linear Task URL](https://github.com/osmosis-labs/osmosis-frontend/issues/3357)
Added headers config for nextjs
Reset to stage and applied fix
@MaxMillington please review
=> use nextjs headers to implement caching

packages/web/hooks/limit-orders/use-place-limit.ts
On limit/market order inputs for the "buy" tab the balance check was using base asset instead of the quote asset. These changes correct that.
[LIM-169: Use Fiat Balance for Buy Tab Input Calculation](https://linear.app/osmosis/issue/LIM-169/[ui]-use-fiat-balance-for-buy-tab-input-calculation)
- `quoteAssetBalance` now correctly uses the quote asset
=> fix: insufficient funds now correctly uses quote asset balance on buy

packages/web/components/trade-tool/index.tsx
These changes add an indicator to the swap page when the use has a fully claimable order.
[LIM-168: Add Claimable Orders Indicator to Order History Link](https://linear.app/osmosis/issue/LIM-168/[ui]-add-claimable-orders-indicator-to-order-history-link)
- Replaced mock data in `trade-tool/index.tsx` with query data
=> feat: added indicator for claimable order amount to swap page

packages/web/components/input/limit-input.tsx
These changes prevent a user's input in the buy/sell tab from causing an overflow error.
[LIM-167: Input Cap for Buy/Sell Tab](https://linear.app/osmosis/issue/LIM-167/[ui]-input-cap-for-buysell-tab)
=> feat: added input validation for limit input

.github/workflows/frontend-e2e-tests.yml, packages/web/e2e/pages/base-page.ts, packages/web/e2e/pages/portfolio-page.ts, packages/web/e2e/pages/transactions-page.ts, packages/web/e2e/tests/transactions.wallet.spec.ts
- Add random transactions test, to make sure transaction details page is displayed.
- Add a specific transaction test, to make sure it is displayed in reasonable time.
[Linear Task Add Transactions page tests](https://linear.app/osmosis/issue/FE-696)
=> Add random and specific transactions tests

packages/bridge/src/skip/__tests__/skip-transfer-status.spec.ts, packages/bridge/src/skip/transfer-status.ts, packages/bridge/src/squid/__tests__/squid-transfer-status.spec.ts, packages/bridge/src/squid/transfer-status.ts, packages/web/stores/root.ts
For Skip and Squid, they linked to axelar scan for all transfers. If it's a basic IBC transfer (which we now support), axelarscan would yield no results. Now, we detect if it's a basic IBC transfer and link to mintscan instead.
[Linear Task URL](https://linear.app/osmosis/issue/FE-741/skip-status-source-fix-links-to-ibc-txs)
* Use chain list and chain ID types to determine if a transfer is a basic IBC transfer
* Use Squid or Skip to initiate an IBC transfer. Confirm that it links to mintscan instead of axelarscan.
=> (Deposit/Withdraw) Generate correct explorer URL for IBC transfers

.github/await_deployment.py, .github/workflows/prod-frontend-e2e-tests.yml
Change Production frontend E2E tests to run on push to reduce spam deployments and events.
[Change Production frontend E2E tests to run on push](https://linear.app/osmosis/issue/FE-719)
=> Change Prod tests to run on push

packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/modals/review-limit-order.tsx
These changes alter the `ReviewLimitOrder` modal in order to accommodate market orders. 
Note: The minimum received amount fiat value looks unusual as it's using the in amount and base asset's fiat value.
[LIM-166: Fix Review Order for Market Orders](https://linear.app/osmosis/issue/LIM-166/[ui]-fix-review-order-for-market-orders)
- Altered `use-place-limit` fields to return market values as expected
- Updated `ReviewLimitOrder` component for market order values
=> feat: review modal now supports market order info

packages/web/components/navbar/index.tsx, packages/web/components/one-click-trading/introducing-one-click-trading.tsx, packages/web/components/one-click-trading/one-click-toast.tsx, packages/web/components/one-click-trading/one-click-trading-settings.tsx, packages/web/hooks/mutations/one-click-trading/use-create-one-click-trading-session.tsx, packages/web/hooks/queries/osmosis/use-icns-name.ts, packages/web/hooks/use-is-new-account.ts, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json, packages/web/modals/profile.tsx, packages/web/pages/_app.tsx, packages/web/pages/index.tsx
Currently we're showing 1CT for new users/wallets that don't have funds, but this causes a dead end when they try to connect and start a 1CT session. We should simply disable and hide the feature for these users until they've deposited funds.
[Linear Task URL](https://linear.app/osmosis/issue/FE-751/disabled-and-hide-1ct-for-new-users-with-no-funds)
=> (1CT) Disable and hide 1CT for new users with no funds

packages/web/components/bridge/amount-screen.tsx
For withdraw, it was assumed the symbol was used for jumping to an asset amount screen. Now, the coinMinimalDenom will also be used for finding the initial asset
[Linear Task URL](https://linear.app/osmosis/issue/FE-693/fix-flow-from-asset-info-pages)
=> (Deposit/Withdraw) Fix use of coinMinimalDenom from asset info page

packages/stores/src/account/base.ts, packages/stores/src/account/types.ts, packages/trpc/src/one-click-trading.ts, packages/types/src/one-click-trading-types.ts, packages/utils/src/gas-utils.ts, packages/web/components/navbar/index.tsx, packages/web/components/one-click-trading/__tests__/one-click-trading-settings.spec.ts, packages/web/components/tooltip/tooltip.tsx, packages/web/hooks/mutations/one-click-trading/use-create-one-click-trading-session.tsx, packages/web/hooks/one-click-trading/use-one-click-trading-params.ts, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json, packages/web/stores/index.tsx
Use the gas limit instead of OSMO as the network fee limit. This will allow us to set limits for other tokens, not just OSMO. Currently, the limit is set to 400,000,000, equivalent to 1 OSMO at today's gas price. In the future, we can lower it if needed for better protection
[Linear Task URL](jose/fe-713-remove-network-fee-adjustment-from-settings-and-set-it-to-1)
=> (1CT) Change network fee limit to use gas limit

packages/bridge/src/axelar/index.ts
Axelar provider was able to return negative output amounts in selectable quotes. This should not be possible. Axelar now throws and is not selectable if the fee exceeds the final out amount.
[Linear Task URL](https://linear.app/osmosis/issue/FE-763/prevent-negative-expected-output)
=> (Deposit/Withdraw) Axelar: throw if out amount negative

.github/workflows/frontend-e2e-tests.yml, packages/web/e2e/tests/pools.spec.ts, packages/web/e2e/tests/portfolio.wallet.spec.ts, packages/web/e2e/tests/select.spec.ts, packages/web/package.json, packages/web/playwright.config.ts
Added monocart coverage for E2E tests. Coverage report will look like this.
[UI test automation code coverage](https://linear.app/osmosis/issue/FE-185)
=> Added monocart coverage

packages/bridge/src/msg.ts, packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/squid/index.ts, packages/server/src/utils/superjson.ts, packages/utils/src/asset-utils.ts, packages/web/components/bridge/amount-screen.tsx, packages/web/components/bridge/crypto-fiat-input.tsx, packages/web/components/bridge/more-bridge-options.tsx, packages/web/components/bridge/quote-detail.tsx, packages/web/components/bridge/review-screen.tsx, packages/web/components/bridge/use-bridge-quotes.ts, packages/web/server/api/routers/bridge-transfer.ts
Squid and Skip would use cosmwasm to initiate a multi hop swap and transfer from Osmosis side to the counterparty. Before, only basic IBC transfers were encoded and provided. Now, cosmwasm contract calls are encoded and returned as sign docs to the FE.
[Linear Task URL](https://linear.app/osmosis/issue/FE-765/handle-cosmwasm-transactions-for-usdc-withdraws)
[Convert transfer fee to from asset of like variants](https://linear.app/osmosis/issue/FE-767/convert-transfer-fee-to-from-asset-of-like-variants)
[Skip: show insufficient CCTP relay fee as insufficient fee error](https://linear.app/osmosis/issue/FE-761/skip-show-insufficient-cctp-relay-fee-as-insufficient-fee-error)
[Fee subracted when not necessary](https://linear.app/osmosis/issue/FE-753/fee-subracted-when-not-necessary)
* Encode …
=> (Deposit/Withdraw) handle cosmwasm transactions

packages/web/components/bridge/use-bridge-quotes.ts
If the best quote logic never goes in to controlled (by the user) mode, there's a risk the selected quote could change while the user is confirming a tx. If the user goes forward with the tx, there's a risk the wrong status source provider could be used to track the status of the tx. This should not be possible. This PR fixes that by not setting the preferred provider while a tx is pending.
[Linear Task URL](https://linear.app/osmosis/issue/FE-780/prevent-selected-quote-from-changing-while-tx-is-pending)
* Check `isTxPending` before changing selected provider
=> (Deposit/Withdraw) Prevent selected quote from changing if tx pending

packages/web/config/ibc-overrides.ts
Add WETH Variant Deposit Overrides to Satellite so that we can properly list these assets.
They should be added to the Axelar integrated bridge, but I do not have the ability to add to it.
Add deposit and withdraw override to Satellite in ibc-overrides.ts for ETH.arb.axl, ETH.base.axl, and ETH.matic.axl
=> Add WETH Variant Deposit Overrides to Satellite

packages/web/components/alert/__tests__/prettify.spec.ts, packages/web/components/alert/prettify.ts
Following the renaming of chain errors, overspend errors are not currently being detected by our regex. This PR will resolve this issue by updating the regex to match the new errors. 
[Linear Task URL](https://linear.app/osmosis/issue/FE-778/fix-overspend-error-detection)
=> (1CT) Fix Overspend Error Detection

packages/bridge/src/axelar/index.ts, packages/bridge/src/ibc/index.ts, packages/bridge/src/skip/index.ts, packages/web/components/bridge/use-bridge-quotes.ts
It's better for bridge provider specific errors to be caught within the provider and re-propogated as a predictable error that can be handled on the client, vs handing provider-specific errors directly on the client. This helps improve end user messaging to what exactly has gone wrong given their specific input, as we can simplify the categorization of errors on the client. More types of errors we encounter from providers in the future can follow this same paradigm; we can catch the error message strings in the provider then repropogate them as some predictable category of errors. Or, we can fall back to the generic category of error: `UnsupportedQuoteError`.
[Linear Task URL](https://linear.app/osmosis/issue/FE-779/cleanup-move-bridge-specific-errors-into-providers)
* Handle CCTP errors …
=> (Deposit/Withdraw) Cleanup: move bridge specific errors into providers

packages/trpc/src/orderbook-router.ts, packages/web/hooks/limit-orders/use-orderbook.ts
These changes fix fetching of quote asset for limit orders and remove an unused query.
[FE-664: Asset Values are Incorrect on Open Orders Page](https://linear.app/osmosis/issue/FE-664/asset-asset-values-are-incorrect-on-open-orders-page)
- Altered `getAssetFromAssetList` call in `orderbookRouter.getAllActiveOrders`
=> fix: fixed quote/asset denom fetching for active orders

packages/web/components/bridge/amount-screen.tsx, packages/web/components/bridge/crypto-fiat-input.tsx, packages/web/components/bridge/use-bridge-quotes.ts
This PR modifies the adjustment of the input amount to only make the adjustment if no quotes are _loading_.
Once all quotes have resolved (succeeded or failed), only then will the input amount be adjusted to account for gas. This reduces the thrash in the quote loading process, as worse quotes won't cause the input to be adjusted if a better quote is still pending. Now, the better qoute can be realized, and then be the cause of a gas adjustment of the input amount.
This results in a less jarring UX.
[Linear Task URL](https://linear.app/osmosis/issue/FE-791/fix-max-input-loop)
* Add `canSetMax` prop to input component
* Return flag indicating if any quote provider is loading, use that to determine if max can be set
This change has been tested locally by rebuilding the website and verified …
=> (Deposit/Withdraw) Improve adjusting max input amount

packages/utils/src/api-client.ts
I've noticed in vercel logs text data responses are assumed to be objects. This checks for the data being an object using `in` operator.
Example Vercel error:
```
Fetch Error. Info: {
endpoint: 'https://stage-proxy-data-api.osmosis-labs.workers.dev/tokens/v2/mcap',
config: { method: 'GET', body: undefined },
status: 200,
exception: TypeError: Cannot use 'in' operator to search for 'code' in n/a
at (../utils/build/api-client.js:80:24)
at (../utils/build/api-client.js:5:57)
}
```
=> Api client: add object check

packages/server/src/queries/complex/orderbooks/pools.ts, packages/server/src/queries/sidecar/orderbooks.ts, packages/web/hooks/limit-orders/use-orderbook.ts
This change adds a new SQS query to identify which orderbooks to use from the frontend.
[LIM-188: Add Canonical Orderbook SQS Query](https://linear.app/osmosis/issue/LIM-188/add-canonical-orderbook-sqs-query)
- Updated `getOrderbookPools` to use a new `queryCanonicalOrderbooks` query for SQS
=> feat: added canonical orderbooks query to edge router for orderbooks

packages/server/src/queries/complex/earn/strategies.ts, packages/server/src/queries/data-services/earn.ts, packages/trpc/src/earn.ts, packages/web/components/earn/table/columns.tsx, packages/web/hooks/use-get-earn-strategies.ts, packages/web/hooks/use-strategy-table-config.ts
We wanna be able to support custom tvl, apr and balance api for each strategy, to be able to do that we need to change the current schema inside our cms:
https://github.com/osmosis-labs/fe-content/pull/86
[Linear Task URL](https://linear.app/osmosis/issue/FE-781/add-new-earn-strategy-endpoint-schema)
=> feat: add new earn strategy endpoint schema

packages/web/components/chart/light-weight-charts/utils.ts
Fix odd behavior on Y axis with extremely long scientific notation
[Linear Task URL](https://linear.app/osmosis/issue/FE-657/odd-behavior-on-y-axis-with-extremely-long-scientific-notation)
=> fix: :bug: fix y axis rendering for small prices

packages/web/components/complex/orders-history/index.tsx, packages/web/components/place-limit-tool/index.tsx, packages/web/components/place-limit-tool/limit-trade-details.tsx, packages/web/components/swap-tool/order-type-selector.tsx, packages/web/components/trade-tool/index.tsx, packages/web/config/analytics-events.ts, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/pages/index.tsx
This change adds amplitude analytics events for limit orders. The following events are included:
- Place Limit Started
- Place Limit Completed
- Place Limit Failed
- Claim All Orders Started
- Claim All Orders Failed
- Order History Page Viewed
- Buy/Sell/Swap tab selected
- Limit/Market selected
The current events for swaps were also added for market orders.
[LIM-178: Add Amplitude Analytics Events](https://linear.app/osmosis/issue/LIM-178/add-amplitude-analytic-events)
- Added limit order amplitude analytics event names
- Added event logs for limit order related events
=> feat: limit order amplitude events

packages/web/components/input/limit-input.tsx, packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/trade-details.tsx, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/modals/review-limit-order.tsx, packages/web/utils/number.ts
These changes add restrictions to the price input by limiting it to min/max price. The fiat price input is also restricted to 2 decimal places similar to the fiat amount input.
These changes also include refectching of the spot price but this needs testing in another branch for how it affects limit input.
[LIM-179: Price Input Causes Crash on Large Value](https://linear.app/osmosis/issue/LIM-179/[bug]-price-input-causes-crash-on-large-value)
=> feat: added limitations to price input to prevent erroring

packages/web/components/place-limit-tool/index.tsx, packages/web/components/place-limit-tool/limit-price-selector.tsx, packages/web/hooks/limit-orders/use-place-limit.ts
These changes redesign the price input and fix/improve the functionality. It also includes an adjustment to default state to include a percentage adjustment around the current spot price.
The state of the price is also adjusted based on refetched asset prices to keep it in sync.
[LIM-198: Price Input](https://linear.app/osmosis/issue/LIM-198/[redesign]-price-input)
[LIM-195: Validate refetching price does not cause issues with limit price](https://linear.app/osmosis/issue/LIM-195/validate-refetching-price-does-not-cause-issues-with-limit-price)
[LIM-197: Adjust default limit price to be a percentage around spot price](https://linear.app/osmosis/issue/LIM-197/adjust-default-limit-price-to-be-a-percentage-around-spot-price)
- Reworked `useLimitPrice`
- If a user inputs a percentage their …
=> [Limit Orders]: Price Input Redesign

packages/web/components/swap-tool/price-selector.tsx, packages/web/hooks/limit-orders/use-orderbook.ts, packages/web/hooks/limit-orders/use-place-limit.ts
These changes add the `enabled` flag to several limit orders related queries.
[LIM-190: Disable Orderbook Queries when Necessary](https://linear.app/osmosis/issue/LIM-190/disable-orderbook-queries-when-necessary)
- Added `enabled` flag to all limit order related queries
=> fix: removed query calls when parameters don't exist for orderbooks

packages/bridge/src/skip/index.ts, packages/bridge/src/squid/__tests__/squid-bridge-provider.spec.ts, packages/bridge/src/squid/index.ts
Some EVM counterparties would have the proper ERC20 address in the source denom. However, many EVM counterparties would contain the proper address in the address member instead. Now, if it's an EVM counterparty, we only check the address to confirm it's available in the provider's asset list. This should make even more EVM assets available from providers.
=> (Deposit/Withdraw) Fix: use address and not source denom for all EVM assets

packages/web/components/control/crypto-fiat-input.tsx, packages/web/components/input/scaled-currency-input.tsx
Currently, users have to type 0 followed by a . to enter a decimal. To improve the user experience, we can automatically add the 0 if a user starts with a dot
[Linear Task URL](https://linear.app/osmosis/issue/FE-854/typing-on-empty-input-should-automatically-add-the-0)
=> (Deposit/Withdraw) Typing . on empty input should automatically add the 0

packages/web/components/bridge/bridge-provider-dropdown.tsx, packages/web/components/bridge/quote-detail.tsx, packages/web/components/bridge/review-screen.tsx
Since tildes are always used to indicate an approximation, I disabled the inequality symbol as it communicates the same idea, but just for smaller values
[Linear Task URL](https://linear.app/osmosis/issue/FE-746/remove-tilde-from-anything-with-less-than-operator)
=> (Deposit/Withdraw) Inequality symbols

packages/web/components/complex/pool/create/cl/set-base-info.tsx
Uses the generated assetlist, instead of the mock testing assetlist
=> fix assetlist used for create concentrated liquidity modal

packages/web/e2e/tests/swap.stables.spec.ts
Added random wait for monitoring tests. 
Workflow runs 3 test instances in parallel and we do not want them to start all in the same time as tests share a wallet and can fail.
=> Added random wait for monitoring tests

packages/bridge/src/axelar/__tests__/axelar-bridge-provider.spec.ts, packages/bridge/src/axelar/index.ts, packages/bridge/src/ibc/__tests__/ibc-bridge-provider.spec.ts, packages/bridge/src/ibc/index.ts, packages/bridge/src/interface.ts, packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/squid/index.ts, packages/stores/src/account/base.ts, packages/tx/src/gas.ts, packages/web/components/bridge/amount-screen.tsx, packages/web/components/bridge/use-bridge-quotes.ts, packages/web/config/ibc-overrides.ts
Before, we were re-estimating gas fee and alt gas tokens for cosmos transaction objects coming from bridge providers. The issue with that approach is a provider could quote an alternative fee token that doesn't get chosen in our custom gas logic. This PR forwards the quoted gas token along with the cosmos transaction request which can then be passed to the wallet to ensure a consistent and accurate UX.
[Linear Task URL](https://linear.app/osmosis/issue/FE-866/cosmos-tx-include-stdfee-in-cosmostransactionrequest)
* Include gas in quote response transaction data for cosmos transactions
* Prefer transactionRequest from getQuote instead of separate getTransactionData query (for accuracy and consistency)
* Update tests
=> (Deposit/Withdraw) Include gas fee from quote in cosmos transactions

packages/server/src/queries/complex/pools/index.ts, packages/server/src/queries/complex/pools/providers/sidecar.ts, packages/server/src/queries/sidecar/pools.ts, packages/trpc/src/pools.ts, packages/web/components/swap-tool/__tests__/swap-tool.spec.tsx
Now that SQS pools query returns capitalization (TVL), we can avoid the performance issue of sending additional SQS price queries to calculate it within the edge function. This should greatly increase performance and allow us to remove the Numia indexer as a major dependency here. As a secondary consequence, pool detail pages should be more performant since SQS supports querying by individual pool ID(s), which greatly reduces the load of getting individual pools (since all pools don't need to be queried)
[FE-909 : Use SQS pools](https://linear.app/osmosis/issue/FE-909/use-sqs-pools)
* Add liquidity capitalization to SQS pools response, and remove price queries to get those values
Tested manually locally
=> Use to SQS pools provider

packages/web/components/place-limit-tool/index.tsx
Refactored and improved the buy/sell button loading and disabled states. The functionality should closely mimic the swap tab now.
[LIM-237: Buy/Sell Button Randomly Hits a Loading State for a Split Second...](https://linear.app/osmosis/issue/LIM-237/buysell-button-randomly-hits-a-loading-state-for-a-split-second-every)
- Moved disabled/loading booleans to separate memoized fields
- Hid certain errors from the button
=> [Limit Orders - V3]: Buy/Sell Button State

packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/alt.tsx, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/modals/review-order.tsx
These changes freeze limit price when the review modal is opened. It also adds adjustments to the review modal to display the correct values on a limit order.
[LIM-248: Limit Order Review Page...](https://linear.app/osmosis/issue/LIM-248/limit-order-review-page-should-not-be-updating-the-price)
[LIM-252: Limit Sell Price...](https://linear.app/osmosis/issue/LIM-252/limit-sell-price-seems-to-be-set-to-market-price-instead-of-the-actual)
- Made `ReviewOrder` props more explicit
- Added a `priceLocked` state value to price state for limit orders, this is toggled when review order is opened
=> [Limit Orders - V3]: Review Modal 

packages/web/components/bridge/amount-screen.tsx, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json, packages/web/modals/wallet-select/use-selectable-wallets.ts
When a chain is pending approval, the button should be disabled and say "pending approval"
[Linear Task URL](https://linear.app/osmosis/issue/FE-877/connect-chain-pending-approval-button-state)
=> (Deposit/Withdraw) Connect chain pending approval button state

.github/workflows/frontend-e2e-tests.yml, .github/workflows/monitoring-e2e-tests.yml, .github/workflows/monitoring-geo-e2e-tests.yml
In order to speedup test execution only upload test results on failure.
=> Upload test results on failure only

packages/web/components/place-limit-tool/index.tsx, packages/web/components/place-limit-tool/limit-price-selector.tsx, packages/web/hooks/limit-orders/use-place-limit.ts
Adjusted the price display for limit holders to account for low value prices.
[LIM-244: Custom Price Decimal Cap...](https://linear.app/osmosis/issue/LIM-244/custom-price-decimal-cap-should-be-made-to-12)
- Homogenized price display for limit price selection
- Increased price input decimal places to 12
- Fixed an issue with button not being disabled on insufficient funds for buy/sell tab
=> [Limit Orders - V3]: Limit Price Display for Low Values

packages/web/components/swap-tool/price-selector.tsx, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/modals/token-select-modal-limit.tsx, packages/web/utils/formatter.ts
These changes alter denom selections:
- Quote denoms are restricted to select assets (defined in `VALID_QUOTES` in `price-selector.tsx`)
- Quote denom balances have improved formatting ("<$0.01" for sub 1c displays)
- Base denom selection modal is a fixed position and reduced height
- Denom selection modal resets search when closing
- Refactored balance fetching for `usePlaceLimit`
=> [Limit Orders - V3]: Denom Selection Updates

.github/await_deployment.py, .github/workflows/monitoring-geo-e2e-tests.yml, packages/web/e2e/tests/swap.stables.spec.ts
- Split and order monitoring tests
- Use 2 wallets for swap tests
[Align test workflows and use more wallets](https://linear.app/osmosis/issue/FE-846)
=> Split parallel swap tests and use 2 wallets

packages/server/src/queries/complex/concentrated-liquidity/index.ts, packages/server/src/queries/complex/staking/superfluid.ts, packages/types/src/chain-types.ts, packages/utils/src/chain-utils.ts, packages/web/config/utils.ts
Newever versions of Keplr made this nullable, but our Keplr stores are from an old version of Keplr.
I don't anticipate this being an issue since we don't really use staking tokens on other chain in our FE features.
Further, most chains have staking tokens.
So, I add a placeholder token to stay compatible with the ChainInfo types that we imported into the keplr-* packages in the monorepo.
Long term, once we remove the keplr stores for good and delete that code, we can upgrade our Keplr chain type to use the newer type that tolerates missing staking tokens. Then, we can suggest chains to Keplr wallet with Staking tokens missing.
-
=> Tolerate missing staking token in chain type

packages/server/src/queries/complex/index.ts, packages/server/src/queries/complex/osmosis/epochs.ts, packages/server/src/queries/complex/pools/incentives.ts, packages/trpc/src/chains.ts, packages/trpc/src/index.ts, packages/trpc/src/params.ts, packages/web/components/overview/pools.tsx, packages/web/server/api/edge-router.ts, packages/web/server/api/local-router.ts
User tRPC instead of MobX queries for getting the epoch countdown. The changes were pretty minimal, so, we can easily remove the tRPC routers + UI component later, as I've heard we'll eventually the countdown from the pools page.
[FE-12 : Pools page: epoch countdown](https://linear.app/osmosis/issue/FE-12/pools-page-epoch-countdown)
- Add params router, which exposes cached and processed getEpochs query from complex folder
- My intention with this router is it will hold all miscellaneous Osmosis params or other queries that can't really be categorized neatly into other pools, staking, earn, assets etc. routers
- Use tRPC query instead of MobX query store in pools overview component
- Remove observer wrapper from component, since there's no more references to any MobX stores in that …
=> Migrate pools page epoch countdown to tRPC

packages/pools/src/weighted.ts
FE used to depend on amino encoding of pools.
But SQS returns app encoding.
The difference wasn't accounted for in the transition.
This PR fixes the bug around inconsistency => we need to do a proper move away from amino
=> fix: frontend bug breaking weighted LP

packages/server/src/queries/complex/assets/price/index.ts, packages/web/server/api/routers/bridge-transfer.ts
Remove source denom
Separated from:
https://github.com/osmosis-labs/osmosis-frontend/pull/3661
From discussions, it is no longer needed and is unused.
=> remove source denom

packages/web/pages/assets/[denom].tsx
https://linear.app/osmosis/issue/FE-941/alloyed-asset-composition-is-hidden
- Fix alloyed composition section rendering, now it should be available for all alloyed assets.
=> fix: :bug: fix hidden alloyed composition

packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts, packages/bridge/src/skip/index.ts
This adds a chain to explicitly pass the to chain ID to Skip createCosmosTransaction for getting timeout height on counterparty chain.
=> (Deposit/Withdraw) Fix Skip timeout height chain ID

packages/web/components/complex/asset-fieldset.tsx, packages/web/components/place-limit-tool/index.tsx
These changes adjust trade tool inputs to scale their input font sizes depending on the length of the input.
[LIM-217](https://linear.app/osmosis/issue/LIM-217/denom-selection-can-take-up-too-much-area)
[LIM-221](https://linear.app/osmosis/issue/LIM-221/when-it-hits-max-size-it-should-start-shrinking)
- Input scaling now uses font size 
- Adjusted font sizes for scaling
- Added overflow handler for denom selection taking up too much space
=> [Limit Orders - V3]: Font Scaling

packages/server/src/queries/complex/concentrated-liquidity/index.ts
* Deserialized string dec sqrt price from CL pools with BigDec type instead of Dec, to handle the given 36 dec precision
=> Increase deserialization precision

packages/bridge/src/axelar/index.ts, packages/bridge/src/interface.ts, packages/bridge/src/skip/__tests__/skip-bridge-provider.spec.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/squid/index.ts, packages/server/src/queries/complex/get-timeout-height.ts, packages/tx/src/gas.ts
There was a regression when migrating getTimeoutHeight to explicitly accept ChainIDs. If the transfer's destination chain is an EVM chain, this would clearly not work. So, this re-adds the ability to get the timeout height of a chain by bech32prefix, which will be useful for getting the Axelar timeout height for an IBC transfer from Osmosis to Axelar as the initial transfer to an EVM chain.
This also classifies an error message from Skip as an insufficient amount error.
=> (Deposit/Withdraw) Timeout height

packages/bridge/src/ibc/index.ts
In the asset list we fetch the generated chain list to get display metadata (decimals, symbol) for alt gas tokens on other chains. However, this is not populated for Osmosis since it has a dynamic fee market. This causes some alt gas tokens on Osmosis to not be returned with metadata.
Instead, if the gas token is on Osmosis (withdrawal), use the asset list instead to get gas token metadata. It will be more reliably up to date.
This could prevent some unnecessary queries of generated chain list as well, in the case of withdraws.
cc @JeremyParish69  expressed hesitation with populating Osmosis gas tokens in generated chain list
[FE-959: Use asset list for getting gas token for Osmosis](https://linear.app/osmosis/issue/FE-959/use-asset-list-for-getting-gas-token-for-osmosis)
- Check asset …
=> (Deposit/Withdraw) IBC provider: use asset list for Osmosis alt fee token metadata

packages/web/components/complex/asset-fieldset.tsx, packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/alt.tsx, packages/web/components/swap-tool/trade-details.tsx
=> feat: add test id

.github/workflows/frontend-e2e-tests.yml, .github/workflows/monitoring-e2e-tests.yml, .github/workflows/monitoring-geo-e2e-tests.yml, .github/workflows/prod-frontend-e2e-tests.yml, packages/web/e2e/pages/trade-page.ts, packages/web/e2e/tests/pools.spec.ts, packages/web/e2e/tests/select.spec.ts, packages/web/e2e/tests/swap.wallet.spec.ts
Swap tool is now part of a Trade tool and tests must be moved to new implementation.
=> Move E2E tests to a new Trade page

packages/web/components/complex/orders-history/index.tsx
These changes remove the extra vertical scroll bar from the order history page. This should become unnecessary with responsive designs.
=> fix: overflow fix for order history table

packages/web/components/bridge/use-bridge-quotes.ts, packages/web/components/control/crypto-fiat-input.tsx
- Fix the issue where the Crypto/Fiat input crypto button is not updated after fiat changes while loading.
- Fix the transfer details being hidden when the current selected provider's request fails by selecting the next viable option.
https://linear.app/osmosis/issue/FE-968/crypto-button-not-being-updated-after-fiat-changes-while-loading-and
=> (Deposit/Withdraw) Fix Crypto Fiat Input Loading and Handle Provider Request Error 

packages/web/components/bridge/quote-detail.tsx, packages/web/components/bridge/use-bridge-quotes.ts, packages/web/components/control/crypto-fiat-input.tsx
If an asset is not found in our asset list, prevent IBC hash overflow in transfer details by shortening denom and trimming placeholder zeros. 
Issue
https://linear.app/osmosis/issue/FE-953/shorten-network-fee-denom-and-remove-placeholder-values
- Shorten network fee denom
- Trim placeholder zeros
=> (Deposit/Withdraw) Shorten network fee denom and remove placeholder values

packages/web/e2e/pages/transactions-page.ts, packages/web/e2e/tests/trade.wallet.spec.ts, packages/web/e2e/tests/transactions.wallet.spec.ts
- Transaction page has only 46 swaps on it, fixed number in a test
- Canceling limit order to reduce number of open orders after the test
=> Fix trxs number and cancel limit order

packages/web/components/chart/light-weight-charts/advanced-chart.tsx, packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/alt.tsx, packages/web/components/swap-tool/order-type-selector.tsx, packages/web/components/swap-tool/price-selector.tsx, packages/web/components/swap-tool/trade-details.tsx, packages/web/components/trade-tool/index.tsx, packages/web/hooks/limit-orders/use-orderbook.ts, packages/web/hooks/use-feature-flags.ts, packages/web/modals/review-order.tsx, packages/web/pages/assets/[denom].tsx, packages/web/pages/index.tsx, packages/web/public/tradingview/custom-limit.css
These changes fix some small issues and some preferred UX changes.
[FE-996](https://linear.app/osmosis/issue/FE-996/buy-and-sell-tabs-show-atom-instead-of-asset-on-asset-info-pages)
[FE-1004](https://linear.app/osmosis/issue/FE-1004/fix-background-of-advanced-chart)
[FE-1005](https://linear.app/osmosis/issue/FE-1005/the-rate-should-be-flipped-for-better-user-experience-1-from-asset-=-x)
[LIM-270](https://linear.app/osmosis/issue/LIM-270/reverted-old-swap-modal-ux-ask-need-to-remember-last-traded-asset-pair)
- Readded the `PreviousSwap` local storage object and wired it in to new trade tool
- Fixed the advanced asset price chart background (extra CSS should be removed when feature flag removed)
- Inverted ratio ordering for swap tab
- Fixed limit orders showing wrong asset on asset page
=> [Limit Orders]: Post Launch QA 2

.gitignore, shell.nix
This PR adds proposal for minor impromevents for development UX. 
- `.gitignore` now includes temp files created/maintained by Vim editor 
- `shell.nix` provides Nix configuration that allows to run project out of the box on Nix with a singe command: `nix-shell --run 'yarn dev'`
N/A
- Updated `.gitignore`
- Created `nix.shell`
This change has been tested locally by making sure added files to `.gitignore` are properly ignored and `nix-shell --run 'yarn dev'` run application successfuly.
=> Dev env: update .gitignore, and shell.nix

packages/web/components/swap-tool/price-selector.tsx, packages/web/config/ibc-overrides.ts
To update hardcoded Asset Symbols: USDC.e.matic.axl, USDT.eth.rt, as they were inaccurate before.
Update web/config/ibc-overrides.ts to new symbols.
Update price selector USDC.matic.axl to USDC.e.matic.axl
This change has not been tested locally, because I can't run FE locally.
From what I can tell, the preview shows the updated symbol correctly:
=> Update Asset Symbol USDC.e.matic.axl, USDT.eth.rt

.github/workflows/monitoring-geo-e2e-tests.yml, packages/web/e2e/tests/monitoring.wallet.spec.ts
- Enable limit order tests for EU as a separate job
=> Enable limit order tests for EU

packages/web/e2e/tests/monitoring.wallet.spec.ts
Looks like Keplr waller sometimes fails to show human readable format for USDC, so switching to check the quantity of an order.
=> Use quantity check for limit order

packages/web/utils/service-name.ts
Use Vercel's project production URL like 'app.osmosis' or 'stage.osmosis' instead of Vercel's generated URL, but it would also fall back to the latter on stage deployments. This will improve debugging experience in DD
=> (Datadog) Use Vercel project production url

packages/bridge/src/ibc/index.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/squid/index.ts, packages/web/components/bridge/amount-screen.tsx, packages/web/hooks/limit-orders/use-place-limit.ts
[Receive incorrect Asset after Withdraw](https://linear.app/osmosis/issue/FE-990/receive-incorrect-asset-after-withdraw)
[Incredibly high bridge fee amount](https://linear.app/osmosis/issue/FE-995/incredibly-high-bridge-fee-amount)
[Only automatically switch chains in wallet when user selects a chain in the selector](https://linear.app/osmosis/issue/FE-1013/only-automatically-switch-chains-in-wallet-when-user-selects-a-chain)
=> (Deposit/Withdraw) Fixes

packages/server/src/queries/complex/osmosis/epochs.ts, packages/web/components/overview/pools.tsx, packages/web/server/api/edge-router.ts, packages/web/server/api/local-router.ts
The epochs query frequently appears as the bottleneck in profiles of the pools page refresh
This latency is unpredictable and is likely due to Vercel edge.
To mitigate this, we move the query to the local tRPC router and also 3x the cache ttl.
Given the move to local router, we can also add a `staleWhileRevalidate` cache flag which only works outside of the edge cache. With this flag and value of 500ms, an old epoch value would be returned while a new value is fetched. 
The new latency is on average si sub-300ms
Before, there would be frequent spikes > 700ms
=> perf: move epochs query to local router from edge

packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts, packages/web/hooks/ui-config/use-remove-concentrated-liquidity-config.ts
Removes some uses of legacy pools query in CL flow.
Remaining uses
* Assets (now called portfolio) page v1: for filtering pools by show dust setting
*
=> Remove some legacy pools query usage

packages/web/instrumentation.ts, packages/web/utils/service-name.ts
- Add osmosis-frontend-dev service name
- Remove osmosis-frontend-preview service name
- Add env:stage attribute
https://linear.app/osmosis/issue/FE-1036/datadog-improvements
=> (Datadog) Add dev service and disable otel in previews 

packages/web/components/complex/pools-table.tsx
Before
After
https://linear.app/osmosis/issue/FE-967/ui-elements-overlap-when-browser-window-is-slightly-wider-than-half-of
=> (Token Details) Hide APR column if there's no available space

packages/web/e2e/tests/swap.wallet.spec.ts
Limit orders sell 1$ of ATOM and buy 1$ of OSMO. So, we need to move some OSMO back to ATOM.
- Swap more OSMO to ATOM
=> Swap more OSMO to ATOM

packages/web/hooks/evm-wallet.ts, packages/web/modals/wallet-select/use-selectable-wallets.ts
Before
After
https://linear.app/osmosis/issue/FE-1016/double-wallet-issue-not-addressed-keplr-logos-look-different
=> (Deposit/Withdraw) Display Keplr EVM correctly

packages/web/components/place-limit-tool/index.tsx, packages/web/hooks/limit-orders/use-place-limit.ts
These changes fix a bug with placing limit orders if the market input is empty. The default input for the sell tab is now fiat and the available balance display changes with the input selected.
=> [In Given Out]: Default input adjustments

packages/web/modals/review-order.tsx
Enables slippage warning when dynamic slippage goes too high
=> feat: added slippage warning for default too high

packages/web/components/complex/portfolio/open-orders.tsx, packages/web/components/complex/portfolio/portfolio-page.tsx, packages/web/components/transactions/recent-activity/recent-activity.tsx, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
- add limit orders to portfolio page
https://linear.app/osmosis/issue/FE-784/portfolio-v2-open-orders
https://linear.app/osmosis/issue/FE-1044/portfolio-v2-show-up-to-5-open-orders
- add top 5 recent open limit orders to portfolio page
- add to new section, with link to limit orders on transactions page
- responsive
- i18n
=> Mattupham/fe 784 portfolio v2 open orders / limit orders

packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/alt.tsx, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/hooks/use-estimate-tx-fees.ts, packages/web/hooks/use-swap.tsx
These changes correct the input value for limit orders on the buy tab
=> fix: remove logs and correct limit input amount

packages/server/src/queries/blockaid/transaction.ts, packages/web/pages/api/transaction-scan.ts
Adding `account_address` to the txn scan endpoint, to match the API by request from blockaid
See:
https://docs.blockaid.io/reference/cosmos_scan_transaction_v0_transaction_scan__post
=> feat: add account address to txn scan endpoint

packages/server/src/queries/complex/orderbooks/pools.ts, packages/trpc/src/orderbook-router.ts, packages/web/components/complex/orders-history/index.tsx, packages/web/hooks/limit-orders/use-orderbook.ts
These changes restrict the amount of orderbooks available in the FE while we create a solution for the orders query.
=> Restrict Orderbook Amount 

.github/workflows/monitoring-geo-e2e-tests.yml, .github/workflows/prod-frontend-e2e-tests.yml, packages/web/e2e/tests/monitoring.wallet.spec.ts, packages/web/e2e/tests/trade.wallet.spec.ts, packages/web/e2e/tests/transactions.wallet.spec.ts, packages/web/playwright.config.ts
- Enabled Trade for US
- change token amount to USD amount
- fix order locator
- fix wallet message check
=> Enabled Trade for US and update locators

packages/bridge/src/ibc/index.ts, packages/bridge/src/nitro/index.ts, packages/bridge/src/squid/index.ts
In the IBC provider, the gas token was checked with only one comparison denom being cast to lower case. This was generally not an issue because we would then query the generated chain list to check for gas tokens there. However, for some Osmosis gas tokens, this caused the queried gas token denom to not be found in the asset list. With that, this bug would only be present if the generated asset list also does not contain the denom.
- Cast denoms to lower case before comparison for getting Osmosis gas token in IBC bridge provider
Tested locally
=> Deposit/Withdraw: IBC provider: fix Osmosis gas asset list denom check

packages/web/components/place-limit-tool/index.tsx, packages/web/e2e/tests/trade.wallet.spec.ts
These changes adjust the following for the buy/sell tab:
- Non focused token amount restricted to 10 decimals (only when non-focused)
- Sell tab fiat input now rounds up to avoid payment fiat value not matching fiat input amount for limit orders
=> [Trade Tool]: Small QA Fixes

.github/workflows/frontend-e2e-tests.yml
To make sure there are no orders in Claim all we need to run claim tests as part of the CI/CD
- Added generic claim tests job to a preview
=> Added generic claim tests job to a preview

packages/web/components/assets/price.tsx
- update price so when "isFlat", show up arrow + 0.0% instead of "-", to match coinmarketcap
https://linear.app/osmosis/issue/FE-1042/portfolio-v2-update-0percent-change-values-to-be-green-and-up
- update threshold for isBearish / isBullish
change vs prod
=> Update price change for - values, should be up arrow with 0.00

packages/bridge/src/skip/client.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/skip/transfer-status.ts, packages/bridge/src/squid/index.ts
[Context](https://osmosis-network.slack.com/archives/C046V54UZC6/p1724714961228419)
Skip has requested that we start using an API key. The `SKIP_API_KEY` has been added to Vercel, and @osmosis-labs/front-end devs need to add it to their `.env.local`. Reach out to @niccoloraspa for the key.
=> Add Skip API key

.github/workflows/monitoring-limit-geo-e2e-tests.yml, .github/workflows/monitoring-swap-geo-e2e-tests.yml
- Split limit orders and swaps monitoring
- Run swaps every 25 minutes to avoid collision with limits
- Run limits every hour
=> Split Limit orders and swaps

packages/web/components/complex/orders-history/index.tsx
These changes fix some spacing issues on the claimable orders row and the status indicator when an order is filled.
[FE-1076](https://linear.app/osmosis/issue/FE-1076/fix-odd-spacing-issues-in-claim-all-flow)
=> [Limit Orders]: Claimable Orders Row Spacing

packages/web/hooks/use-swap.tsx
These changes fix an issue when a coin with 0 decimal places is used for a quote.
[FE-1073](https://linear.app/osmosis/issue/FE-1073/%5Bhttpsforumosmosiszonetissue-with-boot-token-accessibility-on-the)
- Altered `tokenInCoinDecimals/tokenOutCoinDecimals` check to check type rather than existence
=> fix: BOOT token invalid swaps

.gitignore, packages/web/e2e/pages/pools-page.ts, packages/web/e2e/unzip-extension.ts
- Updated Keplr wallet version
- wait for OSMO/USDC pool for 10 seconds
=> Updated Keplr wallet and more time for pools to load

.github/workflows/pr-notification.yml
Adding a yaml file to auto notify slack when someone opens a PR to master
https://linear.app/osmosis/issue/FE-1048/add-github-action-to-automatically-post-to-deployment-announcements
- add yaml file to auto notify slack when someone opens a PR to master
=> add pr notification yaml

packages/server/src/queries/complex/orderbooks/active-orders.ts, packages/web/components/complex/orders-history/index.tsx
After merging Limit Order related PRs the date display for active orders when fetched from a node was incorrect. There was also a minor issue with the historical orders not using a correct unix timestamp.
[FE-1084](https://linear.app/osmosis/issue/FE-1084/fix-incorrect-date-display-of-jan-21-1970)
- Fixed date conversion for active orders when fetched from node
=> [Limit Orders]: Fix date display for active orders from node

.github/workflows/monitoring-claim-orders .yml, packages/web/e2e/tests/select.spec.ts
- Less alerts from claim workflow
=> Less alerts from claim workflow

packages/bridge/src/skip/__tests__/skip-transfer-status.spec.ts, packages/bridge/src/skip/client.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/skip/transfer-status.ts, packages/web/pages/api/skip-track-tx.ts, packages/web/pages/api/skip-tx-status.ts, packages/web/stores/root.ts
This PR refactors the Skip TransferStatusProvider to dep-inject the tx status and track endpoints so that we can create serverless functions that utilize the credentialed SkipApiClient on the server.
Also, I refactored the trackTransaction POST call to skip to be within a catch clause instead of a try catch statement. This makes it slightly more readable as there's less jumping around when interpreting the logic related to prompting Skip to track transactions before continuing the polling.
- Added "SkipStatusProvider" as param to Skip's transfer status provider
- Added 2 serverless functions for Skip's tx status and track API calls. Utilizes the existing SkipApiClient which makes use of the Skip API key
Tested locally with Skip transfers in the deposit/withdraw flow, verifying that …
=> Use Skip API key with tx status endpoints

packages/bridge/src/skip/__tests__/skip-transfer-status.spec.ts, packages/bridge/src/skip/client.ts, packages/bridge/src/skip/index.ts, packages/bridge/src/skip/transfer-status.ts, packages/web/pages/api/skip-track-tx.ts, packages/web/pages/api/skip-tx-status.ts, packages/web/stores/root.ts
* Use Skip API key for status polling
=> Publish Stage

packages/proto-codecs/src/codegen/osmosis/concentratedliquidity/v1beta1/tx.ts, packages/stores/src/account/amino-converters.ts, packages/stores/src/account/base.ts
Due to the v0.50 upgrade there were some changes with how signing works,
This only effects the proto fields defined as `"cosmossdk.io/math.LegacyDec"`
Before the FE was signing something like "123.123456789123456789" where it should be signing "123123456789123456789".
The PR fixes the most used messages so end users can now use ledgers to sign withdraw position messages on the FE.
- create a cl position in any cl pool
- withdraw a position :tada: 
Other tests of note:
- please test ledger as well :pray:
=> fix: amino signing for withdraw position message

packages/stores/src/account/osmosis/index.ts
Fixes [FE-1089: Troubleshoot error removing lp from pool 1016](https://linear.app/osmosis/issue/FE-1089/troubleshoot-error-removing-lp-from-pool-1016)
- If the amount is high precision, increase default slippage tolerance
Tested locally
=> Fix: increase exit pool slippage with high precision amounts

packages/stores/src/account/amino-converters.ts
This PR resolves an issue with unbonding from a weighted pool by updating the proto codecs. The update ensures that the coins array is excluded when it’s empty, as the new version of the SDK does not support empty arrays. The bug was introduced following the upgrade to Cosmos SDK after the Osmosis v26 upgrade.
https://linear.app/osmosis/issue/FE-1143/fix-pool-creation-and-unboding-weighted-pools-tx
=> Fix: Unbond from weighted pools TX

README.md, packages/server/src/queries/coingecko/index.ts, packages/web/hooks/use-feature-flags.ts
This PR improves the onboarding process by addressing issues related to the initial build when environment variables have not been set up. Specifically, we replaced the hardcoded Osmosis API URL, which requires an API key, with a fallback to the free Coingecko API. While the Coingecko API has rate limits, it is sufficient for initial onboarding and short-term contributions to the code base.
Additionally, this PR updates the default feature flags to display a more up-to-date UI that aligns closely with the current production version. The README has also been updated to streamline the first installation and dev server setup. With these improvements, setting up the code base is now as simple as following the included instructions.
https://linear.app/osmosis/issue/FE-1146/improve-osmosis-fe-on …
=> feat: Improve codebase Onboarding

packages/web/config/feature-flag.ts
With allBTC being made canonical, this swaps out the "Favourite" WBTC entry for BTC
It also reorders the assets to place more emphasis on BTC and ETH trading
N/A
Edits list of swap favourites
This change has not been tested locally
=> Swap WBTC for BTC favourite + reorder

packages/bridge/src/interface.ts, packages/server/src/queries/complex/get-timeout-height.ts, packages/stores/src/account/amino-converters.ts, packages/web/stores/transfer-history.tsx
This PR fixes TIA withdrawal issues. The problem occurred because the TIA chain returns 0 as the revision number, causing transactions to fail. After implementing the decimal fix, the revision number was re-added to the transaction after normalizing the message. This fix updates the amino converters to omit the revision number if it’s 0
https://linear.app/osmosis/issue/FE-1164/error-withdrawing-tia-due-to-unauthorized-transaction
=> fix: TIA withdraws

packages/web/components/place-limit-tool/index.tsx, packages/web/components/swap-tool/alt.tsx, packages/web/config/swap.ts, packages/web/hooks/ui-config/use-slippage-config.ts
Change default slippage from `0.5%` to `0.1%` 
https://linear.app/osmosis/issue/FE-1131/review-default-slippage-percentage-setting-in-system
=> (Swap) Decrease Default Slippage

packages/stores/src/account/amino-converters.ts
To fix the POL withdrawal issue, update the amino converters to include the timeout_timestamp. The absence of this field caused a mismatch between the signed amino message and the original message.
https://linear.app/osmosis/issue/FE-1174/error-encountered-when-withdrawing-pol
-  [ ] Can withdraw POL
=> (Deposit/Withdrawal) Fix Withdrawing POL

packages/stores/src/account/amino-converters.ts
https://linear.app/osmosis/issue/FE-1183/all-withdraws-are-failing-working-fine-on-prod
- Only add `timeout_stamp` in transfer transaction only when it's available
=> (Deposit/Withdraw) Fix withdrawals

packages/tx/src/__tests__/gas.spec.ts, packages/tx/src/gas.ts
We have experienced instabilities with the base fee query. To avoid debugging its stability
for the sake of time, we have opted in to increase the base fee multiplier to 1.65 from the original
value of 1.5 which was equal to the gas multiplier. The update was applied on 2024-10-27.
More context: https://osmosis-network.slack.com/archives/C06QAMXGTJ5/p1730045591060839
=> Increase base fee multiplier from 1.5 to 1.65

.github/workflows/frontend-e2e-tests.yml, .github/workflows/prod-frontend-e2e-tests.yml
=> Updated Prod E2E tests workflow

.github/workflows/frontend-e2e-tests.yml, .github/workflows/prod-frontend-e2e-tests.yml, packages/server/src/queries/complex/portfolio/__tests__/allocation.spec.ts, packages/server/src/queries/complex/portfolio/allocation.ts, packages/web/e2e/tests/monitoring.limit.wallet.spec.ts, packages/web/e2e/tests/monitoring.market.wallet.spec.ts, packages/web/e2e/tests/portfolio.wallet.spec.ts
- [Fix: check for 0 before division](https://github.com/osmosis-labs/osmosis-frontend/commit/15f2180ee066f9fc3c9e166fa3e9bd39879b2f5b)
- [Monitoring: Increase order amounts](https://github.com/osmosis-labs/osmosis-frontend/commit/490c50281dc6caf4d91c7ccb0aca962dc8a36dd2)
- [Updated Prod E2E tests workflow](https://github.com/osmosis-labs/osmosis-frontend/pull/3922/commits/780e00a6980a9efd046f86cb83ad5031f1e12154)
=> Publish Stage PR

packages/web/package.json, yarn.lock
Without these dependencies the project won't start on `yarn dev`.
I have left the `use-debugger-hooks` in place, because I have found it to be useful when debugging — given the nature of the package usage of it won't be visible in the codebase. 
The prettier plugin for tailwind also seemed to be useful, but it probably wasn't used. 
This is a fixup for the knip commit.
- clone 
- yarn
- yarn dev
=> 🏃 It's Good To Be Running: Fix `yarn dev` on fresh install

packages/bridge/src/squid/transfer-status.ts, packages/web/components/bridge/review-screen.tsx, packages/web/components/bridge/use-bridge-quotes.ts, packages/web/stores/transfer-history.tsx
https://linear.app/osmosis/issue/FE-1207/truncate-decimals-to-a-maximum-of-6-digits
=> (Deposit/Withdraw) Truncate decimals to a maximum of 6 digits in transfer toast and better Squid transfer status error handling

packages/web/components/complex/all-pools-table.tsx, packages/web/components/control/checkbox-select.tsx, packages/web/components/layouts/main.tsx, packages/web/pages/index.tsx
We originally set a fixed height for the entire app layout, which conflicted with Headless UI’s behavior of locking the scroll when a dropdown menu is open. The solution is to remove this fixed height. This change shouldn’t impact other parts of the app, as containers dynamically adjust their height based on their contents. Moreover, setting a fixed height is generally best avoided unless necessary.
I noticed this height adjustment was specifically added for the swap tool page, so I moved it to that page to avoid breaking the its layout.
https://linear.app/osmosis/issue/FE-1219/pools-page-dropdown-jumping-to-top-of-page
=> (Pools) Fix pools dropdown jumping to top of page

packages/web/config/generate-lists.ts, packages/web/config/utils.ts, packages/web/next-env.d.ts, packages/web/utils/codegen.ts
Previously, we disabled caching to avoid token image conflicts when switching environments. However, since waiting for image downloads to start the server is time-consuming and tedious, we propose creating a lock file inside the generated folder. This lock file will store the current asset list hash and override the cache if the hash changes.
https://linear.app/osmosis/issue/FE-1228/create-lock-file-to-manage-asset-list-images-cache
=> (DevX) Create lock file to manage asset list image cache

packages/web/components/table/portfolio-asset-balances.tsx, packages/web/hooks/__tests__/use-convert-variant.test.ts, packages/web/hooks/use-convert-variant.ts
Add more user protection imposing a limit on price impact when converting non-alloy variants, such as USDC.
If the _amounts_ in vs out differ by more than 5% in the quote, block the conversion tx from being possible. Since we're converting like kinds, we can assume the amounts (with respective decimals in place) should be about the same. This is instead of comparing USD values, which may not be accurate if there's issues getting prices.
Hot fix.
- Include in/out amount diff slippage check in isError flag
Tested small change locally
=> Convert variants: check for large difference in amount

packages/web/components/assets/highlights-categories.tsx, packages/web/components/table/asset-info.tsx, packages/web/pages/index.tsx
https://github.com/user-attachments/assets/a08c5479-fc08-4d22-bc6a-050f20a0a4a9
https://linear.app/osmosis/issue/FE-1229/add-trending-tab-to-the-trade-page
=> (Swap Tool) Add top gainers

packages/web/components/cards/my-position/__tests__/expanded.spec.tsx, packages/web/components/cards/my-position/expanded.tsx
https://linear.app/osmosis/issue/FE-1231/increase-significant-figures-for-btc-in-current-assets-field
- Increase max decimals to 6 in CL asset info component
=> (CL) Increase max decimals in position cards

packages/types/src/feature-flags-types.ts, packages/web/components/assets/highlights-categories.tsx, packages/web/config/analytics-events.ts, packages/web/hooks/use-feature-flags.ts, packages/web/next-env.d.ts, packages/web/pages/index.tsx
We want to measure the impact of adding the top gainers section in the swap/trade page in osmosis. 
https://linear.app/osmosis/issue/FE-1234/amplitude-or-add-swap-check-top-gainers-event
- Add feature flag for top gainer in swap tool
- Add ampli event
=> (Swap tool) Add top gainer ampli event and add feature flag

packages/web/hooks/use-swap.tsx
https://linear.app/osmosis/issue/FE-1236/1ct-fix-insufficient-osmo-popping-up
=> (1CT) Enable other fee tokens for 1-Click Trading

packages/stores/src/account/base.ts, packages/web/hooks/limit-orders/use-place-limit.ts, packages/web/hooks/use-swap.tsx
Due to the payload limit of Ledgers, it is sometimes impossible to initiate 1CT and perform a swap within the same transaction. As a result, we need to sign each tx individually when using a Ledger
https://linear.app/osmosis/issue/FE-1253/handle-ledger-1ct-activation-from-swap-review
=> (1CT) Split txs for Ledger in swap review modal

packages/web/components/bridge/deposit-address-screen.tsx, packages/web/components/nomic/nomic-pending-transfers.tsx, packages/web/components/one-click-trading/one-click-remaining-time.tsx, packages/web/hooks/mutations/one-click-trading/use-create-one-click-trading-session.tsx, packages/web/stores/__tests__/transfer-history.spec.tsx, packages/web/stores/transfer-history.tsx, packages/web/utils/__tests__/date.spec.ts, packages/web/utils/date.ts
Currently, the “humanize time” function only displays the remaining hours, ignoring the minutes. This can be misleading, as a duration like 3 hours and 59 minutes is displayed simply as 3 hours. 
https://linear.app/osmosis/issue/FE-1257/improve-humanize-time-accuracy
=> Improve humanize time accuracy

.github/workflows/monitoring-limit-geo-e2e-tests.yml
To make sure only one private key used per geo zone.
=> Use one pk per zone

packages/web/components/place-limit-tool/index.tsx
These changes hide the "Insufficient Balance" warning when no wallet is connected in the Buy/Sell tabs.
[FE-1259](https://linear.app/osmosis/issue/FE-1259/only-show-insufficient-balance-error-when-wallet-connected)
- Added exception to hide `"limitOrders.insufficientBalance"` errors when no wallet connected
Manually tested with/without wallet connected
=> fix: hide insufficient balance when no wallet connected

.github/workflows/frontend-e2e-tests.yml, .github/workflows/monitoring-e2e-tests.yml, .github/workflows/monitoring-limit-geo-e2e-tests.yml, .github/workflows/prod-frontend-e2e-tests.yml, packages/e2e/pages/trade-page.ts
Use sparse checkout for e2e tests to save 1-2 minutes on setup.
=> Use sparse checkout for e2e tests

packages/bridge/src/ibc/__tests__/ibc-bridge-provider.spec.ts, packages/bridge/src/ibc/index.ts
The old URL (with 'geo' in it), is geoblocked, and trying to connect a wallet just goes right to their '/blocked' page (at least for a few countries like UK and Canada, probably US, too). The app.tfm.com does not do this, and allows connecting to a wallet.
- updates packages/bridge/src/ibc/index.ts:: literally ONLY the tfm URL (1 line of code)
- - also updates a test based on that. (1 line of code)
This change has not been tested locally, because I can't run FE locally.
But I've validated on the generated Vercel build here in this PR (success!).
=> Update TFM External Interface URL

packages/server/src/queries/complex/pools/providers/sidecar.ts, packages/server/src/queries/sidecar/pools.ts, packages/web/components/pages/asset-info-page/pools.tsx
Fixes filtering pools by denom name to use dedicated filter inside assets page instead of leveraging search feature for more precise results
BE-664
- Reverts https://github.com/osmosis-labs/osmosis-frontend/pull/3993
- Passes denoms filter to SQS
=> BE-664 | Fix: filter pools by denom in assets page

packages/tx/src/__tests__/events.spec.ts, packages/tx/src/events.ts
The gas estimation function is incorrectly treating unrelated input tokens as coins spent due to multi-hop swaps, which include these tokens in the spending calculation. This caused unexpected behavior where the swap tool ignored unrelated gas tokens during multi-hop swaps. To resolve this, we should rely on the token_swapped event to determine the input amount and confirm whether the gas amount is subtractive.
https://linear.app/osmosis/issue/FE-1275/improve-gas-amount-estimation-reliability-for-multi-hop-swaps
=> (Swap tool) Improve gas amount estimation reliability for multi-hop swaps

packages/e2e/tests/monitoring.market.wallet.spec.ts
While WBTC pool gas estimate often fails in SQS, we should use BTC instead on WBTC.
=> Use BTC over WBTC in monitoring

packages/web/utils/trpc.ts
On prod we wanna invalidate some old cache, it seems like we accumulated a lot of old cache that cause some performances delays.
-
-
=> feat: :sparkles: change cache buster to invalidate old cache

packages/web/components/complex/add-conc-liquidity.tsx, packages/web/components/complex/pools-table.tsx, packages/web/components/complex/portfolio/user-positions.tsx, packages/web/hooks/ui-config/use-add-concentrated-liquidity-config.ts, packages/web/hooks/ui-config/use-historical-and-depth-data.ts, packages/web/modals/add-liquidity.tsx, packages/web/pages/pool/[id].tsx, packages/web/server/api/local-router.ts
Moves pools router into local tRPC router for following methods:
- `getPools`
- `getPool`
https://linear.app/osmosis/issue/FE-1281/move-pools-router-into-local-trpc-router
- Imported existing poolsRouter into local-router
- Replaced in the source code to use local router for  `getPools`, `getPool` instead of egde
=> FE-1281 | Move pools router into local tRPC router

packages/server/src/queries/complex/pools/env.ts, packages/web/config/feature-flag.ts
Adding the 3 other contract uploads for Transmuter pools so that these can be filtered out in the pools list if wanted.
Transmuter 1.0 already listed
Transmuter 2.0 was never instantiated
This adds 3.0, 3.1 and 3.2 which are the alloyed asset pools - but also are transmuters and often dominate the volume charts.
=> Add Transmuter Contract Codes

packages/server/src/queries/complex/transactions/transactions.ts, packages/server/src/queries/data-services/transactions.ts, packages/web/server/api/local-router.ts
The `/v2/txs/{address}` endpoint currently retrieves all transaction messages, including those not relevant to specific use cases. This has led to issues with empty pages in the transaction history table due to the inclusion of unused message types.
To address this we'll use the messageType filter now that the txs endpoint supports filtering transactions using query parameters. 
https://linear.app/osmosis/issue/FE-1288/use-new-numia-messagetype-filter-to-avoid-polluting-transaction
=> (Transaction History) Use new Numia messageType filter to avoid polluting transaction history list

packages/server/src/queries/complex/assets/price/providers/sidecar.ts, packages/web/components/bridge/amount-screen.tsx, packages/web/components/bridge/bridge-wallet-select-modal.tsx, packages/web/components/bridge/deposit-address-screen.tsx, packages/web/components/input/textarea-box.tsx, packages/web/components/nomic/nomic-pending-transfers.tsx, packages/web/localizations/de.json, packages/web/localizations/en.json, packages/web/localizations/es.json, packages/web/localizations/fa.json, packages/web/localizations/fr.json, packages/web/localizations/gu.json, packages/web/localizations/hi.json, packages/web/localizations/ja.json, packages/web/localizations/ko.json, packages/web/localizations/pl.json, packages/web/localizations/pt-br.json, packages/web/localizations/ro.json, packages/web/localizations/ru.json, packages/web/localizations/tr.json, packages/web/localizations/zh-cn.json, packages/web/localizations/zh-hk.json, packages/web/localizations/zh-tw.json
Implement the following feedback items from the design team: 
- Missing QR code close trigger
- 0% fees → “Free”, and Remove 0% altogether in collapse header
- “Continue” button text → “Confirm amount”
- Address modal title → “Enter Bitcoin address”
- “Done” button in address modal feels non-standard size and style
- Line-heights too large in address input
https://linear.app/osmosis/issue/FE-1278/nomic-feedback
=> (Deposit/Withdraw) Address design feedback for Bitcoin deposits and withdrawals

packages/web/components/chart/historical-chart.tsx, packages/web/components/chart/historical-volume-chart.tsx, packages/web/components/chart/light-weight-charts/chart.tsx
Current onCrosshairMove triggers multiple times for small mouse movements even if the mouse is kept on the same data point. Added an event that triggers only when the logical data point id changes
Fixes an "infinite render" that in reality was an hover event triggered each millisecond the mouse was hovering the element instead of triggering on enter
https://linear.app/osmosis/issue/FE-1272/fix-infinite-rendering-of-portfolio-chartheader-in-osmosis-fe
- Create new higher level event in the Chart base component
- Used said event for historical-chart and portfolio historical chart
The other charts did not display such an issue because they update a mobx store that was filtering rerenders when no data was changed. That said it is best to implement this new event at the base chart and use it …
=> fix: :lipstick: Add new chart event onDataPointHover that triggers only on data point change

packages/server/src/queries/complex/assets/market.ts, packages/trpc/src/assets.ts, packages/web/components/navbar-osmo-price.tsx
This PR fixes navbar OSMO price discrepancies on the token info page during periods of market volatility
https://linear.app/osmosis/issue/FE-1284/investigate-price-inconsistencies-in-sidebar-and-chart-header
=> (Navbar) Use token info api endpoint to get navbar OSMO price

packages/web/hooks/one-click-trading/use-one-click-trading-swap-review.ts, packages/web/modals/review-order.tsx
1CT add-authenticator message is added to every mobile transaction even though there is no option to enable this on mobile browsers.
https://linear.app/osmosis/issue/FE-1301/do-not-add-the-authenticator-message-if-the-1ct-swap-tool-is-hidden
=> (1CT) Do not add the authenticator message if the 1CT swap tool CTA is hidden

packages/web/components/chart/asset-breakdown.tsx, packages/web/components/pool-detail/base-pool.tsx
Before
After
https://linear.app/osmosis/issue/FE-1293/incorrect-pool-liquidity-display-on-mobile-for-pool-1942
=> (Pool details) Hide pool weights for concentrated pools in mobile

packages/web/pages/earn/index.tsx
due to `useEffect` we invoke the event for visiting the earnPage too many times, this PR fixes this error
https://linear.app/osmosis/issue/FE-1302/amplitude-or-issue-with-emission-of-earn-and-assets-pages-page-viewed
- Replace `useEffect` with `onLoadEvent` using `useAmplitudeAnalytics` hook
=> fix: :bug: fix EarnPage.pageViewed event logs

packages/web/components/bridge/amount-and-review-screen.tsx, packages/web/components/bridge/amount-screen.tsx
This PR fixes the issue of non-Cosmos chains not being selectable in the Deposit/Withdraw flow, which blocks users from proceeding with assets like ICP. It ensures these chains can be selected by skipping provider queries and directly suggesting external bridge interfaces.
https://linear.app/osmosis/issue/FE-1298/need-to-be-able-to-transfer-assets-with-non-cosmos-counterparties
=> (Deposit/Withdraw) Show external URLs when assets has no supported chains

packages/web/hooks/use-amplitude-analytics.ts
Right now due to uBlock or stuffs like that, our request to amplitude are blocked for some users, this create a lot of missing data in our metrics. This PR should address this issue by using a domain proxy!
https://linear.app/osmosis/issue/FE-1233/amplitude-or-using-proxy-to-redirect-event-logs-to-amplitude
-
-
=> feat: :sparkles: add amplitude domain proxy

.vscode/settings.json, packages/server/src/queries/complex/assets/market.ts
We use prices from the Numia tokens endpoint only for the assets table. This helps keep the table performant since we don't also have to send batch price queries to SQS in addition to the asset info query.
This reduces the cache time so that prices are kept more up to date during high volatility.
- 5mins > 1min
Tested locally
=> Assets table: reduce market asset cache

packages/e2e/package.json, packages/e2e/tests/monitoring.limit.wallet.spec.ts, packages/e2e/tests/monitoring.market.wallet.spec.ts, packages/e2e/tests/monitoring.swap.wallet.spec.ts, packages/e2e/tests/swap.osmo.wallet.spec.ts, packages/e2e/tests/swap.usdc.wallet.spec.ts, packages/e2e/unzip-extension.ts, yarn.lock
- Added test result to GH Annotations
- Up Keplr to 12.177
=> Added test result to GH Annotations

packages/web/modals/fiat-on-ramp-selection.tsx, packages/web/modals/fiat-ramps.tsx
- [Temporary hide Moonpay](https://github.com/osmosis-labs/osmosis-frontend/pull/4038)
=> Temporary hide Moonpay (#4038)

packages/server/src/queries/complex/assets/price/historical.ts, packages/server/src/queries/data-services/token-historical-chart.ts, packages/trpc/src/assets.ts, packages/web/hooks/ui-config/use-asset-info-config.ts, packages/web/pages/assets/[denom].tsx, packages/web/utils/trading-view.ts
Numia has been making good progress on real-time asset price charts, but now that caching has been removed for real-time charts, this could create significant overhead on their infrastructure and potentially introduce latency without adding real value.
To mitigate this, we need to differentiate traffic sources by adding a `realtime=true` flag to the main chart requests on the asset details page. This will allow us to keep the main chart realtime while caching the smaller charts for a short period, similar to the previous behavior. This approach ensures that our services remain performant and scalable while maintaining real-time updates where necessary.
https://linear.app/osmosis/issue/FE-1333/add-realtime-search-parameter-to-asset-chart-on-the-token-details-page
- Add `realtime` flag to …
=> (Token Info) Add Realtime flag to assetHistoricalPrice

packages/tx/src/gas.ts, packages/web/components/complex/portfolio/assets-overview.tsx, packages/web/stores/index.tsx
This PR resolves an issue with the portfolio balance display in the Numia chart. Previously, an incorrect total balance calculation caused discrepancies between the displayed and actual portfolio values. To ensure accuracy, we now append the SQS total value to the last data point, keeping the portfolio data up to date after transactions.
https://linear.app/osmosis/issue/NUMIA-120/get-total-balance-from-last-datapoint-in-numia-chart
=> Get total balance from last datapoint in numia chart

.github/workflows/monitoring-limit-geo-e2e-tests.yml
- add condition to run jobs on success or failure in monitoring workflow
=> fix: add condition to run jobs on success or failure in monitoring workflow

packages/web/components/pages/asset-info-page/pools.tsx
Fix Asset Detail link to Pools Search Parameter
It added an equals sign that broke the search
https://linear.app/osmosis/issue/FE-1330/see-all-pools-link-on-assets-page-error
- Removed the equals sign from the search parameter in the See Pools link in the Asset Detail Page
This change has not been tested locally, but it was tested just in this preview Vercel deployment because it was a 1-line change.
And it works!
=> fix: Fix Asset Detail link to Pools Search Parameter

packages/web/server/api/routers/bridge-transfer.ts
For transferFees through bridge use returned decimals if present
Thanks to @deividaspetraitis for helping me figure it out!
Every time a quote for a bridge is requested we use the returned decimals for fees instead of the parent variant one
- Use quote decimals if available for bridges
Tested on
=> fix: Use decimals from quote if present otherwise use parent assets decimals

packages/server/src/queries/complex/assets/price/index.ts, packages/stores/src/account/utils.ts, packages/web/server/api/routers/bridge-transfer.ts
Fix the following error when depositing Initita:
Broadcasting transaction failed with code 8 (codespace: ). Log: pubKey does not match signer address init1... with signer index: 0: invalid pubkey.
https://linear.app/osmosis/issue/FE-1355/pubkey-does-not-match-signer-address-error-on-ibc-transfers-for-initia
=> fix: Initia Deposits

packages/server/src/queries/sidecar/router.ts
When doing a swap exact amount out (specifying the exact token amount to receive), the router was incorrectly using `in_amount` instead of `out_amount` for the initialAmount property in the split response. This caused incorrect calculations, resulting in small amounts received.
https://linear.app/osmosis/issue/BE-733/frontend-issue-with-incorrect-amounts-when-swapping-to-alldym
=> Fix Incorrect Amount When Swapping Exact Amount Out

packages/web/components/swap-tool/trade-details.tsx
Omits tilde symbol from the price impact since it makes the number harder to read and understand when it's negative.
Omits leading tilde symbol from the price impact since it makes the number harder to read and understand when it's negative.
[BE-747](https://linear.app/osmosis/issue/BE-747/verify-if-price-impact-field-sign-was-changed-in-frontend)
Updates packages/web/components/swap-tool/trade-details.tsx to omit leading tilde symbol near the price impact.
<!-- _(Please pick either of the following options)_ --!>
=> BE-747 | Omit leading tilde symbol from the price impact

packages/bridge/src/int3face/index.ts, packages/bridge/src/int3face/queries.ts, packages/bridge/src/wormhole/index.ts, packages/web/utils/bridge.ts
Solana-based tokens without supported bridge providers now redirect to our portal widget in /wormhole.
=> Update wormhole bridge redirect path

packages/web/components/bridge/use-bridges-supported-assets.ts
Specify XRPL EVM as the default network for XRP transfers.
- Update use-bridges-supported-assets.ts to specify a default network for XRP transfers.
This change has been tested using the Vercel build
Alternatively, I could remove the check for transfer direction, since it should apply to both withdraw and deposit
=> XRPL EVM as the default network for XRP

packages/tx/src/__tests__/gas.spec.ts, packages/tx/src/gas.ts
Bug fix: Gas fees are being truncated instead of rounded up, resulting in insufficient gas fees suggested to Keplr wallet.
Also note that Keplr's has already implemented this change in their own code.
[QAS-81: Fix gas fee rounding error for AKT deposits in Osmosis FE](https://linear.app/osmosis/issue/QAS-81/fix-gas-fee-rounding-error-for-akt-deposits-in-osmosis-fe)
- replaced truncate with round up for gas fees.
I was able to deploy to vercel and test there.
=> fix: round up gas fees instead of truncating to match Keplr calculation
